// 記事を1か所で読み込む。ページ側はこれを import するだけでよい
import "./shussan";
import "./ikuji";
import "./kyoikuhi";
import "./shunyu";
import "./timing";
import "./chiiki";
import "./chiiki2";

// 自治体ごとの記事。人口の多いところから順に追加している
import "./city-yokohama";
import "./city-osaka";
import "./city-nagoya";
import "./city-sapporo";
import "./city-fukuoka";
import "./city-kawasaki";
import "./city-kobe";
import "./city-kyoto";
import "./city-saitama";
import "./city-hiroshima";
import "./city-sendai";
import "./city-chiba";
import "./city-kitakyushu";
import "./city-sakai";
import "./city-niigata";
import "./city-kumamoto";
import "./city-sagamihara";
import "./city-shizuoka";
import "./city-okayama";
