import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  { slug: "hokatsu-schedule", citySlug: "chikushino", title: "筑紫野市の保活スケジュール　申込から内定までの流れ", description: "筑紫野市の認可保育園の申込時期・選考の流れをまとめました。令和8年度4月入園の動き方を解説します。", image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: "<h2>筑紫野市の4月入園スケジュール</h2><p>筑紫野市の認可保育園は毎年秋に翌年度4月入園の一次申込を受付けます。実施基準指数表を理解して準備を進めましょう。</p><h3>保活の全体スケジュール</h3><div class=\"step\"><div class=\"step-num\">1</div><div class=\"step-content\"><strong>4月〜6月：情報収集</strong><p>筑紫野市のホームページで保育園の一覧や前年度のボーダー（最低指数一覧）を確認します。</p></div></div><div class=\"step\"><div class=\"step-num\">2</div><div class=\"step-content\"><strong>7月〜9月：保育園見学</strong><p>筑紫野市内の保育園を見学して、通勤経路との相性を確認しましょう。</p></div></div><div class=\"step\"><div class=\"step-num\">3</div><div class=\"step-content\"><strong>9月〜10月：書類準備</strong><p>就労証明書の月あたり勤務日数と週あたり勤務時間は正確に記載してもらいましょう。指数に直結します。</p></div></div><div class=\"step\"><div class=\"step-num\">4</div><div class=\"step-content\"><strong>10月：申込書類の提出</strong><p>4月一次の申込期限は例年10月中旬です。期限厳守で提出しましょう。</p></div></div><div class=\"point-box\"><p><strong>ポイント</strong></p><p>筑紫野市の基準指数は父母各最大20点（合計40点満点）です。月の勤務日数と週の勤務時間の両方で判定される制度です。</p></div>", publishedAt: "2026-04-26", popularity: 55 },
  { slug: "scoring-system-guide", citySlug: "chikushino", title: "筑紫野市の入園点数のしくみ　基準指数と調整指数を解説", description: "筑紫野市の保育園入園選考で使われる基準指数と調整指数のしくみをわかりやすく解説します。", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: "<h2>筑紫野市の選考指数とは</h2><p>筑紫野市の認可保育園は「基準指数（父＋母）＋調整指数」の合計で選考されます。</p><h3>基準指数（父母各最大20点、合計40点）</h3><p>就労の場合、月20日以上かつ週40時間以上の就労で満点の<span class=\"highlight\">20点</span>です。福岡県内の標準的な基準に準じています。</p>", publishedAt: "2026-04-26", popularity: 60 },
  { slug: "score-up-tips", citySlug: "chikushino", title: "筑紫野市で点数を上げるコツ　勤務日数と勤務時間の活用法", description: "筑紫野市の保育園入園で点数を上げるための具体的な方法をまとめました。勤務日数と勤務時間の両方がポイントです。", image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop", category: "加点・減点", categoryColor: "amber", content: "<h2>筑紫野市で点数を上げる方法</h2><p>基準指数で高得点を得るには、月あたりの勤務日数と週あたりの勤務時間の両方が重要です。</p><div class=\"point-box\"><p><strong>重要</strong></p><p>筑紫野市は「月20日以上かつ週40時間以上」で満点です。どちらか一方だけでは満点になりません。</p></div>", publishedAt: "2026-04-26", popularity: 58 },
  { slug: "tiebreaker-rules", citySlug: "chikushino", title: "筑紫野市の同点時のルール　どうやって決まる？", description: "筑紫野市の保育園で同じ点数の場合、どのような順序で入園が決まるのかを解説します。", image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: "<h2>同点の場合の順位決定</h2><p>筑紫野市では、基準指数＋調整指数が同じ場合、母親の基準指数が高い家庭を優先します。</p>", publishedAt: "2026-04-26", popularity: 52 },
  { slug: "part-time-work-score", citySlug: "chikushino", title: "筑紫野市でパートタイマーの点数　日数と時間の関係", description: "筑紫野市でパートタイマーとして働く場合の点数計算方法をわかりやすく解説。月12日以上48時間以上の範囲です。", image: "https://images.unsplash.com/photo-1581092916550-e323be2ae537?w=800&h=400&fit=crop", category: "加点・減点", categoryColor: "amber", content: "<h2>パート勤務での点数</h2><p>筑紫野市ではパート勤務でも認可保育園の入園要件を満たします。月48時間以上で基準指数10点です。</p><div class=\"warn-box\"><p><strong>注意</strong></p><p>最低でも月48時間の就労が必要です。就労証明書に正確な情報を記載しましょう。</p></div>", publishedAt: "2026-04-26", popularity: 50 },
  { slug: "single-parent-score", citySlug: "chikushino", title: "筑紫野市のひとり親保活　加点と選考優遇", description: "筑紫野市でひとり親家庭が使える加点制度と選考上の優遇措置をまとめました。", image: "https://images.unsplash.com/photo-1516627145497-ae6968895b2f?w=800&h=400&fit=crop", category: "加点・減点", categoryColor: "amber", content: "<h2>ひとり親家庭の保活は有利</h2><p>筑紫野市ではひとり親世帯に対して調整指数+5点の加点があります。これは大きなアドバンテージです。</p>", publishedAt: "2026-04-26", popularity: 48 },
  { slug: "parental-leave-timing", citySlug: "chikushino", title: "筑紫野市の育児休業と保活　復帰タイミングの重要性", description: "筑紫野市で育児休業から復帰する際の保活のタイミングと加点制度を解説します。", image: "https://images.unsplash.com/photo-1564631521675-32f1c18b1dce?w=800&h=400&fit=crop", category: "書類・手続き", categoryColor: "teal", content: "<h2>育児休業からの復帰と保活</h2><p>筑紫野市では育児休業を取得し入園月に復帰する場合、調整指数+2点の加点があります。</p>", publishedAt: "2026-04-26", popularity: 46 },
  { slug: "nursery-wait-time", citySlug: "chikushino", title: "筑紫野市の認可外保育施設利用と入園スケジュール", description: "筑紫野市で認可外保育施設を利用しながら認可園を待つ場合のポイントをまとめました。", image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=400&fit=crop", category: "施設の種類", categoryColor: "rose", content: "<h2>認可外保育施設と認可園申込</h2><p>筑紫野市では認可外保育施設の利用者が+3点の加点を受けられます。</p>", publishedAt: "2026-04-26", popularity: 54 },
  { slug: "application-checklist", citySlug: "chikushino", title: "筑紫野市の申込書類チェックリスト　書き忘れを防ぐ", description: "筑紫野市の保育園申込に必要な書類と、準備のチェックリストです。", image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop", category: "書類・手続き", categoryColor: "teal", content: "<h2>申込に必要な書類</h2><p>筑紫野市への保育園申込には様々な書類が必要です。期限に遅れないよう早めに準備しましょう。</p>", publishedAt: "2026-04-26", popularity: 56 },
  { slug: "unlicensed-nursery", citySlug: "chikushino", title: "筑紫野市の認可外保育施設　費用と選び方", description: "筑紫野市の認可外保育施設について、費用相場と選択のポイントをまとめました。", image: "https://images.unsplash.com/photo-1576438817882-a0f6b33b9e64?w=800&h=400&fit=crop", category: "施設の種類", categoryColor: "rose", content: "<h2>認可外保育施設の特徴</h2><p>筑紫野市の認可外保育施設は認可園を待つ間の利用が多いです。月ぎめで利用すると加点対象になります。</p>", publishedAt: "2026-04-26", popularity: 51 },
];

registerArticles(articles);
