import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "fuji",
    title: "富士市の保活スケジュール　申込から内定までの流れ",
    description: "富士市の認可保育園の申込時期・選考の流れをまとめました。令和8年度4月入園の動き方を解説します。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>富士市の4月入園スケジュール</h2><p>富士市の認可保育園は毎年秋に翌年度4月入園の一次申込を受付けます。実施基準指数表を理解して準備を進めましょう。</p><h3>保活の全体スケジュール</h3><div class="step"><div class="step-num">1</div><div class="step-content"><strong>4月〜6月：情報収集</strong><p>富士市のホームページで保育園の一覧や前年度のボーダー（最低指数一覧）を確認します。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>7月〜9月：保育園見学</strong><p>富士市内の保育園を見学して、通勤経路との相性を確認しましょう。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>9月〜10月：書類準備</strong><p>就労証明書の月あたり就労時間は正確に記載してもらいましょう。指数に直結します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>11月：申込書類の提出</strong><p>4月一次の申込期限は例年11月中旬です。期限厳守で提出しましょう。</p></div></div><div class="point-box"><p><strong>ポイント</strong></p><p>富士市の基準指数は父母各最大20点（合計40点満点）です。月の就労時間で判定される制度です。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 55,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "fuji",
    title: "富士市の保活でよくある失敗と対策",
    description: "富士市で保活を成功させるために、よくある失敗事例と対策をまとめました。",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>富士市の保活で失敗しないために</h2><p>保活はタイミングと準備が重要です。よくある失敗を事前に知っておくことで、防げます。</p><h3>よくある失敗事例と対策</h3><ul><li><strong>申込期限を逃す</strong> - 大事な書類の期限をカレンダーに記入して管理</li><li><strong>希望園を決めきれない</strong> - 6月までに最低10園はリストアップしておく</li><li><strong>就労時間を正確に記載しない</strong> - 会社に確認し、雇用契約書で再度チェック</li><li><strong>調整指数の加点を見落とす</strong> - ひとり親、生活保護など全項目を確認</li><li><strong>認可外の利用を報告しない</strong> - 認可外利用は加点になるため必ず報告</li></ul><div class="warn-box"><p><strong>注意</strong></p><p>虚偽の申告は入園取消しの対象です。正確な情報を提供しましょう。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 48,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "fuji",
    title: "富士市の入園点数のしくみ　基準指数と調整指数を解説",
    description: "富士市の保育園入園選考で使われる基準指数と調整指数のしくみをわかりやすく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>富士市の選考指数とは</h2><p>富士市の認可保育園は「基準指数（父＋母）＋調整指数」の合計で選考されます。</p><div class="point-box"><p><strong>ポイント</strong></p><p>利用調整指数＝基準指数（父＋母）＋調整指数</p></div><h2>基準指数（父母各最大20点、合計40点）</h2><p>就労の場合、月160時間以上の就労で満点の<span class="highlight">20点</span>です。</p><table><tr><th>月の就労時間</th><th>指数</th></tr><tr><td>月160時間以上</td><td>20</td></tr><tr><td>月120時間以上160時間未満</td><td>18</td></tr><tr><td>月100時間以上120時間未満</td><td>16</td></tr><tr><td>月80時間以上100時間未満</td><td>14</td></tr><tr><td>月64時間以上80時間未満</td><td>12</td></tr><tr><td>月48時間以上64時間未満</td><td>8</td></tr></table><h2>調整指数の代表例</h2><ul><li>ひとり親就労：<span class="highlight">+5点</span></li><li>きょうだい在園中：<span class="highlight">+3点</span></li><li>認可外利用：<span class="highlight">+3点</span></li><li>生活保護世帯：<span class="highlight">+3点</span></li><li>きょうだい同時申込：<span class="highlight">+2点</span></li><li>育休復帰予定：<span class="highlight">+2点</span></li></ul>`,
    publishedAt: "2026-04-12",
    popularity: 60,
  },
  {
    slug: "working-hours-points",
    citySlug: "fuji",
    title: "富士市の就労時間と点数の関係を解説",
    description: "富士市で就労時間がどう点数に反映されるか、時間帯による違いをまとめました。",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>就労時間と点数の大切な関係</h2><p>富士市では月あたりの就労時間が直接、点数に反映されます。8時間の違いが重要です。</p><h3>時間帯の区分と点数</h3><p>富士市の基準指数は次のように設定されています：</p><ul><li>月160時間以上：20点（フルタイム）</li><li>月120時間以上：18点（概ね月3日程度の欠勤）</li><li>月100時間以上：16点（週25時間程度）</li><li>月80時間以上：14点（週20時間程度）</li><li>月64時間以上：12点（週16時間程度）</li><li>月48時間以上：8点（週12時間程度）</li></ul><div class="point-box"><p><strong>重要</strong></p><p>就労時間には通勤時間は含まれません。実際の業務時間で計算してください。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 52,
  },
  {
    slug: "adjustment-points-guide",
    citySlug: "fuji",
    title: "富士市の調整指数　加点・減点の活用法",
    description: "富士市の保育園入園で調整指数の加点と減点を最大限に活用する方法。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "加点・減点",
    categoryColor: "amber",
    content: `<h2>調整指数で差がつく</h2><p>フルタイム共働き世帯は基準指数40点で横並びです。差がつくのは調整指数です。</p><h3>主な加点項目</h3><ul><li>ひとり親で就労中：+5点</li><li>きょうだいが在園中：+3点</li><li>認可外を利用中：+3点</li><li>生活保護受給中：+3点</li><li>きょうだい同時申込：+2点</li><li>育休から復帰予定：+2点</li></ul><h3>減点項目（注意）</h3><ul><li>祖父母が同居で保育可能：-3点</li><li>認可園から転園希望：-5点</li><li>市外からの申込：-10点</li></ul><div class="point-box"><p><strong>ポイント</strong></p><p>富士市外から申込する場合は-10点の大幅減点があります。市内転居を検討しましょう。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 57,
  },
  {
    slug: "single-parent-guide",
    citySlug: "fuji",
    title: "富士市のひとり親保活ガイド　加点と優遇制度",
    description: "富士市でひとり親家庭が使える加点制度と選考上の優遇措置をまとめました。",
    image: "https://images.unsplash.com/photo-1516627145497-ae6968895b2f?w=800&h=400&fit=crop",
    category: "加点・減点",
    categoryColor: "amber",
    content: `<h2>ひとり親家庭の保活は有利</h2><p>富士市ではひとり親家庭に対して調整指数+5点の加点があります。これは大きなアドバンテージです。</p><h3>ひとり親の+5点について</h3><p>母子家庭・父子家庭で現在就労中、または就労が内定している場合に加点されます。</p><div class="point-box"><p><strong>条件</strong></p><ul><li>戸籍上、一方の親がいない状態</li><li>就労中または就労予定</li><li>養育費受取人でも対象になる場合あり</li></ul></div><h3>その他の注意点</h3><p>生活保護受給中の場合はさらに+3点加算される可能性があります。福祉事務所に相談しましょう。</p>`,
    publishedAt: "2026-04-12",
    popularity: 45,
  },
  {
    slug: "nursery-options",
    citySlug: "fuji",
    title: "富士市の認可・認可外保育施設　違いと選び方",
    description: "富士市での認可保育園と認可外保育施設の違い、選び方のポイントをまとめました。",
    image: "https://images.unsplash.com/photo-1564631521675-32f1c18b1dce?w=800&h=400&fit=crop",
    category: "施設の種類",
    categoryColor: "rose",
    content: `<h2>富士市の保育施設選びのポイント</h2><p>保育施設には認可と認可外があります。それぞれの特徴を理解して選びましょう。</p><h3>認可保育園</h3><ul><li>市が管理・監督する公式な保育施設</li><li>保育士配置、施設基準が法令で定められている</li><li>利用料は市の基準に基づき設定</li><li>富士市で選考対象となる</li><li>待機児童が発生することがある</li></ul><h3>認可外保育施設</h3><ul><li>市の基準を満たさない小規模な施設</li><li>料金・保育時間が自由に設定されている</li><li>認可外利用で加点（+3点）がもらえる</li><li>認可園入園までの繋ぎとして利用される</li></ul><div class="point-box"><p><strong>ポイント</strong></p><p>認可外を月ぎめで利用していると、認可園申込時に+3点の加点がもらえます。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 51,
  },
  {
    slug: "interview-tips",
    citySlug: "fuji",
    title: "富士市の保育園見学で押さえるべきポイント",
    description: "富士市の保育園見学で確認すべき項目と、質問の例をまとめました。",
    image: "https://images.unsplash.com/photo-1581092916550-e323be2ae537?w=800&h=400&fit=crop",
    category: "施設の種類",
    categoryColor: "rose",
    content: `<h2>保育園見学で何を見るべきか</h2><p>保育園選びは見学が重要です。事前にチェックリストを用意しましょう。</p><h3>見学時に確認するポイント</h3><ul><li>園舎の衛生状態と安全対策</li><li>保育士の数と子どもとの関わり方</li><li>園庭の広さと遊具</li><li>給食・おやつの内容</li><li>延長保育や一時保育の有無</li><li>通園時間（通勤経路との相性）</li><li>かかりやすい病院の位置</li></ul><h3>質問の例</h3><ul><li>「保育方針について教えてください」</li><li>「アレルギー対応はどのようにしていますか」</li><li>「保護者の参加行事はどの程度ありますか」</li><li>「sick leave時の対応は」</li></ul><div class="point-box"><p><strong>アドバイス</strong></p><p>可能であれば複数の時間帯に見学し、園全体の雰囲気を掴みましょう。</p></div>`,
    publishedAt: "2026-04-12",
    popularity: 49,
  },
  {
    slug: "hokatsu-faq",
    citySlug: "fuji",
    title: "富士市の保活FAQ　よくある質問と回答",
    description: "富士市の保活についてよくある質問と、その回答をまとめました。",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop",
    category: "Q&A",
    categoryColor: "purple",
    content: `<h2>富士市の保活よくある質問</h2><h3>Q. 認可外を使ったら認可園の申込に不利になりますか？</h3><p>A. いいえ、むしろ有利です。認可外利用は+3点の加点がもらえます。</p><h3>Q. 妊娠中の申込はできますか？</h3><p>A. できます。出産予定日が入園予定月内であれば、出産理由で申込できます。</p><h3>Q. 希望する園に落ちた場合、二次募集はありますか？</h3><p>A. あります。富士市は4月一次、6月二次募集を実施しています。</p><h3>Q. 点数が同じ場合、どのように順位が決まりますか？</h3><p>A. 市が定めた同点時の優先順位ルールに従います。詳しくは申込のしおりをご確認ください。</p><h3>Q. 就労時間が月によって変わる場合は？</h3><p>A. 直近3ヶ月の平均で計算されます。月ごとのばらつきは考慮されません。</p>`,
    publishedAt: "2026-04-12",
    popularity: 54,
  },
  {
    slug: "documents-checklist",
    citySlug: "fuji",
    title: "富士市の申込書類チェックリスト　書き忘れを防ぐ",
    description: "富士市の保育園申込に必要な書類と、準備のチェックリストです。",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop",
    category: "書類・手続き",
    categoryColor: "teal",
    content: `<h2>申込に必要な書類</h2><p>富士市への保育園申込には様々な書類が必要です。期限に遅れないよう早めに準備しましょう。</p><h3>主な書類チェックリスト</h3><ul><li>□ 保育施設利用申込書</li><li>□ 就労証明書（父母各1通）</li><li>□ 家庭状況報告書</li><li>□ 調整指数に関わる証明書</li><li>□ 住民票の写し</li><li>□ 本人確認書類</li><li>□ 戸籍抄本（ひとり親の場合）</li><li>□ 福祉事務所の証明書（生活保護の場合）</li><li>□ 認可外保育施設の利用証明書</li><li>□ 医師の診断書（疾病の場合）</li></ul><div class="warn-box"><p><strong>重要</strong></p><p>就労証明書は会社に記入してもらう必要があります。余裕をもって9月中に依頼しましょう。</p></div><h3>提出のコツ</h3><p>書類は第一希望園を経由して市へ提出するか、市の窓口に直接提出します。提出期限の2日前までに準備を完了させましょう。</p>`,
    publishedAt: "2026-04-12",
    popularity: 53,
  },
];

registerArticles(articles);
