import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "ginowan",
    title: "宜野湾市の保活スケジュール　令和8年度4月入園の流れ",
    description: "宜野湾市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>宜野湾市は沖縄県の中部に位置し、人口約10万人の都市です。那覇市の北隣に位置し、米軍基地との関係で独特の特性があります。申込先は宜野湾市こども家庭部保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月中旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>一次で不承諾だった方は自動的に二次の対象になります。沖縄県の地理的特性により、県内他市との比較を検討する家庭も多くいます。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "ginowan",
    title: "宜野湾市の保活でよくある失敗と対策5選",
    description: "宜野湾市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>宜野湾市の4月入園の申込は10月から始まります。見学の予約が埋まる前に動きましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>宜野湾市では希望園を複数記入できます。1〜2園しか書かないと不承諾のリスクが高まります。</p><h2>失敗3：自分の点数を把握していない</h2><p>宜野湾市では基本指数＋調整指数で選考されます。両親ともに月160時間以上の就労で基本指数は各10点、合計20点が基本ラインです。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親世帯は+6点、生活保護受給で+2点、きょうだい在園で+1点の加点があります。使える加点は漏れなくチェックしましょう。</p><h2>失敗5：書類の不備</h2><p>就労証明書の記入漏れや指定様式以外の提出は受理されない場合があります。宜野湾市のホームページで最新の様式を確認しましょう。</p>`,
    publishedAt: "2026-05-08",
    popularity: 42,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "ginowan",
    title: "宜野湾市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "宜野湾市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。宜野湾市は沖縄県の中部に位置し、人口約10万人です。</p><h2>宜野湾市の保育園の種類</h2><ul><li>認可保育園：宜野湾市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可基準を満たさないが届出済みの施設。</li></ul><p>沖縄県内では待機児童が少ないエリアもありますが、宜野湾市は比較的人気が高いため早めの準備が重要です。</p>`,
    publishedAt: "2026-05-08",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "ginowan",
    title: "宜野湾市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "宜野湾市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>宜野湾市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各10点ずつ、基本指数の合計は20点になります。これが宜野湾市の基本指数の満点です。</p><h3>就労時間別の指数</h3><ul><li>月160時間以上：10点</li><li>月140～160時間：9点</li><li>月120～140時間：8点</li><li>月100～120時間：7点</li><li>月80～100時間：6点</li><li>月64～80時間：5点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 46,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "ginowan",
    title: "宜野湾市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "宜野湾市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。宜野湾市の調整指数は以下の通りです。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+6点</li><li>生活保護受給：+2点</li><li>きょうだいが在園中：+1点</li><li>保育士就労：+6点</li></ul><h3>減算項目</h3><ul><li>市外からの申込：-3点（場合によって）</li></ul><div class="point-box"><p>調整指数は世帯の事情により大きく変わります。自分の家庭に当てはまる項目をしっかり把握することが、入園率を上げるコツです。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 43,
  },
  {
    slug: "selection-process",
    citySlug: "ginowan",
    title: "宜野湾市の保育園選考フロー　書類提出から入園決定まで",
    description: "宜野湾市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月中に、宜野湾市こども家庭部保育課へ提出します。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>宜野湾市が申込書類に基づいて指数を計算します。基本指数と調整指数の合計が選考指数になります。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 37,
  },
  {
    slug: "score-up-checklist",
    citySlug: "ginowan",
    title: "宜野湾市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "宜野湾市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親で就労中→+6点</li><li>生活保護を受給中→+2点</li><li>きょうだいが希望施設に在園中→+1点</li><li>保育士として就労中→+6点</li></ul><div class="point-box"><p>宜野湾市では保育士就労による加点が比較的高く設定されています。保育業界への就職を検討している家庭は、就職時期を入園のタイミングに合わせることで大幅な加点が期待できます。</p></div><h2>加点を活用した戦略</h2><p>複数の加点条件に当てはまる場合、合算される仕組みになっています。例えば、ひとり親で生活保護受給の場合は+6点+2点=+8点の加点が得られます。</p>`,
    publishedAt: "2026-05-08",
    popularity: 50,
  },
  {
    slug: "area-guide",
    citySlug: "ginowan",
    title: "宜野湾市の保育園マップ　エリアごとの入りやすさを比較",
    description: "宜野湾市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>宜野湾市の保育園事情</h2><p>宜野湾市は沖縄県の中部に位置する人口約10万人の都市です。認可保育園は約25か所あります。那覇市の北隣に位置し、通勤の利便性が高いため、保育園入園の競争率も比較的高い傾向があります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>宜野湾中央地区：市役所周辺で交通の便が良い</li><li>嘉数地区：新規住宅地で需要が高い</li></ul><h3>比較的入りやすいエリア</h3><ul><li>佐真下・大山地区：市街地から離れるため、空きがある園も</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 33,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "ginowan",
    title: "宜野湾市の認可外保育施設ガイド　認可園との違いは？",
    description: "宜野湾市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。宜野湾市内にも複数存在します。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の入園加点</td><td>-</td><td>加点の対象となる場合あり</td></tr></table><div class="point-box"><p>認可外に預けながら翌年度の認可園を再申請すると、加点がつく場合があるため入りやすくなることがあります。宜野湾市のホームページで詳細をご確認ください。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 31,
  },
  {
    slug: "nursery-fees",
    citySlug: "ginowan",
    title: "宜野湾市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "宜野湾市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。宜野湾市でも同様に適用されています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～5,000円</td></tr><tr><td>300～500万円</td><td>8,000～20,000円</td></tr><tr><td>500～700万円</td><td>20,000～38,000円</td></tr><tr><td>700～1,000万円</td><td>38,000～52,000円</td></tr></table><div class="point-box"><p>宜野湾市では第2子の保育料は半額、第3子以降は無料になります。また、沖縄県の支援制度により、さらなる減免がある場合もあります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 44,
  },
  {
    slug: "nursery-visit-guide",
    citySlug: "ginowan",
    title: "宜野湾市の保育園見学ガイド　チェックポイントと質問リスト",
    description: "宜野湾市の保育園見学で確認すべきポイントと、先輩ママが聞いてよかった質問をまとめました。",
    image: "https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>見学はいつ行くのがベスト？</h2><p>5月～8月が見学のベストシーズンです。9月以降は申込直前で混み合います。</p><h2>見学時のチェックポイント</h2><ul><li>園児たちの表情や雰囲気</li><li>保育士の子どもへの接し方</li><li>園庭や室内の広さ・清潔さ・沖縄の気候への対応</li><li>給食の内容（アレルギー対応）</li></ul><h2>聞いておきたい質問リスト</h2><ul><li>延長保育は何時まで？料金は？</li><li>慣らし保育の期間はどのくらい？</li><li>急な発熱時のお迎えルール</li><li>沖縄の暑さ対策について</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 39,
  },
];

registerArticles(articles);
