import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "handa",
    title: "半田市の保活スケジュール　令和8年度4月入園の流れ",
    description: "半田市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>半田市は愛知県知多半島北部に位置し、人口約12万人の都市です。ミツカン（中埜酢店）発祥の地として知られ、醸造業・食品産業が盛んな都市です。名古屋市へのアクセスも良好です。申込先は半田市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>半田市の選考指数は父母各20点の合計40点満点（愛知県標準方式）です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "handa",
    title: "半田市の保活でよくある失敗と対策5選",
    description: "半田市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>半田市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>半田市は醸造業・製造業が盛んで共働き世帯も多い地域です。人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>半田市は父母各20点の合計40点制（愛知県標準方式）です。月64時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+6点、生活保護で+5点、きょうだい同施設在園で+5点、認可外利用で+4点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：就労内定（内定あり）の活用を忘れる</h2><p>半田市では就労予定（内定あり）で+8点の基本指数が付きます。育休復帰の際に就労内定として申告できる場合があります。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "handa",
    title: "半田市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "半田市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。半田市は愛知県知多半島北部に位置し、人口約12万人。醸造業・食品産業が盛んな都市です。</p><h2>半田市の保育施設の種類</h2><ul><li>認可保育所：半田市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "handa",
    title: "半田市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "半田市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>半田市の保育施設入園は指数方式（愛知県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li><li>就労内定（内定あり）：8点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "handa",
    title: "半田市の調整指数ガイド　加点の全項目まとめ",
    description: "半田市の保育入園選考で基本指数に加算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>半田市では基本指数に加えて、世帯の状況に応じた調整指数が加算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+6点</td></tr><tr><td>生活保護受給世帯</td><td>+5点</td></tr><tr><td>きょうだいが同施設に在園中</td><td>+5点</td></tr><tr><td>きょうだいと同時申込み</td><td>+3点</td></tr><tr><td>認可外保育施設に月ぎめで利用中</td><td>+4点</td></tr><tr><td>育児休業から復帰予定</td><td>+4点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "handa",
    title: "半田市のひとり親家庭の保活　+6点加点の活用法",
    description: "半田市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>半田市では、ひとり親世帯に対して+6点の調整指数加点があります。フルタイム就労20点＋ひとり親6点で26点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+6点）に加えて認可外利用中（+4点）、育休復帰（+4点）なども活用できます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "handa",
    title: "半田市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "半田市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>半田市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140〜160時間未満</td><td>18点</td></tr><tr><td>月120〜140時間未満</td><td>16点</td></tr><tr><td>月100〜120時間未満</td><td>14点</td></tr><tr><td>月80〜100時間未満</td><td>12点</td></tr><tr><td>月64〜80時間未満</td><td>10点</td></tr></table><h2>醸造業・食品産業の場合</h2><p>半田市はミツカン発祥の地で醸造業が盛んです。食品工場や醸造業での勤務でも、実際の月間就労時間で指数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "handa",
    title: "半田市で育休復帰を目指すママへ　+4点加点の活用法",
    description: "半田市で育休から復帰するタイミングで保活をする方向けに、育休復帰加点（+4点）の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+4点）</h2><p>半田市では、育児休業から復帰して入園する場合に+4点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園月の翌月1日までに復職すること</li><li>事業主からの復職予定証明書が必要</li></ul><div class="point-box"><p>フルタイム20点＋育休復帰+4点で24点が確保できます。さらに認可外利用加点（+4点）との合算で28点まで上げることができます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "handa",
    title: "半田市の認可保育施設一覧　地区別の施設数と特徴",
    description: "半田市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>半田市の保育施設の概要</h2><p>半田市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。半田駅・亀崎駅周辺や市内各地に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>半田駅・阿久比駅周辺：施設数が多く利便性が高い</li><li>乙川・板山地区：比較的定員に余裕のある施設が多い</li><li>亀崎・岩滑地区：住宅地で施設が点在</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "unlicensed-nursery",
    citySlug: "handa",
    title: "半田市の認可外保育施設利用中の加点　+4点の条件と申請方法",
    description: "半田市で認可外保育施設を月ぎめで利用している場合の加点（+4点）について、条件と申請方法を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>認可外保育施設利用中の加点</h2><p>半田市では、申込時点で認可外保育施設を月ぎめで利用している場合に+4点の調整指数が加算されます。</p><h2>加点を受けるための条件</h2><ul><li>認可外保育施設（企業主導型保育事業等を含む）に月ぎめで在籍していること</li><li>申込時点で実際に利用中であること</li><li>在籍証明書または利用契約書の写しを提出</li></ul><div class="point-box"><p>認可外保育施設の利用料は高めですが、+4点の加点と育休復帰加点（+4点）の合計+8点で入園の可能性が大きく高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 37,
  },
];

registerArticles(articles);
