import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "iga",
    title: "伊賀市の保活スケジュール　令和8年度4月入園の流れ",
    description: "伊賀市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>伊賀市は三重県北西部に位置する忍者の里です。人口約8万5千人で、2004年に上野市・阿山郡4町1村が合併して誕生しました。伊賀忍者・伊賀上野城が有名で、伊賀鉄道（旧近鉄伊賀線）があり、津市・名張市に隣接しています。申込先は伊賀市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>伊賀市は基本指数が高い自治体です。フルタイム共働きで世帯最大110点（1人最大55点）の指数が付きます。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 46,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "iga",
    title: "伊賀市の保活でよくある失敗と対策5選",
    description: "伊賀市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：合併による旧市町村の違いを忘れる</h2><p>伊賀市は2004年の合併で誕生した市です。旧上野市と旧阿山郡エリアで施設数や待機状況が異なります。全体像を把握しましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>伊賀市は人口約8万5千人で、待機児童が生じる時期があります。希望施設は複数記入が必須です。</p><h2>失敗3：自分の点数を把握していない</h2><p>伊賀市は基本指数が高く、月48時間未満では基本指数が付きません。就労時間を正確に把握することが重要です。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+70点、きょうだい同時申込で+5点、きょうだい既在園で+8点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>伊賀市では65歳未満の同居祖父母が保育できる状態の場合に-5点となります。</p>`,
    publishedAt: "2026-05-15",
    popularity: 50,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "iga",
    title: "伊賀市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "伊賀市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。伊賀市は三重県北西部に位置し、忍者の里として有名です。人口約8万5千人で、伊賀忍者の文化が根付いた地域です。</p><h2>伊賀市の保育施設の種類</h2><ul><li>認可保育所：伊賀市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 48,
  },
  {
    slug: "point-system",
    citySlug: "iga",
    title: "伊賀市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "伊賀市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>伊賀市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大55点、合計110点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月180時間以上：54点</li><li>月168～180時間未満：51点</li><li>月156～168時間未満：48点</li><li>月144～156時間未満：45点</li><li>月120～144時間未満：40点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 52,
  },
  {
    slug: "adjustment-index",
    citySlug: "iga",
    title: "伊賀市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "伊賀市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>伊賀市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+70点</td></tr><tr><td>きょうだいが既に利用している施設を希望（転園含む）</td><td>+8点</td></tr><tr><td>きょうだいがその年度内に同一保育所等の利用を希望</td><td>+5点</td></tr><tr><td>認可外保育施設を週3日以上利用中</td><td>+5点</td></tr><tr><td>生活保護受給世帯</td><td>+50点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-5点</td></tr></table>`,
    publishedAt: "2026-05-15",
    popularity: 50,
  },
  {
    slug: "single-parent",
    citySlug: "iga",
    title: "伊賀市のひとり親家庭の保活　+70点加点の活用法",
    description: "伊賀市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>伊賀市では、ひとり親世帯に対して+70点の調整指数加点があります。フルタイム就労最大55点＋ひとり親70点で大きくアップできます。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+70点）に加えて認可外利用中（+5点）、育休関連の加点などを活用することで、さらに指数を上げることができます。</p>`,
    publishedAt: "2026-05-15",
    popularity: 44,
  },
  {
    slug: "working-mothers",
    citySlug: "iga",
    title: "伊賀市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "伊賀市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>伊賀市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140～160時間未満</td><td>18点</td></tr><tr><td>月120～140時間未満</td><td>16点</td></tr><tr><td>月100～120時間未満</td><td>14点</td></tr></table><h2>津・名張への通勤を考慮</h2><p>伊賀市は津市・名張市に隣接しており、広域通勤者も多い地域です。実際の勤務地までの移動時間を考慮した申告が必要です。</p>`,
    publishedAt: "2026-05-15",
    popularity: 49,
  },
  {
    slug: "ikukyu-return",
    citySlug: "iga",
    title: "伊賀市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "伊賀市で育休から復帰するタイミングで保活をする方向けに、基本指数・調整指数と育児休業の関係を解説します。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育児休業と伊賀市の選考指数</h2><p>伊賀市の基準表には、育児休業による調整指数加点の項目はありません。ただし、転園の場合で育児休業中に他の児童の継続入所を希望する場合は、基本指数で+25点が加点されることがあります。</p><h2>育休復帰時の注意点</h2><ul><li>育児休業中に新規入園を申し込む場合、基本指数は育休による加点ではなく、他の事由の判定になります</li><li>復職予定が決まっていれば、就労事由による基本指数が加点されます</li><li>基本指数の判定の詳細は、市の子育て支援課に相談してください</li></ul><div class="point-box"><p>伊賀市では調整指数の組み合わせが重要です。ひとり親加点（+70点）や認可外利用加点（+5点）など、活用できる加点を確認しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 47,
  },
  {
    slug: "nursery-facilities",
    citySlug: "iga",
    title: "伊賀市の認可保育施設一覧　地区別の施設数と特徴",
    description: "伊賀市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>伊賀市の保育施設の概要</h2><p>伊賀市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。旧上野市・旧阿山郡エリアなど各地区に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>上野地区：市街地で施設数が多く利便性が高い</li><li>郊外地域：比較的定員に余裕のある施設が多い</li><li>広域利用も可能な地域配置</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 40,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "iga",
    title: "伊賀市の祖父母同居の減点　-5点の条件と対処法",
    description: "伊賀市で65歳未満の同居祖父母がいる場合の減点（-5点）について、条件と対処法を解説します。",
    image: "https://images.unsplash.com/photo-1545533935-49ca15b58b9c?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居の減点とは</h2><p>伊賀市では、65歳未満の同居祖父母が保育できる状態にある場合、-5点の調整指数が適用されます。</p><h2>減点が適用される条件</h2><ul><li>65歳未満の祖父母が同居している</li><li>その祖父母が保育可能な状態（無職・就労時間が少ない等）</li></ul><h2>減点が適用されない条件</h2><ul><li>同居祖父母が65歳以上の場合</li><li>同居祖父母がフルタイムで就労している場合</li><li>同居祖父母が疾病・障害等で保育不可能な場合</li></ul><div class="point-box"><p>同居祖父母が就労している場合は就労証明書を提出することで減点を回避できる場合があります。市役所に確認しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 43,
  },
];

registerArticles(articles);
