import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "inazawa",
    title: "稲沢市の保活スケジュール　令和8年度4月入園の流れ",
    description: "稲沢市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>稲沢市は愛知県中部に位置し、人口約13万8千人の都市です。名古屋市の北側に位置するベッドタウンとして発展しており、製造業・物流業が主要産業です。国府宮神社の「はだか祭」で知られる歴史ある地域です。申込先は稲沢市子ども健康部子ども・家庭課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>稲沢市の選考指数は父母各20点の合計40点満点です。就労予定（内定あり）でも8点の指数が付きます。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "inazawa",
    title: "稲沢市の保活でよくある失敗と対策5選",
    description: "稲沢市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>稲沢市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>稲沢市は名古屋のベッドタウンとして共働き世帯が多く、人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：就労内定書の提出を忘れる</h2><p>稲沢市では就労予定（内定あり）で8点の指数が付きます。就労内定書を忘れずに提出しましょう。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+6点、きょうだい在園で+5点、育休復帰で+4点、認可外利用で+4点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：自分の点数を把握していない</h2><p>稲沢市は父母各20点の合計40点制（愛知県標準方式）です。月64時間未満では基本指数が付きません。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "inazawa",
    title: "稲沢市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "稲沢市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。稲沢市は愛知県中部に位置し、人口約13万8千人。名古屋市の北隣に位置するベッドタウンとして共働き世帯が多い地域です。</p><h2>稲沢市の保育施設の種類</h2><ul><li>認可保育所：稲沢市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>事業所内保育事業：企業が従業員向けに設置した施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "point-system",
    citySlug: "inazawa",
    title: "稲沢市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "稲沢市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>稲沢市の保育施設入園は指数方式（愛知県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上（フルタイム）：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li><li>就労予定（内定あり）：8点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "inazawa",
    title: "稲沢市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "稲沢市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>稲沢市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+6点</td></tr><tr><td>生活保護受給世帯</td><td>+5点</td></tr><tr><td>きょうだいが同施設に在園中</td><td>+5点</td></tr><tr><td>きょうだいと同時申込み</td><td>+3点</td></tr><tr><td>認可外保育施設に月ぎめで利用中</td><td>+4点</td></tr><tr><td>育児休業から復帰予定（入園月翌月1日まで）</td><td>+4点</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>稲沢市の調整指数は愛知県内でも充実しており、特にきょうだい在園加点（+5点）が高いのが特徴です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "single-parent",
    citySlug: "inazawa",
    title: "稲沢市のひとり親家庭の保活　+6点加点の活用法",
    description: "稲沢市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>稲沢市では、ひとり親世帯に対して+6点の調整指数加点があります。フルタイム就労20点＋ひとり親6点で26点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li><li>配偶者が長期不在の場合も対象になるケースがあります</li></ul><h2>さらなる加点の活用</h2><p>ひとり親加点（+6点）に加えて、認可外利用中（+4点）・育休復帰（+4点）などと合算することも可能です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "working-mothers",
    citySlug: "inazawa",
    title: "稲沢市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "稲沢市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>稲沢市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140〜160時間未満</td><td>18点</td></tr><tr><td>月120〜140時間未満</td><td>16点</td></tr><tr><td>月100〜120時間未満</td><td>14点</td></tr><tr><td>月80〜100時間未満</td><td>12点</td></tr><tr><td>月64〜80時間未満</td><td>10点</td></tr><tr><td>就労予定（内定あり）</td><td>8点</td></tr></table><h2>夫婦ともにフルタイムの場合</h2><p>両親各20点で合計40点。稲沢市で最高の基本指数となります。これに調整指数が加算されます。</p>`,
    publishedAt: "2026-05-11",
    popularity: 50,
  },
  {
    slug: "ikukyu-return",
    citySlug: "inazawa",
    title: "稲沢市で育休復帰を目指すママへ　+4点加点の活用法",
    description: "稲沢市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+4点）</h2><p>稲沢市では、育児休業から復帰して入園する場合に+4点の調整指数が加算されます。入園月の翌月1日までに復職することが条件です。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園月の翌月1日までに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+4点）は愛知県内でも比較的高い加点です。認可外利用加点（+4点）と合算できます。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "nursery-facilities",
    citySlug: "inazawa",
    title: "稲沢市の認可保育施設一覧　地区別の施設数と特徴",
    description: "稲沢市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>稲沢市の保育施設の概要</h2><p>稲沢市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。稲沢駅・国府宮駅周辺や国道155号沿いに施設が集中しています。</p><h2>地区別の傾向</h2><ul><li>稲沢・国府宮駅周辺：施設数が多く利便性が高いが競争率も高め</li><li>祖父江・平和地区：比較的定員に余裕のある施設が多い</li><li>千代田・明治地区：住宅地として発展中で施設も増加傾向</li></ul><div class="point-box"><p>第1〜第5希望まで記入できます。なるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 34,
  },
  {
    slug: "employment-cert",
    citySlug: "inazawa",
    title: "稲沢市の就労証明書の書き方ガイド　提出書類を正確に準備する",
    description: "稲沢市の保育施設申込に必要な就労証明書の書き方と、正確な月間就労時間の計算方法を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "申込手続き",
    categoryColor: "rose",
    content: `<h2>就労証明書とは</h2><p>稲沢市の保育施設申込には、就労状況を証明する書類が必要です。勤務先に記入してもらいましょう。</p><h2>月間就労時間の計算方法</h2><p>月間就労時間は「1日の就労時間×1月の就労日数」で計算します。残業時間は含めません。</p><h3>指数区分の目安</h3><ul><li>月160時間以上：週5日×8時間以上（フルタイム）</li><li>月140〜160時間：週5日×7〜8時間</li><li>月120〜140時間：週5日×6〜7時間</li><li>月100〜120時間：週5日×5〜6時間</li><li>月80〜100時間：週4〜5日×5時間</li><li>月64〜80時間：週4日×4時間</li></ul><div class="point-box"><p>就労証明書の内容が実態と異なる場合、入園取消になるケースがあります。正確な情報を記入しましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 39,
  },
];

registerArticles(articles);
