import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "isahaya",
    title: "諫早市の保活スケジュール　令和8年度4月入園の流れ",
    description: "諫早市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>諫早市は長崎県の中央部に位置し、人口約13万3千人の都市です。長崎市と佐世保市の中間に位置する交通の要衝で、製造業・農業が主要産業です。諫早湾干拓事業でも知られる地域です。申込先は諫早市子ども未来課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>諫早市の選考指数は父母各100点の合計200点満点（長崎県標準方式）です。他県と大きく異なる独自の点数体系です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "point-system",
    citySlug: "isahaya",
    title: "諫早市の200点制指数システム　長崎県標準方式をわかりやすく",
    description: "諫早市の保育施設入園選考は父母各100点・合計200点満点の独自方式です。この長崎県標準方式を詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>長崎県標準方式とは</h2><p>諫早市は長崎市と同様に「父母各100点・合計200点」の方式を採用しています。一般的な40点制と比べてスケールが大きく、点数差がわかりやすいのが特徴です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数（各100点満点）</h2><ul><li>月160時間以上：100点</li><li>月120〜160時間未満：80点</li><li>月80〜120時間未満：60点</li><li>月64〜80時間未満：40点</li><li>就労予定（内定あり）：30点</li></ul><h2>フルタイム共働きの合計</h2><p>父・母ともに月160時間以上就労の場合、基本指数の合計は200点となります。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "isahaya",
    title: "諫早市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "諫早市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。諫早市は長崎県中央部に位置し、人口約13万3千人。長崎・佐世保の中間に位置する交通の要衝で、共働き世帯が多い地域です。</p><h2>諫早市の保育施設の種類</h2><ul><li>認可保育所：諫早市が認可した施設。保育料は世帯年収に応じて決定。選考は200点制方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>事業所内保育事業：企業が従業員向けに設置した施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "adjustment-index",
    citySlug: "isahaya",
    title: "諫早市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "諫早市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>諫早市では基本指数（最大200点）に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+20点</td></tr><tr><td>きょうだいが認可施設に在園中</td><td>+10点</td></tr><tr><td>小規模保育事業所等を卒園</td><td>+10点</td></tr><tr><td>認可外保育施設を月ぎめで利用中</td><td>+5点</td></tr><tr><td>生活保護受給世帯</td><td>+5点</td></tr><tr><td>育児休業から復帰予定</td><td>+5点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-2点</td></tr></table><div class="point-box"><p>200点制のため、調整指数の点数も他県と比べて大きいように見えますが、基本指数との比率は同程度です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "single-parent",
    citySlug: "isahaya",
    title: "諫早市のひとり親家庭の保活　+20点加点の活用法",
    description: "諫早市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>諫早市では、ひとり親世帯に対して+20点の調整指数加点があります。200点制なので比率としては10%の加算です。フルタイム就労100点＋ひとり親20点で120点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li><li>配偶者が長期不在の場合も対象になるケースがあります</li></ul><h2>さらなる加点の活用</h2><p>ひとり親加点（+20点）に加えて、きょうだい在園（+10点）・認可外利用（+5点）なども活用できます。</p>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "isahaya",
    title: "諫早市の保活でよくある失敗と対策5選",
    description: "諫早市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：200点制の仕組みを誤解する</h2><p>諫早市は父母各100点・合計200点の方式です。他の自治体と混同しないよう注意しましょう。</p><h2>失敗2：情報収集のスタートが遅い</h2><p>諫早市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗3：小規模保育卒園加点を知らない</h2><p>0〜2歳児の小規模保育事業所等を卒園した場合、+10点の加点があります。小規模保育所卒園見込みの場合は必ず確認しましょう。</p><h2>失敗4：希望施設を少なく書く</h2><p>諫早市でも希望施設を複数記入できます。入園の可能性を高めるためなるべく多く書きましょう。</p><h2>失敗5：加点の取りこぼし</h2><p>ひとり親で+20点、きょうだい在園で+10点、育休復帰で+5点など。使える加点を漏れなくチェックしましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
  {
    slug: "working-mothers",
    citySlug: "isahaya",
    title: "諫早市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "諫早市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数（各100点満点）</h2><p>諫早市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>100点</td></tr><tr><td>月120〜160時間未満</td><td>80点</td></tr><tr><td>月80〜120時間未満</td><td>60点</td></tr><tr><td>月64〜80時間未満</td><td>40点</td></tr><tr><td>就労予定（内定あり）</td><td>30点</td></tr></table><h2>夫婦ともにフルタイムの場合</h2><p>両親各100点で合計200点。諫早市で最高の基本指数となります。</p>`,
    publishedAt: "2026-05-11",
    popularity: 48,
  },
  {
    slug: "sibling-bonus",
    citySlug: "isahaya",
    title: "諫早市のきょうだい加点　在園中は+10点の高加点を活用",
    description: "諫早市できょうだいが認可保育施設に在園中の場合の加点（+10点）について解説します。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>きょうだい在園加点とは</h2><p>諫早市では、申込時点できょうだいが認可保育施設に在園中の場合、+10点の調整指数が加算されます。200点制の中でも比較的大きな加点です。</p><h2>加点の条件</h2><ul><li>申込時点できょうだいが認可保育施設（保育所・認定こども園等）に在籍中であること</li><li>同一施設でなくても対象</li></ul><h2>小規模保育卒園加点との違い</h2><p>0〜2歳児向けの小規模保育事業所等を卒園した場合も+10点の加点があります。入園を希望する子がそのような施設を卒園する場合に適用されます。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "isahaya",
    title: "諫早市の認可保育施設一覧　地区別の施設数と特徴",
    description: "諫早市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>諫早市の保育施設の概要</h2><p>諫早市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。諫早駅周辺や国道34号沿いに施設が集中しています。</p><h2>地区別の傾向</h2><ul><li>諫早駅周辺・市街地：施設数が多く利便性が高いが競争率も高め</li><li>小長井・高来地区：比較的定員に余裕のある施設が多い</li><li>多良見・森山地区：住宅地として発展しており施設も整備中</li></ul><div class="point-box"><p>第1〜第5希望まで記入できます。なるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 32,
  },
  {
    slug: "ikukyu-return",
    citySlug: "isahaya",
    title: "諫早市で育休復帰を目指すママへ　+5点加点の活用法",
    description: "諫早市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+5点）</h2><p>諫早市では、育児休業から復帰して入園する場合に+5点の調整指数が加算されます。200点制の中で+5点は比率として小さいですが、同点の場合の優先順位に影響します。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+5点）は認可外利用加点（+5点）と合算できます。合計+10点の上乗せが可能です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
];

registerArticles(articles);
