import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "ishigaki",
    title: "石垣市の保活スケジュール　令和8年度4月入園の流れ",
    description: "石垣市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>石垣市は沖縄県八重山地方の中心都市で、日本最南端・最西端の自治体として知られています。離島という特性から保育施設の選択肢は限られますが、独自の入所選考基準が設けられています。申込先は石垣市こどもみらい課です。</p><h2>一次申込</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月下旬〜11月下旬</td></tr><tr><td>結果通知</td><td>令和8年1月下旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>石垣市は離島のため、保育施設の絶対数が少ないです。第1希望だけでなく複数希望を出すことが重要です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 40,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "ishigaki",
    title: "石垣市の保活でよくある失敗と対策5選",
    description: "石垣市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：希望施設が1か所しかない</h2><p>石垣市は施設数が少ないため、複数の希望施設を出しておくことが重要です。第1希望に入れなかった場合の選択肢を用意しましょう。</p><h2>失敗2：就労時間の計算間違い</h2><p>石垣市では月160時間以上で20点です。月160時間未満では1時間単位で細かく点数が変わります。就労証明書で正確に申告しましょう。</p><h2>失敗3：DV・虐待の加点を知らない</h2><p>石垣市はDV・虐待被害者への加点が+40点と非常に高いです。支援機関を通じた申告が可能です。</p><h2>失敗4：ひとり親の大幅加点を確認しない</h2><p>ひとり親世帯への加点が+23点あります。書類の準備を忘れずに。</p><h2>失敗5：単身赴任の加点を見落とす</h2><p>一方の保護者が単身赴任の場合、+10点の加点があります。該当する場合は忘れずに申告しましょう。</p>`,
    publishedAt: "2026-05-08",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "ishigaki",
    title: "石垣市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "石垣市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。石垣市は沖縄県の八重山地方に位置する人口約5万人の離島都市です。</p><h2>石垣市の保育園の種類</h2><ul><li>認可保育園：石垣市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可基準を満たさないが届出済みの施設。</li></ul><p>離島という特性から施設数は限られています。早めに情報収集することが重要です。</p>`,
    publishedAt: "2026-05-08",
    popularity: 32,
  },
  {
    slug: "point-system",
    citySlug: "ishigaki",
    title: "石垣市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "石垣市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>石垣市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間と点数の関係</h3><ul><li>月160時間以上（週40時間以上）：20点</li><li>月140時間以上（週35時間以上）：19点</li><li>月120時間以上（週30時間以上）：18点</li><li>月100時間以上（週25時間以上）：17点</li><li>月80時間以上（週20時間以上）：16点</li><li>月64時間以上（週16時間以上）：15点</li><li>月64時間未満：10点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 47,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "ishigaki",
    title: "石垣市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "石垣市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。石垣市はDV・虐待被害への+40点が特徴的です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+23点</li><li>生活保護受給：+5点</li><li>DV・虐待の被害：+40点</li><li>申込児童に障がいがある：+16点</li><li>3人以上の扶養児童がいる多子世帯：+8点</li><li>単身赴任（一方の保護者が赴任中）：+10点</li><li>保育士として市内施設に就労：+7点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 49,
  },
  {
    slug: "selection-process",
    citySlug: "ishigaki",
    title: "石垣市の保育園選考フロー　書類提出から入園決定まで",
    description: "石垣市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10月下旬〜11月下旬に、石垣市こどもみらい課へ提出します。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>石垣市が申込書類に基づいて指数を計算します。就労時間と各種調整指数の確認が重要です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望施設との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>1月下旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 43,
  },
  {
    slug: "score-up-checklist",
    citySlug: "ishigaki",
    title: "石垣市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "石垣市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>DV・虐待の被害→+40点（最大の加点）</li><li>ひとり親世帯→+23点</li><li>申込児童に障がいがある→+16点</li><li>多子世帯（3人以上の子を扶養）→+8点</li><li>単身赴任→+10点</li><li>保育士就労（市内施設）→+7点</li><li>生活保護受給→+5点</li></ul><div class="point-box"><p>石垣市はDV・虐待被害への加点が+40点と県内でも高水準です。安全な環境で申告できます。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 46,
  },
  {
    slug: "area-guide",
    citySlug: "ishigaki",
    title: "石垣市の保育園マップ　エリアごとの入りやすさを比較",
    description: "石垣市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>石垣市の保育園事情</h2><p>石垣市は沖縄県の八重山諸島に位置する離島都市です。観光業が盛んで、人口約5万人の島の都市として独自の保育文化があります。認可保育園は約15か所あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>石垣市中心部（石垣港周辺）：交通利便性が高く働く世代が集中</li><li>新川・登野城地区：住宅密集地で保育ニーズが高い</li></ul><h3>比較的入りやすいエリア</h3><ul><li>南部・空港周辺：一部の施設では比較的空きがある場合も</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 34,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "ishigaki",
    title: "石垣市の認可外保育施設ガイド　認可園との違いは？",
    description: "石垣市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。石垣市でも複数の認可外施設があります。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>選考</td><td>指数方式</td><td>施設独自</td></tr></table><div class="point-box"><p>沖縄県の認可外保育施設補助制度を活用することで費用負担が軽減される場合があります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 31,
  },
  {
    slug: "nursery-fees",
    citySlug: "ishigaki",
    title: "石垣市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "石垣市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。石垣市もこの制度に対応しています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～5,000円</td></tr><tr><td>300～500万円</td><td>7,000～18,000円</td></tr><tr><td>500～700万円</td><td>20,000～35,000円</td></tr><tr><td>700万円以上</td><td>35,000円〜</td></tr></table><div class="point-box"><p>石垣市は観光・サービス業が主産業で、平均所得は全国平均より低め。低所得世帯への保育料軽減制度が充実しています。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
];

registerArticles(articles);
