import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "iwakuni",
    title: "岩国市の保活スケジュール　令和8年度4月入園の流れ",
    description: "岩国市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>岩国市は山口県東部に位置し、人口約13万4千人の都市です。岩国基地（米軍・海上自衛隊）を擁し、基地関連の従業者や関連産業の従事者が多い都市です。申込先は岩国市子育て支援部保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>岩国市の選考指数は父母各10点の合計20点が基本指数の満点です。フルタイム共働きで20点が基本ラインで、調整指数が加算されます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "iwakuni",
    title: "岩国市の保活でよくある失敗と対策5選",
    description: "岩国市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>岩国市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>岩国市は基地関連の共働き世帯が多く、人気施設の競争率は高めです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>岩国市は父母各20点の合計40点制です。月64時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+3点、きょうだい在園で+2〜4点、育休復帰で+2点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：世帯の状況を正確に報告する</h2><p>調整指数は世帯の事情に基づいて加減されます。自分の世帯がどの項目に当てはまるかを正確に申告することが重要です。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "iwakuni",
    title: "岩国市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "岩国市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。岩国市は山口県東部に位置し、人口約13万4千人。岩国基地を擁する都市で、基地関連の従業者も多く住んでいます。</p><h2>岩国市の保育施設の種類</h2><ul><li>認可保育所：岩国市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "iwakuni",
    title: "岩国市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "岩国市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>岩国市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数（一親あたり）</h2><ul><li>月140時間以上：10点</li><li>月120時間以上140時間未満：9点</li><li>月100時間以上120時間未満：8点</li><li>月80時間以上100時間未満：7点</li><li>月64時間以上80時間未満：6点</li><li>派遣先未定（派遣開始者）：3点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "iwakuni",
    title: "岩国市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "岩国市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>岩国市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+3点</td></tr><tr><td>きょうだいが市内認可保育所に在園（同施設）</td><td>+2点</td></tr><tr><td>きょうだいが別の認可外施設に在園</td><td>+4点</td></tr><tr><td>生活保護受給世帯</td><td>+2点</td></tr><tr><td>育児休業から復帰予定</td><td>+2点</td></tr><tr><td>申込児童のきょうだいが2人以上（小学校・学童含む）</td><td>+1点</td></tr><tr><td>両親の就労状況が安定している</td><td>+1点</td></tr><tr><td>新生児を迎える予定</td><td>+1点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>保育料を滞納している</td><td>-5点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "iwakuni",
    title: "岩国市のひとり親家庭の保活　+3点加点の活用法",
    description: "岩国市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>岩国市では、ひとり親世帯に対して+3点の調整指数加点があります。フルタイム就労20点＋ひとり親3点で23点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+3点）に加えて、育児休業からの復帰予定（+2点）などの他の調整指数も活用できます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "iwakuni",
    title: "岩国市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "岩国市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数（一親あたり）</h2><p>岩国市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月140時間以上</td><td>10点</td></tr><tr><td>月120時間以上140時間未満</td><td>9点</td></tr><tr><td>月100時間以上120時間未満</td><td>8点</td></tr><tr><td>月80時間以上100時間未満</td><td>7点</td></tr><tr><td>月64時間以上80時間未満</td><td>6点</td></tr></table><h2>基地関連勤務の場合</h2><p>岩国市は米軍・海上自衛隊の岩国基地があり、基地関連で働く方も多くいます。雇用形態によらず、実際の月間就労時間で指数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "iwakuni",
    title: "岩国市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "岩国市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+2点）</h2><p>岩国市では、育児休業から復帰して入園する場合に+2点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+2点）は、他の調整指数と組み合わせることができる場合があります。市役所の保育課に個別に確認しましょう。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "iwakuni",
    title: "岩国市の認可保育施設一覧　地区別の施設数と特徴",
    description: "岩国市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>岩国市の保育施設の概要</h2><p>岩国市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。岩国駅周辺や市内各地に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>岩国駅周辺・由宇地区：施設数が多く利便性が高い</li><li>玖珂・周東地区：比較的定員に余裕のある施設が多い</li><li>錦・美川地区：農村部で施設数は少ない</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "iwakuni",
    title: "岩国市の祖父母同居と保活　注意点と相談方法",
    description: "岩国市で祖父母と同居している場合の保活について、市役所への相談方法をご案内します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母との同居と調整指数</h2><p>岩国市の利用調整基準では、祖父母との同居が選考に影響する場合があります。ただし、適用される条件や減点幅は、市の基準や個別の状況によって異なります。</p><h2>同居祖父母がいる場合の確認事項</h2><ul><li>祖父母の年齢と就労状況</li><li>祖父母が保育を行える環境かどうか</li><li>世帯構成と保育の必要性</li></ul><div class="point-box"><p>祖父母と同居している場合は、必ず岩国市子育て支援部保育課に事前に相談し、個別の状況に基づいた正確な指数計算を確認してください。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
];

registerArticles(articles);
