import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  { slug: "hokatsu-schedule", citySlug: "izumi", title: "和泉市の保活スケジュール　申込から内定までの流れ", description: "和泉市の認可保育園の申込時期・選考の流れをまとめました。令和8年度4月入園の動き方を解説します。", image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: "<h2>和泉市の4月入園スケジュール</h2><p>和泉市の認可保育園は毎年秋に翌年度4月入園の一次申込を受付けます。実施基準指数表を理解して準備を進めましょう。</p><h3>保活の全体スケジュール</h3><div class=\"step\"><div class=\"step-num\">1</div><div class=\"step-content\"><strong>4月〜6月：情報収集</strong><p>和泉市のホームページで保育園の一覧や前年度のボーダー（最低指数一覧）を確認します。</p></div></div><div class=\"step\"><div class=\"step-num\">2</div><div class=\"step-content\"><strong>7月〜9月：保育園見学</strong><p>和泉市内の保育園を見学して、通勤経路との相性を確認しましょう。</p></div></div><div class=\"step\"><div class=\"step-num\">3</div><div class=\"step-content\"><strong>9月〜10月：書類準備</strong><p>就労証明書の月あたり就労時間は正確に記載してもらいましょう。指数に直結します。</p></div></div><div class=\"step\"><div class=\"step-num\">4</div><div class=\"step-content\"><strong>11月：申込書類の提出</strong><p>4月一次の申込期限は例年11月中旬です。期限厳守で提出しましょう。</p></div></div><div class=\"point-box\"><p><strong>ポイント</strong></p><p>和泉市の基準指数は父母各最大20点（合計40点満点）です。月の就労時間で判定される制度です。</p></div>", publishedAt: "2026-04-12", popularity: 55 },
  { slug: "hokatsu-mistakes", citySlug: "izumi", title: "和泉市の保活でよくある失敗と対策", description: "和泉市で保活を成功させるために、よくある失敗事例と対策をまとめました。", image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: "<h2>和泉市の保活で失敗しないために</h2><p>保活はタイミングと準備が重要です。よくある失敗を事前に知っておくことで、防げます。</p><div class=\"warn-box\"><p><strong>注意</strong></p><p>虚偽の申告は入園取消しの対象です。正確な情報を提供しましょう。</p></div>", publishedAt: "2026-04-12", popularity: 48 },
  { slug: "scoring-system-guide", citySlug: "izumi", title: "和泉市の入園点数のしくみ　基準指数と調整指数を解説", description: "和泉市の保育園入園選考で使われる基準指数と調整指数のしくみをわかりやすく解説します。", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: "<h2>和泉市の選考指数とは</h2><p>和泉市の認可保育園は「基準指数（父＋母）＋調整指数」の合計で選考されます。</p><h3>基準指数（父母各最大20点、合計40点）</h3><p>就労の場合、月160時間以上の就労で満点の<span class=\"highlight\">20点</span>です。</p>", publishedAt: "2026-04-12", popularity: 60 },
  { slug: "working-hours-points", citySlug: "izumi", title: "和泉市の就労時間と点数の関係を解説", description: "和泉市で就労時間がどう点数に反映されるか、時間帯による違いをまとめました。", image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: "<h2>就労時間と点数の大切な関係</h2><p>和泉市では月あたりの就労時間が直接、点数に反映されます。8時間の違いが重要です。</p><div class=\"point-box\"><p><strong>重要</strong></p><p>就労時間には通勤時間は含まれません。実際の業務時間で計算してください。</p></div>", publishedAt: "2026-04-12", popularity: 52 },
  { slug: "adjustment-points-guide", citySlug: "izumi", title: "和泉市の調整指数　加点・減点の活用法", description: "和泉市の保育園入園で調整指数の加点と減点を最大限に活用する方法。", image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop", category: "加点・減点", categoryColor: "amber", content: "<h2>調整指数で差がつく</h2><p>フルタイム共働き世帯は基準指数40点で横並びです。差がつくのは調整指数です。</p><div class=\"point-box\"><p><strong>ポイント</strong></p><p>和泉市外から申込する場合は-10点の大幅減点があります。市内転居を検討しましょう。</p></div>", publishedAt: "2026-04-12", popularity: 57 },
  { slug: "single-parent-guide", citySlug: "izumi", title: "和泉市のひとり親保活ガイド　加点と優遇制度", description: "和泉市でひとり親家庭が使える加点制度と選考上の優遇措置をまとめました。", image: "https://images.unsplash.com/photo-1516627145497-ae6968895b2f?w=800&h=400&fit=crop", category: "加点・減点", categoryColor: "amber", content: "<h2>ひとり親家庭の保活は有利</h2><p>和泉市ではひとり親家庭に対して調整指数+5点の加点があります。これは大きなアドバンテージです。</p>", publishedAt: "2026-04-12", popularity: 45 },
  { slug: "nursery-options", citySlug: "izumi", title: "和泉市の認可・認可外保育施設　違いと選び方", description: "和泉市での認可保育園と認可外保育施設の違い、選び方のポイントをまとめました。", image: "https://images.unsplash.com/photo-1564631521675-32f1c18b1dce?w=800&h=400&fit=crop", category: "施設の種類", categoryColor: "rose", content: "<h2>和泉市の保育施設選びのポイント</h2><p>保育施設には認可と認可外があります。それぞれの特徴を理解して選びましょう。</p>", publishedAt: "2026-04-12", popularity: 51 },
  { slug: "interview-tips", citySlug: "izumi", title: "和泉市の保育園見学で押さえるべきポイント", description: "和泉市の保育園見学で確認すべき項目と、質問の例をまとめました。", image: "https://images.unsplash.com/photo-1581092916550-e323be2ae537?w=800&h=400&fit=crop", category: "施設の種類", categoryColor: "rose", content: "<h2>保育園見学で何を見るべきか</h2><p>保育園選びは見学が重要です。事前にチェックリストを用意しましょう。</p>", publishedAt: "2026-04-12", popularity: 49 },
  { slug: "hokatsu-faq", citySlug: "izumi", title: "和泉市の保活FAQ　よくある質問と回答", description: "和泉市の保活についてよくある質問と、その回答をまとめました。", image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop", category: "Q&A", categoryColor: "purple", content: "<h2>和泉市の保活よくある質問</h2><h3>Q. 認可外を使ったら認可園の申込に不利になりますか？</h3><p>A. いいえ、むしろ有利です。認可外利用は+3点の加点がもらえます。</p>", publishedAt: "2026-04-12", popularity: 54 },
  { slug: "documents-checklist", citySlug: "izumi", title: "和泉市の申込書類チェックリスト　書き忘れを防ぐ", description: "和泉市の保育園申込に必要な書類と、準備のチェックリストです。", image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop", category: "書類・手続き", categoryColor: "teal", content: "<h2>申込に必要な書類</h2><p>和泉市への保育園申込には様々な書類が必要です。期限に遅れないよう早めに準備しましょう。</p>", publishedAt: "2026-04-12", popularity: 53 },
];

registerArticles(articles);
