import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "izumo",
    title: "出雲市の保活スケジュール　令和8年度4月入園の流れ",
    description: "出雲市の認可保育所の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>出雲市は島根県の東部に位置し、人口約17万人の県内最大の都市です。出雲大社で知られる観光都市でもあります。保育所の申込先は出雲市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>出雲市の選考指数は父母それぞれ最大50点の合計100点満点です。フルタイム共働きで両親とも月160時間以上働いていれば100点満点が基本ラインになります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "izumo",
    title: "出雲市の保活でよくある失敗と対策5選",
    description: "出雲市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>出雲市の4月入園の申込は10月から始まります。見学の予約が埋まる前に動きましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>出雲市では希望園を複数記入できます。1〜2園しか書かないと不承諾のリスクが高まります。</p><h2>失敗3：自分の点数を把握していない</h2><p>出雲市は父母各50点の合計100点制です。フルタイム共働きで合計100点が基本ラインです。就労時間が月160時間未満の場合、点数が下がります。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親は+30点、きょうだいが在園中で+30点と出雲市は調整指数の加点幅が大きいです。使える加点を漏れなく確認しましょう。</p><h2>失敗5：保育料の滞納</h2><p>出雲市では保育料の滞納があると-30点の大幅減点があります。過去の滞納がないか確認してください。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "izumo",
    title: "出雲市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "出雲市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育所への入所を目指して活動することです。出雲市は島根県の中心都市で、人口約17万人。認可保育所の数は市内に多数あります。</p><h2>出雲市の保育施設の種類</h2><ul><li>認可保育所：出雲市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可外だが届出済みの施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の8月〜9月には施設見学を始め、10月の申込受付に備えましょう。産休に入ったらすぐ動き始めるのが理想です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "point-system",
    citySlug: "izumo",
    title: "出雲市の基本指数システム　100点満点の仕組みをわかりやすく",
    description: "出雲市の保育所入所選考で最も重要な基本指数（父母各50点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>出雲市の保育所入所は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。父と母、それぞれ最大50点で合計100点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各50点ずつ、基本指数の合計は100点になります。</p><h3>就労時間別の基本指数</h3><ul><li>月160時間以上：50点</li><li>月140〜160時間未満：48点</li><li>月120〜140時間未満：46点</li><li>月112〜120時間未満：40点</li><li>月96〜112時間未満：38点</li><li>月80〜96時間未満：36点</li><li>月64〜80時間未満：34点</li><li>月48〜64時間未満：32点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 48,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "izumo",
    title: "出雲市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "出雲市の保育所入所選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。出雲市は調整指数の幅が非常に大きいことが特徴です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+30点</li><li>きょうだいが希望施設に在園中：+30点</li><li>きょうだいと同時申込み：+27点</li><li>生活保護受給：+30点</li><li>認可外保育施設に月ぎめで預けている：+10点</li></ul><h3>減算項目</h3><ul><li>保育料の滞納あり：-30点</li></ul><div class="point-box"><p>出雲市の調整指数は最大で+30点と非常に大きな影響があります。ひとり親家庭やきょうだい在園は大幅な加点になります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 45,
  },
  {
    slug: "selection-process",
    citySlug: "izumo",
    title: "出雲市の保育所選考フロー　書類提出から入所決定まで",
    description: "出雲市の保育所入所選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月に、出雲市子育て支援課へ提出します。就労証明書など必要書類を揃えましょう。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>出雲市が申込書類に基づいて指数を計算します。基本指数と調整指数の合計が選考指数になります。父母各50点が最大です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望施設との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "score-up-checklist",
    citySlug: "izumo",
    title: "出雲市で点数を上げる方法　調整指数チェックリスト",
    description: "出雲市の入所選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯で就労中→+30点（大きな加点）</li><li>きょうだいが希望施設に在園中→+30点</li><li>きょうだいと同時申込み→+27点</li><li>生活保護受給中→+30点</li><li>認可外保育施設に月ぎめで利用中→+10点</li></ul><div class="point-box"><p>出雲市は調整指数の幅が非常に大きく、ひとり親・きょうだい在園・生活保護はいずれも+30点です。基本指数が同点の場合、調整指数で大きく差がつきます。</p></div><h2>注意：保育料滞納は-30点</h2><p>保育料の滞納があると-30点の大幅な減点になります。過去に滞納がある場合は事前に解消しておきましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 52,
  },
  {
    slug: "area-guide",
    citySlug: "izumo",
    title: "出雲市の保育所マップ　エリアごとの入りやすさを比較",
    description: "出雲市内のエリアごとの保育所の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>出雲市の保育所事情</h2><p>出雲市は島根県の東部に位置する人口約17万人の都市です。市内には認可保育所が40か所以上あります。出雲駅周辺や斐川町周辺は共働き世帯が多く、競争率が高い傾向があります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>出雲駅周辺・今市地区：交通の便が良く人気が集中</li><li>斐川町・出東地区：住宅地の開発で需要が増加</li></ul><h3>比較的入りやすいエリア</h3><ul><li>大社地区・湖陵地区：市街地から離れるため、空きがある施設も</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 35,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "izumo",
    title: "出雲市の認可外保育施設ガイド　認可所との違いは？",
    description: "出雲市で認可保育所に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。出雲市内にも複数存在します。</p><h2>認可所との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の調整指数</td><td>-</td><td>+10点の加点</td></tr></table><div class="point-box"><p>出雲市では認可外保育施設に月ぎめで預けている場合、翌年度の選考で+10点の加点があります。認可外に預けながら翌年の認可所を再申請する戦略は有効です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "ikukyuu-guide",
    citySlug: "izumo",
    title: "出雲市で育休から保育所へ復帰する流れ",
    description: "出雲市で育児休業から認可保育所に入所して職場復帰するための手順を解説します。",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>育休中の保活スケジュール</h2><p>育休中の保護者が4月入園を目指す場合、育休終了時期と入園時期を合わせることが重要です。</p><h2>育休と入所の関係</h2><p>出雲市では育休からの復帰を前提とした場合でも、就労証明書（入所後に復職する旨が記載されたもの）があれば申込できます。内定取得後に復職の意思確認がある場合もあります。</p><h2>注意点</h2><ul><li>内定後に育休を延長した場合、入所が取り消されることがあります</li><li>入所月に合わせて復職日を事前に職場と調整しておきましょう</li><li>育休中は就労時間がゼロのため、復職予定として申込む形になります</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 41,
  },
];

registerArticles(articles);
