import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kashiba",
    title: "香芝市の保活スケジュール　令和8年度4月入園の流れ",
    description: "香芝市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>香芝市は奈良県中西部に位置し、人口約79,000人の都市です。大阪のベッドタウンとして発展し、近鉄大阪線・近鉄南大阪線で大阪市内まで約30分の交通利便性を備えています。二上山のふもとに広がる住宅地で、若いファミリー層が多く住んでいます。申込先は香芝市子ども・子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>香芝市の選考指数は父母各20点の合計40点満点です。大阪への通勤者が多い地域のため、フルタイム共働きで40点が基本ラインとなります。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kashiba",
    title: "香芝市の保活でよくある失敗と対策5選",
    description: "香芝市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>香芝市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>香芝市は若いファミリー層が多く移入している地域です。人気施設の競争率は高いため、希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>香芝市は父母各20点の合計40点制です。大阪通勤のため月160時間以上（フルタイム）の就労が多い地域。自分の点数をきちんと計算しておきましょう。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、きょうだい在園で+3点、認可外利用で+3点、育休復帰で+2点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>香芝市では65歳未満の同居祖父母が保育できる状態の場合に-3点となります。同居祖父母の就労状況を確認しておきましょう。</p>`,
    publishedAt: "2026-05-28",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kashiba",
    title: "香芝市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "香芝市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。香芝市は奈良県中西部に位置し、人口約79,000人。大阪のベッドタウンとして発展した住宅地で、近鉄線での通勤利便性が高い地域です。</p><h2>香芝市の保育施設の種類</h2><ul><li>認可保育所：香芝市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-28",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "kashiba",
    title: "香芝市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "香芝市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>香芝市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li></ul><p>香芝市は大阪通勤圏のため、フルタイム就労（月160時間以上）でのご家族が多い地域です。</p>`,
    publishedAt: "2026-05-28",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "kashiba",
    title: "香芝市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "香芝市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>香芝市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+5点</td></tr><tr><td>きょうだいが在園中</td><td>+3点</td></tr><tr><td>きょうだいと同時申込み</td><td>+2点</td></tr><tr><td>認可外保育施設に月ぎめで利用中</td><td>+3点</td></tr><tr><td>育児休業から復帰予定</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+3点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-3点</td></tr></table>`,
    publishedAt: "2026-05-28",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "kashiba",
    title: "香芝市のひとり親家庭の保活　+5点加点の活用法",
    description: "香芝市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>香芝市では、ひとり親世帯に対して+5点の調整指数加点があります。フルタイム就労20点＋ひとり親5点で25点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>香芝市は若いファミリー層が多い地域です。ひとり親加点（+5点）に加えて認可外利用中（+3点）、育休復帰（+2点）なども活用できます。</p>`,
    publishedAt: "2026-05-28",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "kashiba",
    title: "香芝市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "香芝市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>香芝市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140〜160時間未満</td><td>18点</td></tr><tr><td>月120〜140時間未満</td><td>16点</td></tr><tr><td>月100〜120時間未満</td><td>14点</td></tr><tr><td>月80〜100時間未満</td><td>12点</td></tr><tr><td>月64〜80時間未満</td><td>10点</td></tr></table><h2>大阪通勤特性</h2><p>香芝市は近鉄線を利用した大阪への通勤が便利な地域です。フルタイム就労世帯も多く、点数計算が重要になります。</p>`,
    publishedAt: "2026-05-28",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kashiba",
    title: "香芝市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "香芝市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+2点）</h2><p>香芝市では、育児休業から復帰して入園する場合に+2点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+2点）は認可外利用加点（+3点）と合算できます。合計+5点の上乗せが可能です。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 40,
  },
  {
    slug: "facilities-guide",
    citySlug: "kashiba",
    title: "香芝市の認可保育施設一覧　エリア別の施設数と特徴",
    description: "香芝市の認可保育所・認定こども園・小規模保育事業の施設数と、エリア別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>香芝市の保育施設の概要</h2><p>香芝市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。近鉄大阪線沿線の駅周辺や市街地、住宅地エリアに施設が分布しています。</p><h2>エリア別の傾向</h2><ul><li>市街地エリア：施設数が多く利便性が高い</li><li>住宅地エリア：比較的定員に余裕のある施設が多い</li><li>大阪寄りエリア：通勤時間短縮を考慮した施設利用が可能</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 32,
  },
  {
    slug: "unlicensed-nursery",
    citySlug: "kashiba",
    title: "香芝市の認可外保育施設　加点活用で入園難易度を下げる方法",
    description: "香芝市で認可外保育施設を利用している場合の加点（+3点）の仕組みと、活用ポイントを解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd58?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>認可外保育施設利用加点とは</h2><p>香芝市では、認可外保育施設を月ぎめで利用している場合に+3点の調整指数加点があります。</p><h2>加点が適用される条件</h2><ul><li>認可外保育施設に月ぎめ契約で利用していること</li><li>就労と同時に利用していること</li></ul><h2>活用のポイント</h2><p>認可外利用加点（+3点）と育休復帰加点（+2点）を組み合わせることで、最大+5点の上乗せが可能です。認可保育施設への入園難易度を大幅に下げることができます。</p><div class="point-box"><p>香芝市は大阪通勤者が多いため、朝早い保育や延長保育のニーズが高い地域です。認可外施設の活用は実務的な選択となることが多いです。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 30,
  },
];

registerArticles(articles);
