import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kashiba",
    title: "香芝市の保活スケジュール　令和8年度4月入園の流れ",
    description: "香芝市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>香芝市は奈良県中西部に位置し、人口約79,000人の都市です。大阪のベッドタウンとして発展し、近鉄大阪線・近鉄南大阪線で大阪市内まで約30分の交通利便性を備えています。二上山のふもとに広がる住宅地で、若いファミリー層が多く住んでいます。申込先は香芝市子ども・子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>香芝市の選考指数は父と母それぞれ最大10点、合計20点が基本指数です。大阪への通勤者が多い地域のため、フルタイム共働きで20点が基本ラインとなります。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kashiba",
    title: "香芝市の保活でよくある失敗と対策5選",
    description: "香芝市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>香芝市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>香芝市は若いファミリー層が多く移入している地域です。人気施設の競争率は高いため、希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>香芝市は父と母それぞれ最大10点、合計20点制です。大阪通勤のため月160時間以上（フルタイム）の就労が多い地域。自分の点数をきちんと計算しておきましょう。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+3点、きょうだい在園で+2〜4点、育休復帰で+2点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：減点の見落とし</h2><p>香芝市の基準表に祖父母同居の減点はありませんが、保育料を滞納していると-5点になります。未納があれば申込前に整理しておきましょう。</p>`,
    publishedAt: "2026-05-28",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kashiba",
    title: "香芝市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "香芝市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。香芝市は奈良県中西部に位置し、人口約79,000人。大阪のベッドタウンとして発展した住宅地で、近鉄線での通勤利便性が高い地域です。</p><h2>香芝市の保育施設の種類</h2><ul><li>認可保育所：香芝市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-28",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "kashiba",
    title: "香芝市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "香芝市の保育施設入園選考で最も重要な基本指数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>香芝市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：10点</li><li>月120時間以上160時間未満：9点</li><li>月100時間以上120時間未満：8点</li><li>月80時間以上100時間未満：7点</li><li>月64時間以上80時間未満：6点</li></ul><p>香芝市は大阪通勤圏のため、フルタイム就労（月160時間以上）でのご家族が多い地域です。</p>`,
    publishedAt: "2026-05-28",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "kashiba",
    title: "香芝市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "香芝市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>香芝市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+3点</td></tr><tr><td>きょうだいが同じ施設希望で在園中</td><td>+4点</td></tr><tr><td>きょうだいが別施設で在園中</td><td>+2点</td></tr><tr><td>きょうだいが2人以上</td><td>+1点</td></tr><tr><td>育児休業から復帰予定</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+2点</td></tr></table>`,
    publishedAt: "2026-05-28",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "kashiba",
    title: "香芝市のひとり親家庭の保活　+3点加点の活用法",
    description: "香芝市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>香芝市では、ひとり親世帯に対して+3点の調整指数加点があります。フルタイム就労10点＋ひとり親3点で13点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>香芝市は若いファミリー層が多い地域です。ひとり親加点（+3点）に加えて育休復帰（+2点）、きょうだい加点などの活用も検討しましょう。</p>`,
    publishedAt: "2026-05-28",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "kashiba",
    title: "香芝市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "香芝市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>香芝市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140〜160時間未満</td><td>18点</td></tr><tr><td>月120〜140時間未満</td><td>16点</td></tr><tr><td>月100〜120時間未満</td><td>14点</td></tr><tr><td>月80〜100時間未満</td><td>12点</td></tr><tr><td>月64〜80時間未満</td><td>10点</td></tr></table><h2>大阪通勤特性</h2><p>香芝市は近鉄線を利用した大阪への通勤が便利な地域です。フルタイム就労世帯も多く、点数計算が重要になります。</p>`,
    publishedAt: "2026-05-28",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kashiba",
    title: "香芝市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "香芝市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+2点）</h2><p>香芝市では、育児休業から復帰して入園する場合に+2点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+2点）の他に、ひとり親加点（+3点）やきょうだい加点などを活用することで複数の加点を受けられます。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 40,
  },
  {
    slug: "facilities-guide",
    citySlug: "kashiba",
    title: "香芝市の認可保育施設一覧　エリア別の施設数と特徴",
    description: "香芝市の認可保育所・認定こども園・小規模保育事業の施設数と、エリア別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>香芝市の保育施設の概要</h2><p>香芝市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。近鉄大阪線沿線の駅周辺や市街地、住宅地エリアに施設が分布しています。</p><h2>エリア別の傾向</h2><ul><li>市街地エリア：施設数が多く利便性が高い</li><li>住宅地エリア：比較的定員に余裕のある施設が多い</li><li>大阪寄りエリア：通勤時間短縮を考慮した施設利用が可能</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-28",
    popularity: 32,
  },
  {
    slug: "unlicensed-nursery",
    citySlug: "kashiba",
    title: "香芝市の認可外保育施設　加点にはならないが使いどころはある",
    description: "香芝市の基準表に認可外保育施設の利用による加点はありません。それでも認可外を使う場面と、確かめておきたい点を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd58?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>認可外利用は加点にならない</h2><p>香芝市の利用調整基準表には、認可外保育施設を利用していることによる加点の項目がありません。認可外に預けながら翌年の認可園を申し込んでも、その分の点数は付きません。</p><h2>香芝市の調整指数にあるもの</h2><ul><li>きょうだいが市内の認可保育施設に在園（同じ施設希望+4点、別施設+2点）</li><li>申込児童のきょうだいが2人以上（+1点）</li><li>育児休業からの復帰予定（+2点）</li><li>市内認可保育施設の職員（+2点）</li><li>保育料の滞納（-5点）</li></ul><h2>それでも認可外を使う場面</h2><p>香芝市は大阪へ通勤する家庭が多く、早朝や延長の保育が必要になりがちです。認可園に入れるまでの間や、開所時間が合わないときの選択肢として認可外施設は現実的です。国の無償化の対象施設なら利用料の一部が補助されます。</p><h2>確かめておきたい点</h2><ul><li>奈良県への届出があり、指導監督基準を満たしているか</li><li>開所時間と延長の上限</li><li>認可園の内定が出たときの退園の手続き</li></ul>`,
    publishedAt: "2026-05-28",
    popularity: 30,
  },
];

registerArticles(articles);
