import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kawachinagano",
    title: "河内長野市の保活スケジュール　令和8年度4月入園の流れ",
    description: "河内長野市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>河内長野市は大阪府南東部に位置し、金剛・葛城山系の麓に立地する人口約9万9千人の都市です。南海電鉄高野線・近鉄長野線が通り、大阪市内へのベッドタウンとして発展しています。豊かな自然と住宅地が共存する地域です。申込先は河内長野市子ども子育て課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>河内長野市の選考指数は父母各10点の合計20点満点（加算方式20点制）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 35,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kawachinagano",
    title: "河内長野市の保活でよくある失敗と対策5選",
    description: "河内長野市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>河内長野市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>河内長野市は大阪市のベッドタウンとして子育て世帯が増加している地域です。人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>河内長野市は父母各10点の合計20点制（加算方式）です。月48時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+12点、きょうだい在園で+2点、育休復帰で+2点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：減点項目を見落とす</h2><p>河内長野市では申込児童以外に就学前児童がいる場合に-2点、最低賃金を下回る場合に-3点など、減点される項目があります。自身の状況を事前に確認しておきましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 38,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kawachinagano",
    title: "河内長野市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "河内長野市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。河内長野市は大阪府南東部に位置し、人口約9万9千人の地域です。金剛山系の山々に囲まれた自然豊かな場所にありながら、大阪市内へのベッドタウンとしても機能しています。</p><h2>河内長野市の保育施設の種類</h2><ul><li>認可保育所：河内長野市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 37,
  },
  {
    slug: "point-system",
    citySlug: "kawachinagano",
    title: "河内長野市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "河内長野市の保育施設入園選考で最も重要な基本指数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>河内長野市の保育施設入園は指数方式（加算方式20点制）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：10点</li><li>月120〜160時間未満：9点</li><li>月100〜120時間未満：8点</li><li>月80〜100時間未満：7点</li><li>月64〜80時間未満：6点</li><li>月48〜64時間未満：2点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 41,
  },
  {
    slug: "adjustment-index",
    citySlug: "kawachinagano",
    title: "河内長野市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "河内長野市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>河内長野市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目（主なもの）</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+12点</td></tr><tr><td>親が不在（片方）</td><td>+10点</td></tr><tr><td>親が不在（両親）</td><td>+20点</td></tr><tr><td>保育士・幼稚園教諭として就労</td><td>+10点</td></tr><tr><td>兄弟姉妹が利用している施設を希望</td><td>+2点</td></tr><tr><td>育休・産休から復帰</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+1点</td></tr></table><h2>減点項目（主なもの）</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>申込児童以外に就学前児童がいる</td><td>-2点</td></tr><tr><td>就労実績がない</td><td>-2点</td></tr><tr><td>収入が最低賃金×月64時間未満</td><td>-3点</td></tr><tr><td>育児休業延長の許容申出書を提出</td><td>-40点</td></tr></table><div class="point-box"><p>育児休業延長の許容申出書を提出すると-40点の大きな減点になります。入園を強く希望する場合は提出しないのが一般的です。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 43,
  },
  {
    slug: "single-parent",
    citySlug: "kawachinagano",
    title: "河内長野市のひとり親家庭の保活　+12点加点の活用法",
    description: "河内長野市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>河内長野市では、ひとり親世帯に対して+12点の調整指数加点があります。フルタイム就労10点＋ひとり親12点で22点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><h2>その他の加点項目</h2><p>ひとり親加点に加えて、育休復帰（+2点）などの調整指数項目を活用できます。複数の加点が該当する場合は合算されます。</p>`,
    publishedAt: "2026-05-15",
    popularity: 33,
  },
  {
    slug: "working-mothers",
    citySlug: "kawachinagano",
    title: "河内長野市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "河内長野市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>河内長野市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月120〜160時間未満</td><td>9点</td></tr><tr><td>月100〜120時間未満</td><td>8点</td></tr><tr><td>月80〜100時間未満</td><td>7点</td></tr><tr><td>月64〜80時間未満</td><td>6点</td></tr><tr><td>月48〜64時間未満</td><td>2点</td></tr></table><h2>ベッドタウン特性</h2><p>河内長野市は大阪方面への通勤者が多い地域です。フルタイム就労世帯が多く、点数計算が重要になります。</p>`,
    publishedAt: "2026-05-15",
    popularity: 45,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kawachinagano",
    title: "河内長野市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "河内長野市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+2点）</h2><p>河内長野市では、育児休業から復帰して入園する場合に+2点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><h2>育休延長との関係</h2><p>認可保育施設への入園が叶わない場合、育休延長が可能なケースがあります。ただし、育児休業延長の許容に関する申出書を提出すると-40点の大きな減点になるため、入園を強く希望する場合は提出しないのが一般的です。</p><div class="point-box"><p>育休復帰を目指す場合は、事前に市役所に相談し、制度の詳細を確認することをお勧めします。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 39,
  },
  {
    slug: "nursery-facilities",
    citySlug: "kawachinagano",
    title: "河内長野市の認可保育施設一覧　地区別の施設数と特徴",
    description: "河内長野市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>河内長野市の保育施設の概要</h2><p>河内長野市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。河内長野駅周辺や中心市街地、山辺地区に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>河内長野駅周辺・市街地：施設数が多く利便性が高い</li><li>加賀田・三日市町地区：比較的定員に余裕のある施設が多い</li><li>周辺農村地区：施設数が限定的だが、通勤路線で補完</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 31,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "kawachinagano",
    title: "河内長野市での祖父母同居と保活　同居家族がいるときの点数",
    description: "河内長野市で祖父母と同居する場合の保活における点数の影響と、その他の減点項目について解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>河内長野市では祖父母同居による減点はありません</h2><p>河内長野市の利用調整基準には、祖父母と同居していることを理由とした減点の項目がありません。祖父母の有無や就労状況が選考に直接影響することはありません。</p><h2>河内長野市の減点項目</h2><p>河内長野市では以下のような場合に減点となります。</p><ul><li>申込児童以外に就学前児童がいる場合：-2点</li><li>就労実績（外勤・自営）がない場合：-2点</li><li>収入金額が最低賃金×月64時間を下回っている場合：-3点</li><li>育児休業延長の許容に関する申出書を提出する場合：-40点</li></ul><h2>祖父母の力を活用しながら保活を進める</h2><p>祖父母が同居している場合、保育のサポート体制が整っているのは利点です。祖父母の助けを活用しながら、親自身の就労や学業に専念することで、その他の加点項目を確保することに集中しましょう。</p><div class="point-box"><p>祖父母との同居は減点にはなりませんが、家族の経済状況（最低賃金以下の場合）に関連する減点には注意が必要です。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 35,
  },
];

registerArticles(articles);
