import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kirishima",
    title: "霧島市の保活スケジュール　令和8年度4月入園の流れ",
    description: "霧島市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>霧島市は鹿児島県北部に位置し、人口約12万3千人の都市です。霧島連山を擁する自然豊かな都市で、温泉地としても有名です。九州自動車道の隼人インターがあり、県内各地へのアクセスも良好です。申込先は霧島市こども政策部保育幼稚園課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>霧島市の選考点数は父母各10点の合計20点満点（鹿児島県標準方式）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kirishima",
    title: "霧島市の保活でよくある失敗と対策5選",
    description: "霧島市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>霧島市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>霧島市は温泉・観光・農業等が盛んで共働き世帯も多い地域です。人気施設の競争率は高めです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>霧島市は父母各10点の合計20点制（鹿児島県標準方式）です。月60時間未満では基本点数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+10点、きょうだい在園同施設で+3点、認可外利用で+2点、生活保護で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>霧島市では65歳未満の同居祖父母が保育できる状態の場合に-1点となります。同居祖父母の就労状況を確認しておきましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kirishima",
    title: "霧島市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "霧島市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。霧島市は鹿児島県北部に位置し、人口約12万3千人。霧島連山と温泉で知られる自然豊かな都市です。</p><h2>霧島市の保育施設の種類</h2><ul><li>認可保育所：霧島市が認可した施設。保育料は世帯年収に応じて決定。選考は点数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "kirishima",
    title: "霧島市の基本点数システム　20点満点の仕組みをわかりやすく",
    description: "霧島市の保育施設入園選考で最も重要な基本点数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本点数とは</h2><p>霧島市の保育施設入園は点数方式（鹿児島県標準方式）です。基本点数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本点数の満点です。</p><div class="point-box"><p>選考点数＝基本点数（父）＋基本点数（母）＋調整点数</p></div><h2>就労時間別の基本点数</h2><ul><li>月180時間以上：10点</li><li>月150〜180時間未満：9点</li><li>月120〜150時間未満：8点</li><li>月90〜120時間未満：7点</li><li>月60〜90時間未満：6点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "kirishima",
    title: "霧島市の調整点数ガイド　加点・減点の全項目まとめ",
    description: "霧島市の保育入園選考で基本点数に加算・減算される調整点数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整点数とは</h2><p>霧島市では基本点数に加えて、世帯の状況に応じた調整点数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+10点</td></tr><tr><td>きょうだいが在園中（同じ園を希望）</td><td>+3点</td></tr><tr><td>きょうだいが在園中（別の園）</td><td>+1点</td></tr><tr><td>認可外保育施設に月極で利用中</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+3点</td></tr><tr><td>育児休業から復帰予定</td><td>+1点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-1点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "kirishima",
    title: "霧島市のひとり親家庭の保活　+10点加点の活用法",
    description: "霧島市でひとり親として保活をする方向けに、ひとり親加点（+10点）の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>霧島市では、ひとり親世帯に対して+10点の調整点数が加算されます。フルタイム就労10点＋ひとり親10点で20点と満点に達することができます。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><div class="point-box"><p>霧島市のひとり親加点+10点は基本点数の最大値（10点）と同じです。ひとり親世帯はフルタイム就労と合わせて最高点（20点）が確保できます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "working-mothers",
    citySlug: "kirishima",
    title: "霧島市の働くママの保活攻略法　フルタイムvs時短の点数差",
    description: "霧島市でフルタイム・時短などさまざまな働き方をするママが、どのような点数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本点数</h2><p>霧島市では就労時間が長いほど高い点数が付与されます。鹿児島県標準方式は月180時間以上が最高点という特徴があります。</p><table><tr><th>就労時間</th><th>基本点数</th></tr><tr><td>月180時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月150〜180時間未満</td><td>9点</td></tr><tr><td>月120〜150時間未満</td><td>8点</td></tr><tr><td>月90〜120時間未満</td><td>7点</td></tr><tr><td>月60〜90時間未満</td><td>6点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kirishima",
    title: "霧島市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "霧島市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+1点）</h2><p>霧島市では、育児休業から復帰して入園する場合に+1点の調整点数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点は+1点ですが、フルタイム10点＋育休+1点の合計11点を確保できます。認可外利用加点（+2点）との合算も有効です。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "kirishima",
    title: "霧島市の認可保育施設一覧　地区別の施設数と特徴",
    description: "霧島市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>霧島市の保育施設の概要</h2><p>霧島市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。隼人・国分地区を中心に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>隼人・国分地区：市街地で施設数が多い</li><li>溝辺・横川地区：比較的定員に余裕のある施設が多い</li><li>牧園・霧島・福山地区：農村部で施設数は少ない</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "kirishima",
    title: "霧島市の祖父母同居の減点　-1点の条件と対処法",
    description: "霧島市で65歳未満の同居祖父母がいる場合の減点（-1点）について、条件と対処法を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居の減点とは</h2><p>霧島市では、65歳未満の同居祖父母が保育できる状態にある場合、-1点の調整点数が適用されます。</p><h2>減点が適用される条件</h2><ul><li>65歳未満の祖父母が同居している</li><li>その祖父母が保育可能な状態（無職・就労時間が少ない等）</li></ul><h2>減点が適用されない条件</h2><ul><li>同居祖父母が65歳以上の場合</li><li>同居祖父母がフルタイムで就労している場合</li><li>同居祖父母が疾病・障害等で保育不可能な場合</li></ul><div class="point-box"><p>霧島市の祖父母減点は-1点と比較的少ないですが、満点（20点）を目指す場合は確認が必要です。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
];

registerArticles(articles);
