import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kirishima",
    title: "霧島市の保活スケジュール　令和8年度4月入園の流れ",
    description: "霧島市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>霧島市は鹿児島県北部に位置し、人口約12万3千人の都市です。霧島連山を擁する自然豊かな都市で、温泉地としても有名です。九州自動車道の隼人インターがあり、県内各地へのアクセスも良好です。申込先は霧島市こども政策部保育幼稚園課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>霧島市の選考点数は父母各20点の合計40点満点です。フルタイム共働きで基本点数40点が上限です。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kirishima",
    title: "霧島市の保活でよくある失敗と対策5選",
    description: "霧島市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>霧島市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>霧島市は温泉・観光・農業等が盛んで共働き世帯も多い地域です。人気施設の競争率は高めです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>霧島市は父母各20点の合計40点制です。月60時間未満では基本点数が大きく下がります。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+25点、きょうだい在園同施設で+15点、生活保護で+10点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：基本点数を確認しない</h2><p>霧島市では就労の際、月60時間未満では基本点数が付きません。特に就学中の場合、基本点数20点が条件になります。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kirishima",
    title: "霧島市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "霧島市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。霧島市は鹿児島県北部に位置し、人口約12万3千人。霧島連山と温泉で知られる自然豊かな都市です。</p><h2>霧島市の保育施設の種類</h2><ul><li>認可保育所：霧島市が認可した施設。保育料は世帯年収に応じて決定。選考は点数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "kirishima",
    title: "霧島市の基本点数システム　20点満点の仕組みをわかりやすく",
    description: "霧島市の保育施設入園選考で最も重要な基本点数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本点数とは</h2><p>霧島市の保育施設入園は点数方式です。基本点数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本点数の満点です。</p><div class="point-box"><p>選考点数＝基本点数（父）＋基本点数（母）＋調整点数</p></div><h2>就労時間別の基本点数</h2><ul><li>月22日以上または月120時間以上：20点</li><li>月18日以上22日未満または月100時間以上120時間未満：18点程度</li><li>月16日以上18日未満または月80時間以上100時間未満：16点程度</li><li>月14日以上16日未満または月60時間以上80時間未満：14点程度</li><li>月12日以上14日未満または月48時間以上60時間未満：12点程度</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "kirishima",
    title: "霧島市の調整点数ガイド　加点・減点の全項目まとめ",
    description: "霧島市の保育入園選考で基本点数に加算・減算される調整点数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整点数とは</h2><p>霧島市では基本点数に加えて、世帯の状況に応じた調整点数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+25点</td></tr><tr><td>きょうだいが在園中（同じ園を希望）</td><td>+15点</td></tr><tr><td>きょうだいが在園中（別の園）</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+10点</td></tr><tr><td>育児休業から復帰予定</td><td>+5点</td></tr><tr><td>DV支援措置対象者</td><td>+20点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "kirishima",
    title: "霧島市のひとり親家庭の保活　+25点加点の活用法",
    description: "霧島市でひとり親として保活をする方向けに、ひとり親加点（+25点）の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>霧島市では、ひとり親世帯に対して+25点の調整点数が加算されます。フルタイム就労20点＋ひとり親25点で45点と大きな加点が得られます。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><div class="point-box"><p>霧島市のひとり親加点+25点は基本点数の最大値（20点）を上回る大きな加点です。ひとり親世帯はフルタイム就労と合わせて高い総合点を確保できます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "working-mothers",
    citySlug: "kirishima",
    title: "霧島市の働くママの保活攻略法　フルタイムvs時短の点数差",
    description: "霧島市でフルタイム・時短などさまざまな働き方をするママが、どのような点数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本点数</h2><p>霧島市では就労時間が長いほど高い点数が付与されます。霧島市は月180時間以上が最高点という特徴があります。</p><table><tr><th>就労時間</th><th>基本点数</th></tr><tr><td>月180時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月150〜180時間未満</td><td>9点</td></tr><tr><td>月120〜150時間未満</td><td>8点</td></tr><tr><td>月90〜120時間未満</td><td>7点</td></tr><tr><td>月60〜90時間未満</td><td>6点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kirishima",
    title: "霧島市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "霧島市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+5点）</h2><p>霧島市では、育児休業から復帰して入園する場合に+5点の調整点数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点は+5点です。フルタイム20点＋育休+5点の合計25点を確保できます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "kirishima",
    title: "霧島市の認可保育施設一覧　地区別の施設数と特徴",
    description: "霧島市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>霧島市の保育施設の概要</h2><p>霧島市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。隼人・国分地区を中心に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>隼人・国分地区：市街地で施設数が多い</li><li>溝辺・横川地区：比較的定員に余裕のある施設が多い</li><li>牧園・霧島・福山地区：農村部で施設数は少ない</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "kirishima",
    title: "霧島市の調整点数　大きな加点を活かす方法",
    description: "霧島市ではひとり親加点やDV支援加点など、大きな調整点が用意されています。活用可能な加点項目を確認して、入園を有利に進めましょう。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>霧島市の調整点数の特徴</h2><p>霧島市では、祖父母同居の減点項目は基準表にありません。その代わり、ひとり親世帯やDV支援対象者向けの大きな加点が用意されています。</p><h2>大きな加点項目</h2><ul><li>ひとり親世帯：+25点（就労中・生活保護なし）～+30点（就労中・生活保護受給）</li><li>DV支援措置対象者：+20点</li><li>きょうだい在園中（同じ園希望）：+15点</li><li>生活保護受給世帯：+10点</li></ul><h2>活用のポイント</h2><p>複数の加点が重ねて加算される場合があります。例えば、ひとり親で育休復帰の場合は+25点＋復帰加点の組み合わせで大きなアドバンテージが得られます。</p><div class="point-box"><p>基本点数40点に加えて、最大で+30点以上の調整点が期待できる場合もあります。該当する加点項目がないか、保育課に相談してみましょう。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
];

registerArticles(articles);
