import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  { slug: "hokatsu-schedule", citySlug: "kiryu", title: "桐生市の保活スケジュール　令和8年度4月入園の流れ", description: "桐生市の保育園申込時期・選考の流れ・結果通知の時期をわかりやすく解説します。", image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>令和8年度4月入園のスケジュール</h2><p>桐生市の4月入園は<strong>一次</strong>と<strong>二次利用調整</strong>に分かれています。申込先は桐生市子ども課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付</td><td>令和7年11月上旬〜12月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月下旬</td></tr></table><h2>動き始める時期</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>4月〜5月：情報収集</strong><p>桐生市の認可保育園は約25か所。織物産業で知られた地域です。</p></div></div>`, publishedAt: "2026-04-29", popularity: 49 },
  { slug: "hokatsu-mistakes", citySlug: "kiryu", title: "桐生市の保活でよくある失敗と対策5選", description: "初めてのママがやりがちな失敗パターンと対策をまとめました。", image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>失敗1：スタートが遅い</h2><p>11月からの申込に向けて、遅くとも6月には情報収集を始めましょう。</p><h2>失敗2：希望園が少ない</h2><p>複数園を希望に入れることで不承諾のリスクを減らせます。</p><h2>失敗3：点数を把握していない</h2><p>基本指数40点がフルタイム共働きの標準ラインです。</p>`, publishedAt: "2026-04-29", popularity: 46 },
  { slug: "scoring-system-guide", citySlug: "kiryu", title: "桐生市の入園点数のしくみ　基本指数と調整指数を解説", description: "点数の仕組みを初めての方にもわかるように解説します。", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: `<h2>点数ってなに？</h2><p>桐生市の入園は「先着順」ではなく「点数」で選考されます。</p><p>選考指数 ＝ 基本指数（父）＋ 基本指数（母）＋ 調整指数</p><h2>基本指数</h2><p>父母それぞれ最大20点。合計最大40点が基本ラインです。</p><h2>調整指数の加点・減点</h2><ul><li>ひとり親：+5点</li><li>きょうだい在園中：+5点</li><li>認可外利用：+3点</li><li>生活保護：+4点</li></ul>`, publishedAt: "2026-04-29", popularity: 55 },
  { slug: "score-up-checklist", citySlug: "kiryu", title: "桐生市で点数を上げる方法　加点チェックリスト", description: "調整指数の加点を最大限に活用する方法を解説します。", image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop", category: "点数アップ", categoryColor: "amber", content: `<h2>加点チェックリスト</h2><ul><li>ひとり親で就労中 → +5点</li><li>きょうだい在園中 → +5点</li><li>認可外利用 → +3点</li><li>生活保護 → +4点</li><li>きょうだい同時申込 → +2点</li><li>育休明け復職 → +2点</li></ul><p>認可外に預けながら翌年申請すると加点がつく有効な戦略です。</p>`, publishedAt: "2026-04-29", popularity: 51 },
  { slug: "area-guide", citySlug: "kiryu", title: "桐生市の保育園マップ　エリアごとの入りやすさ", description: "桐生市内のエリアごとの競争率や特徴をまとめました。", image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop", category: "エリア情報", categoryColor: "purple", content: `<h2>桐生市の保育園事情</h2><p>人口約10万人の市。JR両毛線の桐生駅周辺がメインエリアです。認可保育園は約25か所。</p><h3>競争率が高いエリア</h3><ul><li><strong>桐生駅周辺</strong>：駅近の園は人気集中</li><li><strong>中心市街地</strong>：ファミリー層が増加</li></ul><h3>入りやすいエリア</h3><ul><li><strong>郊外</strong>：駅から離れるため比較的空きあり</li></ul>`, publishedAt: "2026-04-29", popularity: 42 },
  { slug: "ninkagai-guide", citySlug: "kiryu", title: "桐生市の認可外保育施設ガイド　認可園との違い", description: "認可園に入れなかった場合の選択肢について解説します。", image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop", category: "認可外保育", categoryColor: "teal", content: `<h2>認可外保育施設とは？</h2><p>自治体に届出をして運営している保育施設です。桐生市内にも複数あります。</p><h3>認可園との違い</h3><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得応じて決定</td><td>施設が設定</td></tr><tr><td>入園選考</td><td>指数による調整</td><td>施設独自基準</td></tr><tr><td>翌年加点</td><td>-</td><td>+3点</td></tr></table>`, publishedAt: "2026-04-29", popularity: 39 },
  { slug: "tiebreaker-guide", citySlug: "kiryu", title: "桐生市で同点になったら　優先順位のしくみ", description: "同点になった場合の優先順位と対策を解説します。", image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: `<h2>同点の優先順位</h2><ol><li>ひとり親世帯</li><li>きょうだい在園中の園希望</li><li>基本指数が高い</li><li>市の居住期間が長い</li><li>所得が低い</li></ol><p>加点を積み上げて同点を避けることが重要です。</p>`, publishedAt: "2026-04-29", popularity: 44 },
  { slug: "small-nursery", citySlug: "kiryu", title: "桐生市の小規模保育　メリット・デメリット", description: "小規模保育事業の特徴や卒園後の進路について解説します。", image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>小規模保育とは？</h2><p>定員6〜19人の少人数施設。対象は0〜2歳児のみ。3歳以降は転園が必要です。</p><h2>メリット</h2><ul><li>少人数でアットホーム</li><li>認可園より入りやすい</li><li>卒園時の優先枠あり</li></ul><h2>デメリット</h2><ul><li>3歳で転園必須</li><li>園庭がない場合が多い</li></ul>`, publishedAt: "2026-04-29", popularity: 37 },
  { slug: "nursery-fees", citySlug: "kiryu", title: "桐生市の保育料はいくら？　世帯年収別の目安", description: "認可保育園の保育料を世帯年収別に紹介します。", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop", category: "お金の話", categoryColor: "rose", content: `<h2>保育料の仕組み</h2><p>世帯の住民税額と子どもの年齢で決まります。</p><h2>3歳以上は無償化</h2><p>3歳児クラス以上は保育料無料（給食費は別途）です。</p><h3>世帯年収別の目安（0〜2歳）</h3><table><tr><th>年収目安</th><th>月額</th></tr><tr><td>〜300万</td><td>0〜6,000円</td></tr><tr><td>300〜500万</td><td>10,000〜25,000円</td></tr><tr><td>500万以上</td><td>25,000円〜</td></tr></table>`, publishedAt: "2026-04-29", popularity: 40 },
  { slug: "nursery-visit-guide", citySlug: "kiryu", title: "桐生市の保育園見学ガイド　チェックポイント", description: "見学で確認すべきポイントと質問リストをまとめました。", image: "https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>見学のベストシーズン</h2><p>6月〜9月が見学に最適。10月以降は申込直前で混み合います。</p><h2>チェックポイント</h2><ul><li>園児たちの雰囲気と表情</li><li>保育士の子どもへの接し方</li><li>園舎と園庭の状態</li><li>給食内容とアレルギー対応</li><li>持ち物や送迎動線</li></ul><h2>質問リスト</h2><ul><li>延長保育の時間と料金</li><li>慣らし保育の期間</li><li>発熱時のお迎えルール</li><li>行事への保護者参加</li></ul>`, publishedAt: "2026-04-29", popularity: 36 },
];

registerArticles(articles);
