import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kitakami",
    title: "北上市の保活スケジュール　令和8年度4月入園の流れ",
    description: "北上市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>北上市は岩手県中部に位置する人口約9万人の都市です。自動車産業が盛んで、製造業の従業員が多いのが特徴です。申込先は北上市子ども課です。</p><h2>一次利用調整</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月下旬〜11月中旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h2>二次利用調整</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月中旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>北上市は岩手県内でも早めのスケジュールです。一次で不承諾だった方は自動的に二次の対象になります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 40,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kitakami",
    title: "北上市の保活でよくある失敗と対策5選",
    description: "北上市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：見学スケジュールが後ろ倒しになる</h2><p>北上市は申込が10月下旬からと他の市町村より早いため、夏休み中の見学が必須です。</p><h2>失敗2：就労時間の計算間違い</h2><p>北上市では週42時間以上（月168時間以上）で20点です。週30時間未満は12点と段階的です。就労証明書で正確に申告しましょう。</p><h2>失敗3：祖父母同居をうっかり報告しない</h2><p>同居65歳未満祖父母が保育可能な場合、-20点の大幅減点があります。隠さず報告することが重要です。</p><h2>失敗4：多胎児加点を見落とす</h2><p>双子や三つ子の場合、+8点の加点があります。該当する場合は忘れずに申告しましょう。</p><h2>失敗5：きょうだい加点の条件確認不足</h2><p>第2子は+3点、第3子以降は+5点です。かつ保育士就労で+25点と組み合わせられます。</p>`,
    publishedAt: "2026-05-08",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kitakami",
    title: "北上市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "北上市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。北上市は岩手県中部に位置し、人口約9万人の製造業が盛んな都市です。</p><h2>北上市の保育園の種類</h2><ul><li>認可保育園：北上市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可基準を満たさないが届出済みの施設。</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 32,
  },
  {
    slug: "point-system",
    citySlug: "kitakami",
    title: "北上市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "北上市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>北上市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに週42時間以上の就労（月168時間以上）で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間と点数の関係</h3><ul><li>週42時間以上（月168時間以上）：20点</li><li>週30時間以上42時間未満：14～18点</li><li>週30時間未満（月120時間未満）：12点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 47,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "kitakami",
    title: "北上市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "北上市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。北上市の調整指数は減点項目も多いのが特徴です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+21点</li><li>生活保護受給：+10点</li><li>第2子：+3点</li><li>第3子以降：+5点</li><li>多胎児（双子・三つ子等）：+8点</li><li>きょうだい第1希望施設に在籍：+8点</li><li>保育士就労（北上市内認可保育施設）：+25点</li></ul><h3>主な減算項目</h3><ul><li>同居65歳未満祖父母が保育可能：-20点</li></ul><div class="point-box"><p>祖父母同居による-20点の減点が大きいのが北上市の特徴です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 49,
  },
  {
    slug: "selection-process",
    citySlug: "kitakami",
    title: "北上市の保育園選考フロー　書類提出から入園決定まで",
    description: "北上市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10月下旬〜11月中旬に、北上市子ども課へ提出します。岩手県内でも早めのスケジュールです。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>北上市が申込書類に基づいて指数を計算します。祖父母同居の確認が重要です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月中旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 43,
  },
  {
    slug: "score-up-checklist",
    citySlug: "kitakami",
    title: "北上市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "北上市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親で就労中→+21点</li><li>生活保護を受給中→+10点</li><li>第2子がいる→+3点</li><li>第3子以降がいる→+5点</li><li>双子や三つ子→+8点</li><li>きょうだいが第1希望施設に在籍→+8点</li><li>保育士資格で北上市内認可保育施設に就労→+25点</li></ul><div class="point-box"><p>保育士就労で+25点は県内でも高い加点です。保育士資格のある方は北上市内での就職を検討する価値があります。</p></div><h2>減点チェックリスト</h2><ul><li>同居祖父母が65歳未満で保育可能→-20点</li></ul><div class="point-box"><p>祖父母同居による-20点の減点が大きいため、祖父母に保育が難しい理由がある場合は記載しましょう。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 46,
  },
  {
    slug: "area-guide",
    citySlug: "kitakami",
    title: "北上市の保育園マップ　エリアごとの入りやすさを比較",
    description: "北上市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>北上市の保育園事情</h2><p>北上市は岩手県中部に位置する人口約9万人の都市です。自動車産業が盛んで、製造業の従業員が多いのが特徴です。認可保育園は約24か所あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>北上駅周辺：駅近の園は人気が集中</li><li>工業団地エリア：自動車メーカーの従業員の需要が高い</li></ul><h3>比較的入りやすいエリア</h3><ul><li>郊外・山間部エリア：人口が少ないため、比較的空きがある園も</li><li>浦生野地域：新規園の開設により空きが増加中</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 34,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "kitakami",
    title: "北上市の認可外保育施設ガイド　認可園との違いは？",
    description: "北上市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。北上市には複数の認可外施設があります。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の入園加点</td><td>-</td><td>なし</td></tr><tr><td>施設数</td><td>約24か所</td><td>複数</td></tr></table><div class="point-box"><p>北上市では認可外施設を利用しても、次年度の加点対象にはなりません。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 31,
  },
  {
    slug: "nursery-fees",
    citySlug: "kitakami",
    title: "北上市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "北上市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。北上市もこの制度に対応しています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～4,500円</td></tr><tr><td>300～500万円</td><td>7,000～18,000円</td></tr><tr><td>500～700万円</td><td>20,000～32,000円</td></tr><tr><td>700～1,000万円</td><td>32,000～45,000円</td></tr></table><div class="point-box"><p>北上市では第2子の保育料は半額、第3子以降は無料になります。多子世帯に優しい制度です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
  {
    slug: "nursery-visit-guide",
    citySlug: "kitakami",
    title: "北上市の保育園見学ガイド　チェックポイントと質問リスト",
    description: "北上市の保育園見学で確認すべきポイントと、先輩ママが聞いてよかった質問をまとめました。",
    image: "https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>見学はいつ行くのがベスト？</h2><p>5月～8月が見学のベストシーズンです。北上市は申込が10月下旬からと早いため、夏休み前に見学を終わらせることが重要です。</p><h2>見学時のチェックポイント</h2><ul><li>園児たちの表情や雰囲気</li><li>保育士の子どもへの接し方</li><li>園庭や室内の広さ・清潔さ</li><li>給食の内容（アレルギー対応）</li><li>冬の暖房対応</li></ul><h2>聞いておきたい質問リスト</h2><ul><li>延長保育は何時まで？料金は？</li><li>慣らし保育の期間はどのくらい？</li><li>冬場の雪道送迎対応</li><li>急な発熱時のお迎えルール</li><li>製造業の夜勤対応は可能か</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 38,
  },
];

registerArticles(articles);
