import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "komaki",
    title: "小牧市の保活スケジュール　令和8年度4月入園の流れ",
    description: "小牧市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>小牧市は愛知県の北部に位置し、人口約15万人の都市です。小牧・長久手の戦いの地として知られ、名古屋空港（県営名古屋空港）が市内にあります。製造業・物流業が盛んで共働き世帯が多い地域です。申込先は小牧市こども未来部幼児教育・保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>小牧市の選考指数は父母各20点の合計40点満点です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "komaki",
    title: "小牧市の保活でよくある失敗と対策5選",
    description: "小牧市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>小牧市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>小牧市では希望施設を複数記入できます。製造業従事者が多く共働き率が高いため、人気施設の競争率は高いです。</p><h2>失敗3：自分の点数を把握していない</h2><p>小牧市は父母各20点の合計40点制です。フルタイム共働きで40点が基本ラインです。月64時間未満では指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+6点、きょうだい在園で+5点、育休復帰で+4点、認可外利用で+4点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：就労内定書の提出を忘れる</h2><p>小牧市では就労予定（内定あり）で8点の指数が付きます。内定書を忘れずに提出しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "komaki",
    title: "小牧市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "小牧市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。小牧市は愛知県の北部に位置し、人口約15万人。名古屋空港を擁し、製造業・物流業が集積する工業都市で、共働き世帯が多い地域です。</p><h2>小牧市の保育施設の種類</h2><ul><li>認可保育所：小牧市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>事業所内保育事業：企業が従業員向けに設置した施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "point-system",
    citySlug: "komaki",
    title: "小牧市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "小牧市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>小牧市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間別の基本指数</h3><ul><li>月160時間以上（フルタイム）：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li><li>就労予定（内定あり）：8点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 49,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "komaki",
    title: "小牧市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "小牧市の保育施設入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。小牧市の主な調整指数は以下の通りです。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+6点</li><li>きょうだいが同じ施設に在園中：+5点</li><li>きょうだいを同時に申込み：+3点</li><li>生活保護受給：+5点</li><li>認可外保育施設に月ぎめで利用中：+4点</li><li>育児休業から復帰予定（入園月翌月1日までに復職）：+4点</li></ul><div class="point-box"><p>小牧市はひとり親+6点、生活保護+5点、育休復帰+4点など、調整指数の項目が充実しています。複数の加点条件は合算されます。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "selection-process",
    citySlug: "komaki",
    title: "小牧市の保育施設選考フロー　書類提出から入園決定まで",
    description: "小牧市の保育施設入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月に、小牧市こども未来部幼児教育・保育課へ提出します。就労証明書など必要書類を揃えましょう。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>小牧市が申込書類に基づいて指数を計算します。基本指数（父母各最大20点）と調整指数の合計が選考指数です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望施設との相性を調整します。同点の場合は別の条件で順位が決まります。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-11",
    popularity: 39,
  },
  {
    slug: "score-up-checklist",
    citySlug: "komaki",
    title: "小牧市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "小牧市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯で就労中→+6点</li><li>きょうだいが同じ施設に在園中→+5点</li><li>きょうだいを同時に申込み→+3点</li><li>生活保護受給中→+5点</li><li>認可外保育施設に月ぎめで利用中→+4点</li><li>育休から復帰予定（入園月翌月1日までに復職）→+4点</li></ul><div class="point-box"><p>小牧市では育休復帰の条件として「入園月の翌月1日までに復職」が必要です。職場との復職日の調整を早めに行いましょう。認可外利用（+4点）も不承諾後の再申請で有効です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 53,
  },
  {
    slug: "area-guide",
    citySlug: "komaki",
    title: "小牧市の保育施設マップ　エリアごとの入りやすさを比較",
    description: "小牧市内のエリアごとの保育施設の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>小牧市の保育施設事情</h2><p>小牧市は愛知県の北部に位置する人口約15万人の都市です。名古屋空港を擁し、製造業・物流業が集積する工業都市です。市内に認可保育所が25か所以上あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>小牧駅周辺・中心市街地：交通の便が良く人気が集中</li><li>小牧南・岩崎地区：住宅地開発が進む工場近隣エリア</li></ul><h3>比較的入りやすいエリア</h3><ul><li>大草・北外山地区：市の北部エリア、空きがある施設も</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 35,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "komaki",
    title: "小牧市の認可外保育施設ガイド　認可園との違いは？",
    description: "小牧市で認可保育施設に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。小牧市内にも複数存在します。</p><h2>認可施設との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の調整指数</td><td>-</td><td>+4点の加点</td></tr></table><div class="point-box"><p>小牧市では認可外保育施設に月ぎめで預けている場合、翌年度の選考で+4点の加点があります。一度不承諾になっても認可外に預けながら再申請する戦略は有効です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "ikukyuu-guide",
    citySlug: "komaki",
    title: "小牧市で育休から保育施設へ復帰する流れ",
    description: "小牧市で育児休業から認可保育施設に入園して職場復帰するための手順を解説します。",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>育休中の保活スケジュール</h2><p>育休中の保護者が4月入園を目指す場合、育休終了時期と入園時期を合わせることが重要です。</p><h2>育休復帰の加点について</h2><p>小牧市では、入園月の翌月1日までに復職する予定の場合、調整指数で+4点の加点があります。職場との復職日調整を早めに行いましょう。</p><h2>注意点</h2><ul><li>内定後に育休を延長した場合、入園が取り消されることがあります</li><li>入園後に就労実態がない場合は退園となる場合があります</li><li>製造業・物流業が多い地域のため、シフト勤務の場合は就労時間の月換算を正確に記入しましょう</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
];

registerArticles(articles);
