import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "konan",
    title: "江南市の保活スケジュール　令和8年度4月入園の流れ",
    description: "江南市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>江南市は愛知県北部に位置し、人口約9万8千人。名古屋市北西部に隣接した尾張北部の住宅都市です。名鉄犬山線・各務原線が通り、交通の利便性が高い地域です。申込先は江南市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>江南市は基本指数が高い自治体です。フルタイム共働きで世帯最大400点（1人最大200点）の指数が付きます。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 35,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "konan",
    title: "江南市の保活でよくある失敗と対策5選",
    description: "江南市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>江南市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。名古屋圏のベッドタウンとして競争が激しい地域です。</p><h2>失敗2：希望施設を少なく書く</h2><p>江南市は名古屋北西部に隣接した住宅都市で、子育て世帯が多い地域です。人気施設の競争率は高め。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>江南市は基本指数が高く、月60時間未満では基本指数が付きません。就労時間を正確に把握することが重要です。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+100点、育休・産休明けで+8点、きょうだい同時申込で+7点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>江南市では65歳未満の同居祖父母が保育できる状態の場合に-15点となります。同居祖父母の就労状況を確認しておきましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 39,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "konan",
    title: "江南市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "江南市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。江南市は愛知県北部に位置し、人口約9万8千人。名古屋市北西部に隣接した住宅都市で、若い世帯が多い地域です。</p><h2>江南市の保育施設の種類</h2><ul><li>認可保育所：江南市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 37,
  },
  {
    slug: "point-system",
    citySlug: "konan",
    title: "江南市の基本指数システム　400点満点の仕組みをわかりやすく",
    description: "江南市の保育施設入園選考で最も重要な基本指数について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>江南市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大100点（通常）～200点（虐待・DV対応）、合計400点が基本指数の最高額です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：100点</li><li>月140～160時間未満：90点</li><li>月120～140時間未満：80点</li><li>月100～120時間未満：70点</li><li>月80～100時間未満：60点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 41,
  },
  {
    slug: "adjustment-index",
    citySlug: "konan",
    title: "江南市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "江南市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>江南市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+100点</td></tr><tr><td>3人以上の入所</td><td>+9点</td></tr><tr><td>育休・産休明け</td><td>+8点</td></tr><tr><td>きょうだい同時申込み</td><td>+7点</td></tr><tr><td>きょうだい同時入所中</td><td>+7点</td></tr><tr><td>市内の年齢上限保育所の卒園に伴う転所</td><td>+19点</td></tr><tr><td>生活保護受給世帯</td><td>+6点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-15点</td></tr></table>`,
    publishedAt: "2026-05-15",
    popularity: 43,
  },
  {
    slug: "single-parent",
    citySlug: "konan",
    title: "江南市のひとり親家庭の保活　+100点加点の活用法",
    description: "江南市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>江南市では、ひとり親世帯に対して+100点の調整指数加点があります。フルタイム就労最大100点＋ひとり親100点で大幅にアップできます。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+100点）に加えて、育休・産休明け（+8点）などを活用することで、さらに指数を上げることができます。</p>`,
    publishedAt: "2026-05-15",
    popularity: 32,
  },
  {
    slug: "working-mothers",
    citySlug: "konan",
    title: "江南市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "江南市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>江南市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月120〜160時間未満</td><td>18点</td></tr><tr><td>月100〜120時間未満</td><td>16点</td></tr><tr><td>月80〜100時間未満</td><td>14点</td></tr><tr><td>月64〜80時間未満</td><td>12点</td></tr></table><h2>愛知県の特性</h2><p>江南市は名古屋圏のベッドタウンとして共働き世帯が多い地域です。フルタイム就労世帯の競争が激しいため点数計算が重要です。</p>`,
    publishedAt: "2026-05-15",
    popularity: 45,
  },
  {
    slug: "ikukyu-return",
    citySlug: "konan",
    title: "江南市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "江南市で育休から復帰するタイミングで保活をする方向けに、基本指数・調整指数と育児休業の関係を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休・産休明けの加点</h2><p>江南市では、育休・産休明けの場合に+8点の調整指数が加点されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業を取得中、または取得していた者</li><li>産前産後休業から復帰する場合</li><li>市役所に書類提出して確認されること</li></ul><div class="point-box"><p>江南市では調整指数の組み合わせが重要です。ひとり親加点（+100点）や育休・産休明け加点（+8点）を最大限活用しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 38,
  },
  {
    slug: "nursery-facilities",
    citySlug: "konan",
    title: "江南市の認可保育施設一覧　地区別の施設数と特徴",
    description: "江南市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>江南市の保育施設の概要</h2><p>江南市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。江南駅周辺や市街地に施設が集中しており、利便性が高い地域です。</p><h2>地区別の傾向</h2><ul><li>江南駅周辺・市街地：施設数が多く利便性が高い</li><li>住宅地区：比較的定員に余裕のある施設が多い</li><li>周辺エリア：名鉄線で補完可能</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 30,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "konan",
    title: "江南市の祖父母同居の減点　-15点の条件と対処法",
    description: "江南市で65歳未満の同居祖父母がいる場合の減点（-15点）について、条件と対処法を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居の減点とは</h2><p>江南市では、65歳未満の同居祖父母が保育できる状態にある場合、-15点の調整指数が適用されます。</p><h2>減点が適用される条件</h2><ul><li>65歳未満の祖父母が同居している</li><li>その祖父母が保育可能な状態（無職・就労時間が少ない等）</li></ul><h2>減点が適用されない条件</h2><ul><li>同居祖父母が65歳以上の場合</li><li>同居祖父母がフルタイムで就労している場合</li><li>同居祖父母が疾病・障害等で保育不可能な場合</li></ul><div class="point-box"><p>同居祖父母が就労している場合は就労証明書を提出することで減点を回避できる場合があります。市役所に確認しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 34,
  },
];

registerArticles(articles);
