import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "kuwana",
    title: "桑名市の保活スケジュール　令和8年度4月入園の流れ",
    description: "桑名市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>桑名市は三重県北部に位置し、人口約14万人の都市です。名古屋市や四日市市のベッドタウンとして発展しており、製造業・商業が主要産業です。七里の渡し（東海道唯一の海上ルート）の宿場町として歴史ある町でもあります。申込先は桑名市こども未来局保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>桑名市の選考指数は父母各40点の合計80点満点です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "kuwana",
    title: "桑名市の保活でよくある失敗と対策5選",
    description: "桑名市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>桑名市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>桑名市は名古屋のベッドタウンとして共働き世帯が多く、人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>桑名市は父母各40点の合計80点制です。月48時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+10点、きょうだい在園で+10点、育休復帰で+6点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>桑名市では65歳未満の同居祖父母が保育できる状態の場合に減点となります。申請書記入前に確認しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "kuwana",
    title: "桑名市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "桑名市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。桑名市は三重県北部に位置し、人口約14万人。名古屋・四日市のベッドタウンとして発展しており、共働き世帯が増加しています。</p><h2>桑名市の保育施設の種類</h2><ul><li>認可保育所：桑名市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>家庭的保育事業（保育ママ）：保育者の家庭で少人数を保育。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "kuwana",
    title: "桑名市の基本指数システム　80点満点の仕組みをわかりやすく",
    description: "桑名市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>桑名市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大40点、合計80点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月20日以上・1日9時間以上：20点</li><li>月20日以上・1日8時間以上：19点</li><li>月20日以上・1日7時間以上：18点</li><li>月20日以上・1日6時間以上：17点</li><li>月20日以上・1日5時間以上：15点</li><li>月20日以上・1日3時間以上：12点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "adjustment-index",
    citySlug: "kuwana",
    title: "桑名市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "桑名市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>桑名市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+5点</td></tr><tr><td>きょうだいが希望施設に在園中</td><td>+3点</td></tr><tr><td>きょうだいと同時申込み</td><td>+2点</td></tr><tr><td>認可外保育施設に月ぎめで利用中</td><td>+3点</td></tr><tr><td>育児休業から復帰予定</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+3点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-3点</td></tr></table>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "kuwana",
    title: "桑名市のひとり親家庭の保活　+10点加点の活用法",
    description: "桑名市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>桑名市では、ひとり親世帯に対して+10点の調整指数加点があります。これは基本指数に加算されるため、選考において大きなアドバンテージとなります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li><li>配偶者が長期不在（海外赴任・施設入所等）の場合も対象となることがあります</li></ul><h2>フルタイム就労の場合の目安指数</h2><p>基本指数40点（片親分のみ）＋ひとり親加点10点＝50点が基本ラインです。きょうだいが同施設に既に在園中の場合はさらに+10点が加わります。</p>`,
    publishedAt: "2026-05-11",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "kuwana",
    title: "桑名市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "桑名市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>桑名市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月120〜160時間未満</td><td>18点</td></tr><tr><td>月100〜120時間未満</td><td>16点</td></tr><tr><td>月80〜100時間未満</td><td>14点</td></tr><tr><td>月64〜80時間未満</td><td>12点</td></tr><tr><td>月48〜64時間未満</td><td>8点</td></tr></table><h2>時短勤務の注意点</h2><p>育休復帰後に時短勤務を選択する場合、月120時間以上を確保できれば18点となります。週5日・7時間勤務で月約140〜160時間が目安です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 48,
  },
  {
    slug: "ikukyu-return",
    citySlug: "kuwana",
    title: "桑名市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "桑名市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点</h2><p>桑名市では、育児休業から復帰して入園する場合に調整指数が加算されます。復帰時期によって加点が異なります。</p><h2>加点の種類</h2><ul><li>育児休業終了に伴い、就労により申し込む場合：+6点</li><li>育児休業中に新規申込をする場合（復帰予定あり）：+14点</li></ul><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>きょうだいが同時申込みで+5点、既に同施設に在園中で+10点などの加点と合算できます。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "kuwana",
    title: "桑名市の認可保育施設一覧　地区別の施設数と特徴",
    description: "桑名市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>桑名市の保育施設の概要</h2><p>桑名市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。桑名駅周辺や国道1号・23号沿いに施設が集中しています。</p><h2>地区別の傾向</h2><ul><li>桑名駅周辺：施設数が多く利便性が高いが競争率も高め</li><li>長島・多度地区：比較的定員に余裕のある施設が多い</li><li>大山田・城南地区：住宅地として発展中で需要が増加中</li></ul><div class="point-box"><p>第1〜第5希望まで記入できます。なるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 32,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "kuwana",
    title: "桑名市では祖父母同居に関する減点がない　基本指数で評価される項目",
    description: "桑名市の利用調整基準では祖父母同居に関する特別な減点がありません。代わりに評価される項目を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>桑名市では祖父母同居による減点がない</h2><p>桑名市の保育施設利用調整基準には、<span class="highlight">祖父母同居に関する特別な減点がありません</span>。他の自治体では「65歳未満の祖父母が同居していると-3点」といった減点を設ける場合がありますが、桑名市では該当する項目がありません。</p><h2>代わりに評価される項目</h2><p>桑名市では、基本指数で以下の項目が評価されます。</p><ul><li>保護者の就労状況（就労日数・時間）</li><li>出産・疾病・障害などの保育が必要な理由</li><li>保護者の健康状態</li></ul><h2>調整指数の加点・減点</h2><ul><li>ひとり親世帯：+10点</li><li>きょうだいが既に同施設に在園中：+10点</li><li>きょうだい同時申込：+5点</li><li>育児休業からの復帰予定：+6点～+14点</li><li>生活保護世帯：+2点</li><li>保育士・保育教諭：+5点</li></ul><div class="point-box"><p>祖父母が同居していることを理由とした減点はありませんが、祖父母の就労状況がある場合は、保護者本人の基本指数に含まれる場合があります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 37,
  },
];

registerArticles(articles);
