import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "matsusaka",
    title: "松阪市の保活スケジュール　令和8年度4月入園の流れ",
    description: "松阪市の認可保育所の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>松阪市は三重県の中南部に位置し、人口約16万人の都市です。松阪牛で全国的に知られ、商業・農業が盛んな地域です。申込先は松阪市こども局こども未来課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>松阪市の選考指数は父母各20点の合計40点満点です。フルタイム共働きで40点が基本ラインになります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 35,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "matsusaka",
    title: "松阪市の保活でよくある失敗と対策5選",
    description: "松阪市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>松阪市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>松阪市では希望園を複数記入できます。1〜2園しか書かないと不承諾のリスクが高まります。</p><h2>失敗3：同居祖父母の影響を把握していない</h2><p>松阪市では65歳未満の祖父母が同居し保育できる状態の場合、-3点の減点があります。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、きょうだい在園で+3点、認可外利用で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：就労証明書の記入漏れ</h2><p>就労時間の記載が不正確だと指数計算に影響します。勤務先に正確に記入してもらいましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "matsusaka",
    title: "松阪市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "松阪市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育所への入所を目指して活動することです。松阪市は三重県の中南部に位置し、人口約16万人。松阪牛で全国的に知られる商業・農業都市です。</p><h2>松阪市の保育施設の種類</h2><ul><li>認可保育所：松阪市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可外だが届出済みの施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の8〜9月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 37,
  },
  {
    slug: "point-system",
    citySlug: "matsusaka",
    title: "松阪市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "松阪市の保育所利用調整で最も重要な基本点数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本点数とは</h2><p>松阪市の保育所利用調整は点数方式です。基本点数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本点数の満点です。</p><div class="point-box"><p>利用調整点数＝基本点数（父）＋基本点数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本点数の合計は40点になります。</p><h3>就労時間別の基本点数</h3><ul><li>月160時間以上：20点</li><li>月120〜160時間未満：18点</li><li>月100〜120時間未満：16点</li><li>月80〜100時間未満：14点</li><li>月64〜80時間未満：12点</li><li>月48〜64時間未満：8点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "matsusaka",
    title: "松阪市の入園点数のしくみ　基本点数と調整指数をやさしく解説",
    description: "松阪市の保育所利用調整で使われる基本点数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。松阪市の主な調整指数は以下の通りです。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+5点</li><li>きょうだいが希望施設に在園中：+3点</li><li>きょうだいと同時申込み：+2点</li><li>生活保護受給：+3点</li><li>認可外保育施設に月ぎめで利用中：+3点</li><li>育児休業から復帰予定（入園月に復職）：+2点</li></ul><h3>減算項目</h3><ul><li>65歳未満の祖父母が同居し保育可能：-3点</li></ul><div class="point-box"><p>同居の祖父母が保育できる状態だと-3点の減点になります。三重県内では標準的な調整方式です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 43,
  },
  {
    slug: "selection-process",
    citySlug: "matsusaka",
    title: "松阪市の保育所選考フロー　書類提出から入所決定まで",
    description: "松阪市の保育所利用調整の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月に、松阪市こども局こども未来課へ提出します。就労証明書など必要書類を揃えましょう。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>点数の計算</strong><p>松阪市が申込書類に基づいて点数を計算します。基本点数（父母各最大20点）と調整指数の合計が利用調整点数です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>点数の高い順に、希望施設との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "score-up-checklist",
    citySlug: "matsusaka",
    title: "松阪市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "松阪市の利用調整で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯で就労中→+5点</li><li>きょうだいが希望施設に在園中→+3点</li><li>きょうだいと同時申込み→+2点</li><li>生活保護受給中→+3点</li><li>認可外保育施設に月ぎめで利用中→+3点</li><li>育休から復帰予定（入園月に復職）→+2点</li></ul><div class="point-box"><p>松阪市では認可外保育施設の月ぎめ利用が+3点の加点になります。一度不承諾になった場合は認可外に預けながら翌年再申請する戦略が有効です。</p></div><h2>注意：祖父母が同居している場合</h2><p>65歳未満の祖父母が同居し保育できる場合は-3点です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 49,
  },
  {
    slug: "area-guide",
    citySlug: "matsusaka",
    title: "松阪市の保育所マップ　エリアごとの入りやすさを比較",
    description: "松阪市内のエリアごとの保育所の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>松阪市の保育所事情</h2><p>松阪市は三重県の中南部に位置する人口約16万人の都市です。松阪牛の産地として有名で、農業・商業が盛んな地域です。市内に認可保育所が多数あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>松阪駅周辺・中心市街地：交通の便が良く人気が集中</li><li>松阪インター周辺・朝見地区：住宅開発が進む地域</li></ul><h3>比較的入りやすいエリア</h3><ul><li>嬉野・三雲・飯南地区：市の北西部・中南部の農村エリア</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 32,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "matsusaka",
    title: "松阪市の認可外保育施設ガイド　認可所との違いは？",
    description: "松阪市で認可保育所に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。松阪市内にも複数存在します。</p><h2>認可所との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の調整指数</td><td>-</td><td>+3点の加点</td></tr></table><div class="point-box"><p>松阪市では認可外保育施設に月ぎめで預けている場合、翌年度の選考で+3点の加点があります。一度不承諾になっても認可外に預けながら再申請する戦略は有効です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 33,
  },
  {
    slug: "ikukyuu-guide",
    citySlug: "matsusaka",
    title: "松阪市で育休から保育所へ復帰する流れ",
    description: "松阪市で育児休業から認可保育所に入所して職場復帰するための手順を解説します。",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>育休中の保活スケジュール</h2><p>育休中の保護者が4月入所を目指す場合、育休終了時期と入所時期を合わせることが重要です。</p><h2>育休復帰の加点について</h2><p>松阪市では、入園月に職場復帰する予定の場合、調整指数で+2点の加点があります。復職予定の書類を準備して申込みましょう。</p><h2>注意点</h2><ul><li>内定後に育休を延長した場合、入所が取り消されることがあります</li><li>入所後に就労実態がない場合は退所となる場合があります</li><li>農業や自営業の場合は就労時間の証明方法を事前に確認しましょう</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
];

registerArticles(articles);
