import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  { slug: "hokatsu-schedule", citySlug: "moriya", title: "守谷市の保活スケジュール　令和8年度4月入園の流れ", description: "守谷市の保育園申込時期・選考の流れをわかりやすく解説します。", image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>令和8年度4月入園のスケジュール</h2><p>守谷市の4月入園は<strong>一次</strong>と<strong>二次利用調整</strong>に分かれています。申込先は守谷市子ども家庭課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付</td><td>令和7年11月上旬〜12月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月下旬</td></tr></table>`, publishedAt: "2026-04-29", popularity: 48 },
  { slug: "hokatsu-mistakes", citySlug: "moriya", title: "守谷市の保活でよくある失敗と対策5選", description: "初めてのママがやりがちな失敗パターンと対策をまとめました。", image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>失敗1：スタートが遅い</h2><p>守谷市は人口約7万人の小規模自治体。11月からの申込に向けて6月には動き始めましょう。</p><h2>失敗2：希望園が少ない</h2><p>園の数が少ないため、複数園の希望が重要です。</p><h2>失敗3：点数を把握していない</h2><p>基本指数40点がフルタイム共働きの標準です。</p>`, publishedAt: "2026-04-29", popularity: 46 },
  { slug: "scoring-system-guide", citySlug: "moriya", title: "守谷市の入園点数のしくみ　基本指数と調整指数", description: "点数の仕組みを初めての方にもわかるように解説します。", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: `<h2>選考指数の仕組み</h2><p>選考指数 ＝ 基本指数（父）＋ 基本指数（母）＋ 調整指数</p><h2>基本指数</h2><p>就労時間で判定。月160時間以上で満点20点。父母合計最大40点。</p><h2>調整指数</h2><ul><li>ひとり親：+6点</li><li>きょうだい在園中：+4点</li><li>認可外利用：+2点</li><li>生活保護：+4点</li></ul>`, publishedAt: "2026-04-29", popularity: 54 },
  { slug: "score-up-checklist", citySlug: "moriya", title: "守谷市で点数を上げる方法　加点チェックリスト", description: "調整指数の加点を最大限に活用する方法を解説します。", image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop", category: "点数アップ", categoryColor: "amber", content: `<h2>加点チェックリスト</h2><ul><li>ひとり親で就労中 → +6点</li><li>きょうだい在園中 → +4点</li><li>認可外利用 → +2点</li><li>生活保護 → +4点</li><li>きょうだい同時申込 → +3点</li><li>育休明け復職 → +2点</li></ul><p>小規模自治体なので加点が特に重要です。</p>`, publishedAt: "2026-04-29", popularity: 50 },
  { slug: "area-guide", citySlug: "moriya", title: "守谷市の保育園マップ　エリアごとの入りやすさ", description: "守谷市内のエリアごとの競争率や特徴をまとめました。", image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop", category: "エリア情報", categoryColor: "purple", content: `<h2>守谷市の保育園事情</h2><p>茨城県南部の人口約7万人の小規模市。つくばエクスプレスの守谷駅周辺がメインエリアです。認可保育園は約18か所。</p><h3>競争率が高いエリア</h3><ul><li><strong>守谷駅周辺</strong>：駅近の園は人気集中</li></ul><h3>入りやすいエリア</h3><ul><li><strong>郊外エリア</strong>：比較的空きあり</li></ul>`, publishedAt: "2026-04-29", popularity: 42 },
  { slug: "ninkagai-guide", citySlug: "moriya", title: "守谷市の認可外保育施設ガイド　認可園との違い", description: "認可園に入れなかった場合の選択肢について解説します。", image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop", category: "認可外保育", categoryColor: "teal", content: `<h2>認可外保育施設とは？</h2><p>自治体に届出をして運営している保育施設です。守谷市内にも複数あります。</p><h3>認可園との比較</h3><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得応じて決定</td><td>施設が設定</td></tr><tr><td>翌年加点</td><td>-</td><td>+2点</td></tr></table><p>小規模自治体だからこそ、認可外の選択肢も大切です。</p>`, publishedAt: "2026-04-29", popularity: 39 },
  { slug: "tiebreaker-guide", citySlug: "moriya", title: "守谷市で同点になったら　優先順位のしくみ", description: "同点になった場合の優先順位と対策を解説します。", image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=400&fit=crop", category: "選考のしくみ", categoryColor: "blue", content: `<h2>同点の優先順位</h2><ol><li>ひとり親世帯</li><li>きょうだい在園中</li><li>基本指数が高い</li><li>市の居住期間が長い</li><li>所得が低い</li></ol><p>小規模自治体だからこそ同点を避けることが特に重要です。</p>`, publishedAt: "2026-04-29", popularity: 44 },
  { slug: "small-nursery", citySlug: "moriya", title: "守谷市の小規模保育　メリット・デメリット", description: "小規模保育事業の特徴や卒園後の進路について解説します。", image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>小規模保育とは？</h2><p>定員6〜19人の少人数施設。0〜2歳児が対象。3歳以降は転園が必要です。</p><h2>メリット</h2><ul><li>少人数でアットホーム</li><li>認可園より入りやすい</li><li>卒園時に優先枠あり</li></ul><h2>デメリット</h2><ul><li>3歳で転園必須</li><li>園庭がない場合が多い</li></ul>`, publishedAt: "2026-04-29", popularity: 36 },
  { slug: "nursery-fees", citySlug: "moriya", title: "守谷市の保育料はいくら？　世帯年収別の目安", description: "認可保育園の保育料を世帯年収別に紹介します。", image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop", category: "お金の話", categoryColor: "rose", content: `<h2>保育料の仕組み</h2><p>世帯の住民税額と子どもの年齢で決まります。</p><h2>3歳以上は無償化</h2><p>3歳児クラス以上は保育料無料です。給食費は別途必要。</p><h3>世帯年収別の目安（0〜2歳）</h3><table><tr><th>年収目安</th><th>月額</th></tr><tr><td>〜300万</td><td>0〜6,000円</td></tr><tr><td>300〜500万</td><td>10,000〜25,000円</td></tr></table>`, publishedAt: "2026-04-29", popularity: 40 },
  { slug: "nursery-visit-guide", citySlug: "moriya", title: "守谷市の保育園見学ガイド　チェックポイント", description: "見学で確認すべきポイントと質問リストをまとめました。", image: "https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=800&h=400&fit=crop", category: "保活の基本", categoryColor: "green", content: `<h2>見学のベストシーズン</h2><p>6月〜9月が最適。10月以降は申込直前で混み合います。</p><h2>チェックポイント</h2><ul><li>園児たちの雰囲気</li><li>保育士の対応</li><li>園舎の状態</li><li>給食とアレルギー対応</li><li>持ち物と送迎動線</li></ul><h2>質問リスト</h2><ul><li>延長保育の時間と料金</li><li>慣らし保育の期間</li><li>発熱時のお迎え</li><li>行事への参加</li></ul>`, publishedAt: "2026-04-29", popularity: 37 },
];

registerArticles(articles);
