import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "niihama",
    title: "新居浜市の保活スケジュール　令和8年度4月入園の流れ",
    description: "新居浜市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>新居浜市は愛媛県東予地方に位置する人口約11万人の都市です。住友グループの企業城下町として知られ、共働き世帯が多いため保育需要は旺盛です。申込先は新居浜市こども育て課です。</p><h2>一次申込</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年11月上旬〜11月下旬</td></tr><tr><td>結果通知</td><td>令和8年2月上旬</td></tr></table><h2>二次申込・随時申込</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月中旬〜</td></tr><tr><td>結果通知</td><td>随時通知</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>新居浜市は企業城下町のため、大手企業の育休明けが集中する4月の競争率が高いのが特徴です。早めの申込を心がけましょう。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 40,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "niihama",
    title: "新居浜市の保活でよくある失敗と対策5選",
    description: "新居浜市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：見学スケジュールが後ろ倒しになる</h2><p>新居浜市は申込が11月上旬からのため、遅くとも9月中に希望園の見学を終わらせることが重要です。</p><h2>失敗2：就労時間の計算間違い</h2><p>新居浜市では月160時間以上で15点です。月64〜79時間では11点と大きく下がります。就労証明書で正確に申告しましょう。</p><h2>失敗3：祖父母同居の減点を見落とす</h2><p>同居する65歳未満の祖父母が保育可能な場合は-2点の減点があります。</p><h2>失敗4：DV・虐待の加点を申告しない</h2><p>DV・虐待の被害を受けている場合、+15点の大幅加点があります。支援機関を通じた申告が可能です。</p><h2>失敗5：きょうだい同施設の加点確認不足</h2><p>きょうだいが同一施設に在籍している場合は+3点の加点があります。申込時に忘れず申告しましょう。</p>`,
    publishedAt: "2026-05-08",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "niihama",
    title: "新居浜市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "新居浜市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。新居浜市は住友グループの企業城下町として発展した愛媛県東予地方の中核都市です。</p><h2>新居浜市の保育園の種類</h2><ul><li>認可保育園：新居浜市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可基準を満たさないが届出済みの施設。</li></ul><h2>いつから始めるべき？</h2><ul><li>生後2〜3か月：保育園の種類や制度を調べ始める</li><li>生後4〜5か月：希望する保育園をリストアップ</li><li>生後6〜8か月：保育園見学（秋申込に向け夏までに完了）</li><li>生後9〜10か月：申込書類の準備</li><li>生後11か月ごろ：申込提出（11月の申込期間に合わせる）</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 32,
  },
  {
    slug: "point-system",
    citySlug: "niihama",
    title: "新居浜市の基本指数システム　30点満点の仕組みをわかりやすく",
    description: "新居浜市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>新居浜市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各15点ずつ、基本指数の合計は30点になります。</p><h3>就労時間と点数の関係</h3><ul><li>月160時間以上：15点</li><li>月140時間以上160時間未満：14点</li><li>月120時間以上140時間未満：13点</li><li>月80時間以上120時間未満：12点</li><li>月64時間以上80時間未満：11点</li></ul><div class="point-box"><p>新居浜市は5段階の就労時間区分が設けられており、フルタイム共働きで合計30点が基本的な目安です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 47,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "niihama",
    title: "新居浜市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "新居浜市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+5点</li><li>生活保護受給：+3点</li><li>申込児童に障がい（身体障害1・2級等）：+4点</li><li>DV・虐待の被害：+15点</li><li>きょうだいが同一施設に在籍または同時申込：+3点</li></ul><h3>主な減算項目</h3><ul><li>同居する65歳未満祖父母が保育可能：-2点</li></ul><div class="point-box"><p>DV・虐待の被害に対する+15点は大きな加点です。支援機関を通じて申告が可能です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 49,
  },
  {
    slug: "selection-process",
    citySlug: "niihama",
    title: "新居浜市の保育園選考フロー　書類提出から入園決定まで",
    description: "新居浜市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>11月上旬〜下旬に、新居浜市こども育て課へ提出します。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>新居浜市が申込書類に基づいて指数を計算します。就労時間・調整指数の確認が重要です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は2月上旬に通知が届きます。不承諾の場合は二次申込を検討しましょう。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 43,
  },
  {
    slug: "score-up-checklist",
    citySlug: "niihama",
    title: "新居浜市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "新居浜市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯→+5点</li><li>生活保護受給→+3点</li><li>申込児童に障がいがある（身体障害1・2級等）→+4点</li><li>DV・虐待被害→+15点</li><li>きょうだいが同一施設に在籍または同時申込→+3点</li></ul><div class="point-box"><p>DV・虐待の+15点は全ての調整指数の中で最も大きな加点です。安全な場所で申告できます。</p></div><h2>減点チェックリスト</h2><ul><li>同居祖父母が65歳未満で保育可能→-2点</li></ul><h2>フルタイム就労で点数を上げるには</h2><p>月160時間以上（就労時間の最高区分）まで就労時間を増やすと、一人あたり最大15点になります。育休明けのフルタイム復帰が有利です。</p>`,
    publishedAt: "2026-05-08",
    popularity: 46,
  },
  {
    slug: "area-guide",
    citySlug: "niihama",
    title: "新居浜市の保育園マップ　エリアごとの入りやすさを比較",
    description: "新居浜市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>新居浜市の保育園事情</h2><p>新居浜市は人口約11万人の住友グループ企業城下町です。化学・金属などの大手企業が集積しており、共働き率が高いため保育ニーズが旺盛です。認可保育園は約30か所あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>新居浜駅周辺：交通利便性が高く人気が集中</li><li>工業地帯周辺：住友系企業の従業員が多く競争率高め</li></ul><h3>比較的入りやすいエリア</h3><ul><li>山側・郊外エリア：人口が少ないため比較的空きがある</li><li>新興住宅地：新規園が開設されている地区もある</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 34,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "niihama",
    title: "新居浜市の認可外保育施設ガイド　認可園との違いは？",
    description: "新居浜市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。新居浜市には企業内保育所なども存在します。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>選考</td><td>指数方式</td><td>施設独自</td></tr><tr><td>施設数</td><td>約30か所</td><td>複数</td></tr></table><div class="point-box"><p>住友系企業の従業員向け事業所内保育所もあります。勤務先に確認してみましょう。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 31,
  },
  {
    slug: "nursery-fees",
    citySlug: "niihama",
    title: "新居浜市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "新居浜市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。新居浜市もこの制度に対応しています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～5,000円</td></tr><tr><td>300～500万円</td><td>8,000～20,000円</td></tr><tr><td>500～700万円</td><td>22,000～36,000円</td></tr><tr><td>700～1,000万円</td><td>36,000～48,000円</td></tr></table><div class="point-box"><p>住友系大企業の従業員は世帯年収が高い傾向があるため、保育料の負担も大きくなります。福利厚生の保育補助制度を確認しましょう。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
];

registerArticles(articles);
