import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "nishio",
    title: "西尾市の保活スケジュール　令和8年度4月入園の流れ",
    description: "西尾市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>西尾市は愛知県の西三河南部に位置し、人口約16万人の都市です。自動車関連産業が盛んで共働き世帯が多く、保育園の競争率が高い地域です。申込先は西尾市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>西尾市の選考指数は父母各20点の合計40点満点です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 37,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "nishio",
    title: "西尾市の保活でよくある失敗と対策5選",
    description: "西尾市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>西尾市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>西尾市では希望園を複数記入できます。1〜2園しか書かないと不承諾のリスクが高まります。</p><h2>失敗3：自分の点数を把握していない</h2><p>西尾市は父母各20点の合計40点制です。フルタイム共働きで40点が基本ラインです。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+6点、きょうだい在園で+5点、育休復帰で+4点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：内定通知後の書類提出漏れ</h2><p>内定後に復職証明書や住民票の追加提出が必要な場合があります。指示された書類は期限内に提出しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 43,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "nishio",
    title: "西尾市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "西尾市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。西尾市は愛知県の西三河南部に位置し、人口約16万人。自動車関連企業の勤務者が多く、保育需要が高い地域です。</p><h2>西尾市の保育施設の種類</h2><ul><li>認可保育所：西尾市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>事業所内保育事業：企業が従業員向けに設置した施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の8〜9月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 39,
  },
  {
    slug: "point-system",
    citySlug: "nishio",
    title: "西尾市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "西尾市の保育園入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>西尾市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。父と母それぞれ最大20点で、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間別の基本指数</h3><ul><li>月160時間以上（フルタイム）：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li><li>就労予定（内定あり）：8点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 47,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "nishio",
    title: "西尾市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "西尾市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。西尾市の主な調整指数は以下の通りです。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+6点</li><li>きょうだいが同じ施設に在園中：+5点</li><li>きょうだいと同時申込み：+3点</li><li>生活保護受給：+5点</li><li>認可外保育施設に月ぎめで利用中：+4点</li><li>育児休業から復帰予定：+4点</li></ul><div class="point-box"><p>ひとり親家庭やきょうだい在園家庭は大きな加点が期待できます。複数の加点条件に当てはまる場合は合算されます。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "selection-process",
    citySlug: "nishio",
    title: "西尾市の保育園選考フロー　書類提出から入園決定まで",
    description: "西尾市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月に、西尾市子育て支援課へ提出します。就労証明書など必要書類を揃えましょう。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>西尾市が申込書類に基づいて指数を計算します。基本指数と調整指数の合計が選考指数です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。同点の場合は別の条件で順位が決まります。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "score-up-checklist",
    citySlug: "nishio",
    title: "西尾市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "西尾市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯で就労中→+6点</li><li>きょうだいが同じ施設に在園中→+5点</li><li>きょうだいと同時申込み→+3点</li><li>生活保護受給中→+5点</li><li>認可外保育施設に月ぎめで利用中→+4点</li><li>育休から復帰予定（入園月翌月1日までに復職）→+4点</li></ul><div class="point-box"><p>育休復帰の加点（+4点）を活用するためには、入園月の翌月1日までに復職することが条件です。職場との復職日の調整を早めに行いましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 51,
  },
  {
    slug: "area-guide",
    citySlug: "nishio",
    title: "西尾市の保育園マップ　エリアごとの入りやすさを比較",
    description: "西尾市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>西尾市の保育園事情</h2><p>西尾市は愛知県の西三河南部に位置する人口約16万人の都市です。自動車関連企業の工場が多く、フルタイム共働き世帯が多いため保育需要が高い地域です。市内に認可保育所が多数あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>西尾駅周辺・旧市街地：交通の便が良く人気が集中</li><li>一色・吉良地区：住宅開発が進む地域</li></ul><h3>比較的入りやすいエリア</h3><ul><li>幡豆・東幡豆地区：市街地から離れるため、空きがある園も</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 34,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "nishio",
    title: "西尾市の認可外保育施設ガイド　認可園との違いは？",
    description: "西尾市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。西尾市内にも複数存在します。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の調整指数</td><td>-</td><td>+4点の加点</td></tr></table><div class="point-box"><p>西尾市では認可外保育施設に月ぎめで預けている場合、翌年度の選考で+4点の加点があります。認可外に預けながら翌年の認可園を再申請する戦略は有効です。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 35,
  },
  {
    slug: "ikukyuu-guide",
    citySlug: "nishio",
    title: "西尾市で育休から保育園へ復帰する流れ",
    description: "西尾市で育児休業から認可保育園に入園して職場復帰するための手順を解説します。",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>育休中の保活スケジュール</h2><p>育休中の保護者が4月入園を目指す場合、育休終了時期と入園時期を合わせることが重要です。</p><h2>育休復帰の加点について</h2><p>西尾市では、入園月の翌月1日までに復職する予定の場合、調整指数で+4点の加点があります。職場との復職日調整を早めに行いましょう。</p><h2>注意点</h2><ul><li>内定後に育休を延長した場合、入園が取り消されることがあります</li><li>入所後に就労実態がない場合は退園となる場合があります</li><li>育休中でも就労予定として申込む形になります（内定があれば+8点）</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
];

registerArticles(articles);
