import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "nobeoka",
    title: "延岡市の保活スケジュール　令和8年度4月入園の流れ",
    description: "延岡市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>延岡市は宮崎県北部に位置し、人口約11.6万人の旭化成の企業城下町です。日向灘に面した港湾都市として知られ、工業・商業が盛んな地域です。申込先は延岡市こども保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年11月中旬〜12月上旬</td></tr><tr><td>結果通知</td><td>令和8年2月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月下旬〜3月上旬</td></tr><tr><td>結果通知</td><td>令和8年3月中旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>延岡市の選考指数は父母各15点の合計30点満点（宮崎県標準方式）です。フルタイム共働きで30点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 38,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "nobeoka",
    title: "延岡市の保活でよくある失敗と対策5選",
    description: "延岡市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>延岡市の4月入園の申込は11月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>延岡市は旭化成などの大企業が本社を置く企業城下町で、共働き世帯も多い地域です。人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>延岡市は父母各15点の合計30点制（宮崎県標準方式）です。月60時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、きょうだい在園で+5点、認可外利用で+8点、育休復帰で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>延岡市では60歳未満の同居祖父母が保育できる状態の場合に-2点となります。同居祖父母の就労状況を確認しておきましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 42,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "nobeoka",
    title: "延岡市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "延岡市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。延岡市は宮崎県北部の旭化成の企業城下町で、人口約11.6万人。日向灘に面した港湾都市として有名です。</p><h2>延岡市の保育施設の種類</h2><ul><li>認可保育所：延岡市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、11月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 40,
  },
  {
    slug: "point-system",
    citySlug: "nobeoka",
    title: "延岡市の基準指数システム　30点満点の仕組みをわかりやすく",
    description: "延岡市の保育施設入園選考で最も重要な基準指数（父母各15点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基準指数とは</h2><p>延岡市の保育施設入園は指数方式（宮崎県標準方式）です。基準指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大15点、合計30点が基準指数の満点です。</p><div class="point-box"><p>選考指数＝基準指数（父）＋基準指数（母）＋調整指数</p></div><h2>就労時間別の基準指数</h2><ul><li>月160時間以上：15点</li><li>月140〜160時間未満：14点</li><li>月120〜140時間未満：13点</li><li>月100〜120時間未満：12点</li><li>月80〜100時間未満：11点</li><li>月60〜80時間未満：10点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 44,
  },
  {
    slug: "adjustment-index",
    citySlug: "nobeoka",
    title: "延岡市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "延岡市の保育入園選考で基準指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>延岡市では基準指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>認可外保育施設卒園（新規申込み）</td><td>+8点</td></tr><tr><td>ひとり親世帯</td><td>+5点</td></tr><tr><td>きょうだいが申込み施設に在園中</td><td>+5点</td></tr><tr><td>産休・育休明けで復職</td><td>+3点</td></tr><tr><td>単身赴任</td><td>+3点</td></tr><tr><td>新規申込み</td><td>+2点</td></tr><tr><td>生活保護受給世帯</td><td>+2点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>60歳未満の同居祖父母が保育可能</td><td>-2点</td></tr></table>`,
    publishedAt: "2026-05-15",
    popularity: 46,
  },
  {
    slug: "single-parent",
    citySlug: "nobeoka",
    title: "延岡市のひとり親家庭の保活　+5点加点の活用法",
    description: "延岡市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>延岡市では、ひとり親世帯に対して+5点の調整指数加点があります。フルタイム就労15点＋ひとり親5点で20点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+5点）に加えて認可外利用中（+8点）、育休復帰（+3点）なども活用できます。</p>`,
    publishedAt: "2026-05-15",
    popularity: 36,
  },
  {
    slug: "working-mothers",
    citySlug: "nobeoka",
    title: "延岡市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "延岡市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基準指数</h2><p>延岡市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基準指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>15点</td></tr><tr><td>月140〜160時間未満</td><td>14点</td></tr><tr><td>月120〜140時間未満</td><td>13点</td></tr><tr><td>月100〜120時間未満</td><td>12点</td></tr><tr><td>月80〜100時間未満</td><td>11点</td></tr><tr><td>月60〜80時間未満</td><td>10点</td></tr></table><h2>旭化成などの大企業勤務の場合</h2><p>延岡市は旭化成の企業城下町として知られ、大企業勤務者が多い地域です。安定した勤務条件で就労証明書も作成しやすいでしょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 48,
  },
  {
    slug: "ikukyu-return",
    citySlug: "nobeoka",
    title: "延岡市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "延岡市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+3点）</h2><p>延岡市では、産休明け・育休明けで復職する場合に+3点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+3点）は認可外利用加点（+8点）と合算できます。合計+11点の上乗せが可能です。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 42,
  },
  {
    slug: "nursery-facilities",
    citySlug: "nobeoka",
    title: "延岡市の認可保育施設一覧　地区別の施設数と特徴",
    description: "延岡市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>延岡市の保育施設の概要</h2><p>延岡市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。市街地や各地域に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>延岡駅周辺・市街地：施設数が多く利便性が高い</li><li>北川・北浦地区：施設数は限られるが比較的定員に余裕のある施設が多い</li><li>南部工業団地周辺：大企業勤務者向けの施設が多い傾向</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 34,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "nobeoka",
    title: "延岡市の祖父母同居の減点　-2点の条件と対処法",
    description: "延岡市で60歳未満の同居祖父母がいる場合の減点（-2点）について、条件と対処法を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居の減点とは</h2><p>延岡市では、60歳未満の同居祖父母が保育できる状態にある場合、-2点の調整指数が適用されます。</p><h2>減点が適用される条件</h2><ul><li>60歳未満の祖父母が同居している</li><li>その祖父母が保育可能な状態（無職・就労時間が少ない等）</li></ul><h2>減点が適用されない条件</h2><ul><li>同居祖父母が60歳以上の場合</li><li>同居祖父母がフルタイムで就労している場合</li><li>同居祖父母が疾病・障害等で保育不可能な場合</li></ul><div class="point-box"><p>同居祖父母が就労している場合は就労証明書を提出することで減点を回避できる場合があります。市役所に確認しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 38,
  },
];

registerArticles(articles);
