import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "okinawa",
    title: "沖縄市の保活スケジュール　令和8年度4月入園の流れ",
    description: "沖縄市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>沖縄市は沖縄本島中部に位置し、人口約14万4千人の沖縄県第2の都市です。旧コザ市と美里村が合併した都市で、米軍基地に隣接する国際色豊かな都市です。申込先は沖縄市こどもの未来部保育・幼稚園課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>沖縄市の選考指数は父母各30点の合計60点満点（沖縄県標準方式）です。フルタイム共働きで60点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "okinawa",
    title: "沖縄市の保活でよくある失敗と対策5選",
    description: "沖縄市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>沖縄市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>沖縄市は待機児童が多い地域で、人気施設の競争率は非常に高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>沖縄市は父母各30点の合計60点制（沖縄県標準方式）です。月64時間未満では基本指数が低くなります。</p><h2>失敗4：大きな加点を見逃す</h2><p>ひとり親で+50点、認可保育所勤務保育士で+50点など、沖縄市は調整指数の加点幅が大きいです。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：育休復帰加点を使い忘れる</h2><p>沖縄市では育休復帰予定で+9点の加点があります。申込時に忘れずに記載しましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "okinawa",
    title: "沖縄市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "沖縄市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。沖縄市は沖縄本島中部に位置し、人口約14万4千人。国際色豊かな都市として知られています。</p><h2>沖縄市の保育施設の種類</h2><ul><li>認可保育所：沖縄市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "okinawa",
    title: "沖縄市の基本指数システム　60点満点の仕組みをわかりやすく",
    description: "沖縄市の保育施設入園選考で最も重要な基本指数（父母各30点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>沖縄市の保育施設入園は指数方式（沖縄県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大30点、合計60点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：30点</li><li>月140〜160時間未満：26点</li><li>月120〜140時間未満：22点</li><li>月90〜120時間未満：19点</li><li>月64〜90時間未満：15点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "okinawa",
    title: "沖縄市の調整指数ガイド　加点の全項目まとめ",
    description: "沖縄市の保育入園選考で基本指数に加算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>沖縄市では基本指数に加えて、世帯の状況に応じた調整指数が加算されます。沖縄県は全国と比べても調整指数の加点幅が大きいのが特徴です。</p><h2>主な加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+50点</td></tr><tr><td>認可保育所・こども園保育士として勤務</td><td>+50点</td></tr><tr><td>育児休業から復帰予定</td><td>+9点</td></tr><tr><td>きょうだいが在園中の園を第1希望</td><td>+7点</td></tr><tr><td>きょうだい同時入所申込</td><td>+6点</td></tr><tr><td>生活保護受給世帯</td><td>+3点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "okinawa",
    title: "沖縄市のひとり親家庭の保活　+50点加点の活用法",
    description: "沖縄市でひとり親として保活をする方向けに、ひとり親加点（+50点）の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>沖縄市では、ひとり親世帯に対して+50点という非常に大きな調整指数加点があります。フルタイム就労30点＋ひとり親50点で80点が確保できます。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li><li>配偶者の長期不在等でひとり親とみなされる場合</li></ul><div class="point-box"><p>沖縄市のひとり親加点+50点は全国でも最高水準の加点です。ひとり親世帯は基本指数が低くても入園できる可能性が大幅に高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "working-mothers",
    citySlug: "okinawa",
    title: "沖縄市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "沖縄市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>沖縄市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>30点</td></tr><tr><td>月140〜160時間未満</td><td>26点</td></tr><tr><td>月120〜140時間未満</td><td>22点</td></tr><tr><td>月90〜120時間未満</td><td>19点</td></tr><tr><td>月64〜90時間未満</td><td>15点</td></tr></table><h2>基地関連の仕事の場合</h2><p>沖縄市は米軍基地に隣接しており、基地関連の仕事や国際業務に従事する方も多くいます。雇用形態によらず、実際の月間就労時間で指数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "ikukyu-return",
    citySlug: "okinawa",
    title: "沖縄市で育休復帰を目指すママへ　+9点加点の活用法",
    description: "沖縄市で育休から復帰するタイミングで保活をする方向けに、育休復帰加点（+9点）の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+9点）</h2><p>沖縄市では、育児休業から復帰して入園する場合に+9点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入所した翌月1日までに復職すること</li><li>事業主からの復職予定証明書が必要</li></ul><div class="point-box"><p>フルタイム30点＋育休復帰+9点で39点が確保できます。共働きフルタイムで60点満点に近い状態で入園申込が可能です。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "okinawa",
    title: "沖縄市の認可保育施設一覧　地区別の施設数と特徴",
    description: "沖縄市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>沖縄市の保育施設の概要</h2><p>沖縄市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。沖縄市は沖縄県内でも待機児童が多い地域のひとつで、施設の整備が進んでいます。</p><h2>地区別の傾向</h2><ul><li>コザ・胡屋地区：市街地で施設が多いが競争率も高め</li><li>諸見里・美里地区：住宅地で比較的定員に余裕あり</li><li>越来・登川地区：施設数は少ないが競争率も低め</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "nursery-worker-bonus",
    citySlug: "okinawa",
    title: "沖縄市の保育士加点　+50点の条件と申請方法",
    description: "沖縄市で認可保育所・こども園の保育士として働く場合の加点（+50点）について詳しく解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>保育士加点とは</h2><p>沖縄市では、認可保育所または認定こども園で保育士等として働いている場合に+50点の調整指数が加算されます。</p><h2>加点を受けるための条件</h2><ul><li>認可保育所または認定こども園に保育士・幼稚園教諭等として在籍していること</li><li>在籍証明書を提出すること</li></ul><div class="point-box"><p>保育士加点+50点は沖縄市内の保育士確保を目的とした施策です。フルタイム就労30点＋保育士加点+50点で80点が確保でき、入園しやすい状況になります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
];

registerArticles(articles);
