import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "onomichi",
    title: "尾道市の保活スケジュール　令和8年度4月入園の流れ",
    description: "尾道市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>尾道市は広島県東部に位置し、人口約13万3千人の都市です。しまなみ海道の本州側起点として知られ、造船業・商業が主要産業です。坂道と寺社仏閣が織りなす風情ある景観で映画やアニメの舞台としても有名です。申込先は尾道市こども部保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>尾道市はランク制（A〜G）を採用しており、父母の低い方のランクが世帯のランクになるmin方式です（広島県標準方式）。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "rank-system",
    citySlug: "onomichi",
    title: "尾道市のランク制とは　A〜Gランクのしくみを詳しく解説",
    description: "尾道市の保育入園選考は他の自治体と異なるランク制（A〜G）を採用しています。その仕組みをわかりやすく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>ランク制とは</h2><p>尾道市は広島県の標準方式「ランク制」を採用しています。保育の必要度をA〜Gの7段階で判定し、父母それぞれのランクを評価したうえで「低い方のランク」が世帯のランクになります（min方式）。</p><div class="point-box"><p>世帯ランク＝min（父のランク、母のランク）＋調整指数</p></div><h2>ランク別の就労時間目安</h2><table><tr><th>ランク</th><th>就労時間</th></tr><tr><td>A（最高）</td><td>月160時間以上</td></tr><tr><td>B</td><td>月120〜160時間未満</td></tr><tr><td>C</td><td>月64〜120時間未満</td></tr><tr><td>D</td><td>月64時間未満</td></tr><tr><td>E</td><td>内職</td></tr><tr><td>G（最低）</td><td>求職中</td></tr></table><h2>min方式の注意点</h2><p>父母の一方がランクAでも、もう一方がランクGなら世帯ランクはGになります。両親ともに高いランクを維持することが重要です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 50,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "onomichi",
    title: "尾道市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "尾道市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。尾道市は広島県東部に位置し、人口約13万3千人。しまなみ海道の玄関口として知られ、造船業・観光業が盛んな都市です。</p><h2>尾道市の保育施設の種類</h2><ul><li>認可保育所：尾道市が認可した施設。保育料は世帯年収に応じて決定。選考はランク制。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "adjustment-index",
    citySlug: "onomichi",
    title: "尾道市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "尾道市の保育入園選考でランクに加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>尾道市ではランク（A〜G）に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>保育士・幼稚園教諭等として就労</td><td>+5点</td></tr><tr><td>きょうだいが認可保育所に在園中</td><td>+4点</td></tr><tr><td>きょうだいと同時に申し込む</td><td>+2点</td></tr><tr><td>育休明けの復帰</td><td>+3点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>育休延長も許容できる（不承諾通知目的）</td><td>-30点</td></tr></table><div class="point-box"><p>保育士・幼稚園教諭の加点（+5点）は尾道市独自の特徴です。保育士不足の解消を目的としています。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "onomichi",
    title: "尾道市の保活でよくある失敗と対策5選",
    description: "尾道市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：ランク制の仕組みを誤解する</h2><p>尾道市はランク制（A〜G）を採用しており、父母の低い方のランクが世帯ランクになります。両親ともに高いランクを維持することが重要です。</p><h2>失敗2：情報収集のスタートが遅い</h2><p>尾道市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗3：育休延長の減点を軽視する</h2><p>育休延長を許容する選択肢を選ぶと-30点の大きな減点があります。不承諾通知が必要な場合のみ選択してください。</p><h2>失敗4：保育士加点を見落とす</h2><p>保育士・幼稚園教諭として就労中の場合、+5点の大きな加点があります。</p><h2>失敗5：希望施設を少なく書く</h2><p>尾道市でも希望施設を複数記入できます。なるべく多く書いて入園の可能性を高めましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "working-mothers",
    citySlug: "onomichi",
    title: "尾道市の働くママの保活攻略法　ランクAを目指す就労時間",
    description: "尾道市でランクAを獲得するための就労時間と、ランクごとの違いをわかりやすく解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ランクAを目指すために</h2><p>尾道市の最高ランク「A」を得るには、月160時間以上の就労が必要です。週5日・8時間勤務で月約160〜175時間が目安です。</p><h2>min方式の影響</h2><p>尾道市はmin方式なので、夫婦どちらかのランクが低いと世帯全体のランクが引き下げられます。例えば父がランクAでも、母がランクCなら世帯ランクはCです。</p><h2>時短勤務の場合</h2><p>時短で月120時間以上就労すればランクB（2番目）を確保できます。週5日・6時間勤務が目安です。</p>`,
    publishedAt: "2026-05-11",
    popularity: 48,
  },
  {
    slug: "hoikushi-bonus",
    citySlug: "onomichi",
    title: "尾道市の保育士加点　+5点の優遇措置を詳しく解説",
    description: "尾道市で保育士・幼稚園教諭として就労している場合の加点（+5点）について詳しく解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>保育士加点とは</h2><p>尾道市では、保育士・幼稚園教諭等として就労している場合に+5点の調整指数加点があります。これは保育士不足の解消と、保育士が安心して働けるよう支援する目的で設けられています。</p><h2>対象となる職種</h2><ul><li>保育士</li><li>幼稚園教諭</li><li>認定こども園の保育教諭</li><li>その他これに準じる保育関連職種</li></ul><h2>活用のポイント</h2><p>保育士として就労しながら子どもの保育施設入園を申し込む場合、+5点の大きなアドバンテージが得られます。きょうだい在園加点（+4点）と合算すると合計+9点になります。</p>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "ikukyu-return",
    citySlug: "onomichi",
    title: "尾道市で育休復帰を目指すママへ　+3点加点の活用法",
    description: "尾道市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+3点）</h2><p>尾道市では、育児休業から復帰して入園する場合に+3点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p><strong>育休延長の選択には注意が必要</strong></p><p>育休延長を許容できる選択肢を選ぶと-30点の大きな減点があります。不承諾通知が欲しい場合のみ選んでください。不用意に選択しないよう注意しましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
  {
    slug: "nursery-facilities",
    citySlug: "onomichi",
    title: "尾道市の認可保育施設一覧　地区別の施設数と特徴",
    description: "尾道市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>尾道市の保育施設の概要</h2><p>尾道市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。尾道駅周辺や国道2号沿い・しまなみ街道沿いに施設が集中しています。</p><h2>地区別の傾向</h2><ul><li>尾道駅周辺・市街地：施設数が多く利便性が高いが競争率も高め</li><li>向島・因島地区：しまなみ海道の島嶼部で比較的定員に余裕がある</li><li>御調・瀬戸田地区：農村・離島エリアで施設数は少ないが競争率も低め</li></ul><div class="point-box"><p>第1〜第5希望まで記入できます。なるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 32,
  },
  {
    slug: "sibling-bonus",
    citySlug: "onomichi",
    title: "尾道市のきょうだい在園加点　+4点の高加点を活用する方法",
    description: "尾道市できょうだいが認可保育施設に在園中の場合の加点（+4点）について、条件と活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>きょうだい在園加点とは</h2><p>尾道市では、申込時点できょうだいが認可保育施設に在園中の場合、+4点の調整指数が加算されます。同一施設でなくても対象となります。</p><h2>同時申込加点との違い</h2><p>きょうだいと同時に申し込む場合は+2点の加点があります。在園加点（+4点）と同時申込加点（+2点）は重複して適用することはできません。上の子が入園済みの場合は在園加点が適用されます。</p><h2>加点活用のポイント</h2><p>すでに上の子が認可保育施設に在園中であれば、下の子の申込時に+4点のアドバンテージが得られます。きょうだい在園の事実を申込書類に必ず記載しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
];

registerArticles(articles);
