import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "osaki",
    title: "大崎市の保活スケジュール　令和8年度4月入園の流れ",
    description: "大崎市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>大崎市は宮城県北部に位置し、人口約12万4千人の都市です。古川市・鳴子町などの合併で誕生した広域市で、農業（ひとめぼれの産地）・商業が主要産業です。鳴子温泉を擁する観光地としても知られています。申込先は大崎市子ども子育て支援部保育課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>大崎市の選考指数は父母各10点の合計20点満点（宮城県標準方式）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 34,
  },
  {
    slug: "point-system",
    citySlug: "osaki",
    title: "大崎市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "大崎市の保育施設入園選考で最も重要な基本指数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>大崎市の保育施設入園は指数方式（宮城県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労状況別の基本指数</h2><table><tr><th>就労状況</th><th>基本指数</th></tr><tr><td>フルタイム（週5日・1日7時間以上）</td><td>10点</td></tr><tr><td>週5日・1日5〜7時間</td><td>8点</td></tr><tr><td>週4〜5日・1日4〜5時間</td><td>7点</td></tr><tr><td>月64時間以上（上記以外）</td><td>4点</td></tr></table><h2>フルタイム共働きの場合</h2><p>父・母ともにフルタイムで、各10点ずつ、基本指数の合計は20点になります。</p>`,
    publishedAt: "2026-05-11",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "osaki",
    title: "大崎市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "大崎市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。大崎市は宮城県北部に位置し、人口約12万4千人。農業・観光・商業が主要産業で、仙台市への通勤者も多い地域です。</p><h2>大崎市の保育施設の種類</h2><ul><li>認可保育所：大崎市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "adjustment-index",
    citySlug: "osaki",
    title: "大崎市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "大崎市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>大崎市では基本指数（最大20点）に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+3点</td></tr><tr><td>きょうだいが認可保育所に在園中、または同時申込</td><td>+3点</td></tr><tr><td>生活保護または住民税非課税世帯</td><td>+2点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>65歳未満の同居祖父母が保育可能</td><td>-1点</td></tr></table><div class="point-box"><p>大崎市は20点制のため、調整指数の影響が比較的大きくなります。利用できる加点を最大限活用しましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "osaki",
    title: "大崎市の保活でよくある失敗と対策5選",
    description: "大崎市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：20点制を他市と混同する</h2><p>大崎市は父母各10点・合計20点の宮城県標準方式です。40点制・100点制の自治体とは異なります。</p><h2>失敗2：情報収集のスタートが遅い</h2><p>大崎市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>フルタイム（週5日・1日7時間以上）で10点、それ以下では8点・7点・4点と下がります。自分の就労状況と対応する点数を確認しましょう。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+3点、きょうだい在園で+3点、生活保護・住民税非課税で+2点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>大崎市では65歳未満の同居祖父母が保育できる状態の場合に-1点となります。20点制では小さく見えますが、同点の場合に影響します。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "single-parent",
    citySlug: "osaki",
    title: "大崎市のひとり親家庭の保活　+3点加点の活用法",
    description: "大崎市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>大崎市では、ひとり親世帯に対して+3点の調整指数加点があります。20点制のため、+3点は全体の15%に相当する大きな加点です。フルタイム就労10点＋ひとり親3点で13点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li><li>配偶者が長期不在の場合も対象になるケースがあります</li></ul><p>ひとり親加点（+3点）に加えて生活保護・住民税非課税世帯（+2点）も合算できます。</p>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "working-mothers",
    citySlug: "osaki",
    title: "大崎市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "大崎市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>就労状況別の基本指数</h2><p>大崎市では就労状況によって基本指数が異なります（各10点満点）。</p><table><tr><th>就労状況</th><th>基本指数</th></tr><tr><td>フルタイム（週5日・1日7時間以上）</td><td>10点</td></tr><tr><td>週5日・1日5〜7時間</td><td>8点</td></tr><tr><td>週4〜5日・1日4〜5時間</td><td>7点</td></tr><tr><td>月64時間以上（上記以外）</td><td>4点</td></tr></table><h2>夫婦ともにフルタイムの場合</h2><p>両親各10点で合計20点。大崎市で最高の基本指数となります。</p><h2>農業・自営業の場合</h2><p>大崎市は農業が盛んな地域です。農業従事者や自営業者の場合も、実際の就労時間に基づいて指数が計算されます。</p>`,
    publishedAt: "2026-05-11",
    popularity: 46,
  },
  {
    slug: "sibling-bonus",
    citySlug: "osaki",
    title: "大崎市のきょうだい加点　在園・同時申込で+3点の活用法",
    description: "大崎市できょうだいが認可保育所に在園中または同時申込の場合の加点（+3点）について解説します。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>きょうだい加点とは</h2><p>大崎市では、きょうだいが認可保育所に在園中の場合、または同時に申し込む場合に+3点の調整指数が加算されます。在園・同時申込どちらにも同じ+3点が適用されます。</p><h2>加点の条件</h2><ul><li>きょうだいが認可保育所・認定こども園等に在園中であること、または</li><li>同じ年に複数の子どもを同時に申し込む場合</li></ul><h2>20点制での影響</h2><p>大崎市は20点制のため、+3点は全体の15%に相当する大きな加点です。活用できる場合は必ず申請しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 38,
  },
  {
    slug: "nursery-facilities",
    citySlug: "osaki",
    title: "大崎市の認可保育施設一覧　地区別の施設数と特徴",
    description: "大崎市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>大崎市の保育施設の概要</h2><p>大崎市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。古川駅周辺や国道4号・47号沿いに施設が集中しています。</p><h2>地区別の傾向</h2><ul><li>古川地区（市街地）：施設数が多く利便性が高いが競争率も高め</li><li>松山・岩出山地区：比較的定員に余裕のある施設が多い</li><li>鳴子・田尻地区：農村・温泉地域で施設数は少ないが競争率も低め</li></ul><div class="point-box"><p>第1〜第5希望まで記入できます。なるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 30,
  },
  {
    slug: "welfare-bonus",
    citySlug: "osaki",
    title: "大崎市の生活保護・住民税非課税世帯の加点　+2点の活用法",
    description: "大崎市で生活保護または住民税非課税世帯の場合の加点（+2点）について解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>生活保護・住民税非課税世帯の加点</h2><p>大崎市では、生活保護受給世帯または住民税非課税世帯に対して+2点の調整指数加点があります。住民税非課税世帯も対象となるのが大崎市の特徴です。</p><h2>対象となる世帯</h2><ul><li>生活保護受給中の世帯</li><li>住民税が非課税となっている世帯（前年度の所得が一定以下の場合）</li></ul><h2>住民税非課税の目安</h2><p>住民税非課税の目安は世帯構成によって異なりますが、概ね年収100〜125万円以下の場合に該当することが多いです。詳細は市役所税務課に確認しましょう。</p><div class="point-box"><p>20点制の大崎市では+2点は全体の10%に相当する重要な加点です。該当する場合は必ず申請しましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 34,
  },
];

registerArticles(articles);
