import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "sanda",
    title: "三田市の保活スケジュール　令和8年度4月入園の流れ",
    description: "三田市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>三田市は兵庫県南東部に位置し、人口約11万2千人の都市です。神戸・大阪のベッドタウンとしてニュータウンの開発が進んだ住宅地です。六甲山系の山々に囲まれた緑豊かな地域です。申込先は三田市保育振興課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>三田市の選考指数は父母各20点の合計40点満点です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "sanda",
    title: "三田市の保活でよくある失敗と対策5選",
    description: "三田市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>三田市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>三田市はベッドタウンとしての発展で子育て世帯が多い地域です。人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>三田市は父母各20点の合計40点制です。月48時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+7点、きょうだい在園で+4点など。使える加点を漏れなくチェックしましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "sanda",
    title: "三田市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "三田市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。三田市は兵庫県南東部に位置し、人口約11万2千人。神戸・大阪のベッドタウンとして開発が進んだ住宅地です。</p><h2>三田市の保育施設の種類</h2><ul><li>認可保育所：三田市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "sanda",
    title: "三田市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "三田市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>三田市の保育施設入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月100〜120時間未満：14点</li><li>月80〜100時間未満：12点</li><li>月64〜80時間未満：10点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "sanda",
    title: "三田市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "三田市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>三田市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+7点</td></tr><tr><td>きょうだいが在園中</td><td>+4点</td></tr><tr><td>きょうだいと同時申込み</td><td>+2点</td></tr><tr><td>多胎児が同時申込み</td><td>+4点</td></tr><tr><td>生活保護受給世帯</td><td>+2点</td></tr></table>`,
    publishedAt: "2026-05-15",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "sanda",
    title: "三田市のひとり親家庭の保活　+7点加点の活用法",
    description: "三田市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>三田市では、ひとり親世帯に対して+7点の調整指数加点があります。フルタイム就労20点＋ひとり親7点で27点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "sanda",
    title: "三田市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "三田市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>三田市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>20点</td></tr><tr><td>月140〜160時間未満</td><td>18点</td></tr><tr><td>月120〜140時間未満</td><td>16点</td></tr><tr><td>月100〜120時間未満</td><td>14点</td></tr><tr><td>月80〜100時間未満</td><td>12点</td></tr><tr><td>月64〜80時間未満</td><td>10点</td></tr></table><h2>ベッドタウン特性</h2><p>三田市は神戸・大阪方面への通勤者が多い地域です。フルタイム就労世帯も多く、点数計算が重要になります。</p>`,
    publishedAt: "2026-05-15",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "sanda",
    title: "三田市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "三田市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰について</h2><p>三田市では、育児休業から復帰する場合の専門的な加点制度は設けられていません。ただし、育児休業中であっても保育が必要と認められる場合は申込が可能です。</p><h2>申込の際の注意点</h2><ul><li>育児休業取得中であることを申告書に記載</li><li>入園予定日までに復職の予定があることを説明</li><li>必要に応じて復職予定証明書を提出</li></ul><div class="point-box"><p>育児休業延長を希望する場合は、基準指数から-20点の調整が入る可能性があります。復職予定時期について市役所に相談しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "sanda",
    title: "三田市の認可保育施設一覧　地区別の施設数と特徴",
    description: "三田市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>三田市の保育施設の概要</h2><p>三田市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。三田駅周辺や中心市街地、ニュータウンエリアに施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>三田駅周辺・市街地：施設数が多く利便性が高い</li><li>ニュータウンエリア：比較的定員に余裕のある施設が多い</li><li>周辺農村地区：施設数が少なめだが、通勤路線で補完</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 32,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "sanda",
    title: "三田市で祖父母と同居している場合　申告と相談のポイント",
    description: "三田市で祖父母と同居している場合の申込方法と、市役所への相談ポイントを解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居について</h2><p>三田市では、65歳未満の同居祖父母の状況に基づく専門的な減点制度は設けられていません。申込時に家族構成や世帯状況を正確に申告することが重要です。</p><h2>申告時に必要な情報</h2><ul><li>同居家族全員の氏名と年齢</li><li>祖父母の就労状況</li><li>祖父母が保育に携わることができるかどうか</li></ul><h2>相談が必要な場合</h2><p>家族構成が複雑な場合や、祖父母の状況が入園選考に影響する可能性があると考える場合は、事前に三田市保育振興課に相談することをお勧めします。</p><div class="point-box"><p>公平な選考のため、申告書の記載事項は正確・正直に記載しましょう。不明な点は市役所に確認してください。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 36,
  },
];

registerArticles(articles);
