import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "tomigusuku",
    title: "豊見城市の保活スケジュール　令和8年度4月入園の流れ",
    description: "豊見城市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>豊見城市は沖縄県南部に位置する人口約6万人の市です。那覇市に隣接しており、ベッドタウンとして人口が増加しています。申込先は豊見城市こども部こども支援課です。</p><h2>一次申込</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年11月上旬〜11月下旬</td></tr><tr><td>結果通知</td><td>令和8年1月下旬</td></tr></table><h2>二次申込・随時申込</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜</td></tr><tr><td>結果通知</td><td>随時通知</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>豊見城市は那覇市に隣接する成長都市です。新しい住宅地が多く保育ニーズが高いため、早めの申込が重要です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 40,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "tomigusuku",
    title: "豊見城市の保活でよくある失敗と対策5選",
    description: "豊見城市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：見学スケジュールが後ろ倒しになる</h2><p>豊見城市は申込が11月上旬からです。9月中に希望園の見学を終わらせることが重要です。</p><h2>失敗2：就労時間の計算間違い</h2><p>豊見城市では月160時間以上で20点です。月64〜79時間では10点と差が大きいです。就労証明書で正確に申告しましょう。</p><h2>失敗3：育休延長の大幅減点</h2><p>育休を延長して入所を希望する場合は-150点の大幅減点があります。育休延長は慎重に判断しましょう。</p><h2>失敗4：きょうだい加点の確認不足</h2><p>きょうだいが同じ施設に在籍・同時申込の場合は+11点の大きな加点があります。忘れずに申告しましょう。</p><h2>失敗5：DV・虐待の支援制度を知らない</h2><p>DV・虐待被害者は市役所の相談窓口を通じた特別配慮があります。安全な環境での支援申請が可能です。</p>`,
    publishedAt: "2026-05-08",
    popularity: 44,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "tomigusuku",
    title: "豊見城市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "豊見城市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。豊見城市は沖縄県南部の那覇市に隣接した成長都市で、近年人口が増加しています。</p><h2>豊見城市の保育園の種類</h2><ul><li>認可保育園：豊見城市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li></ul><h2>いつから始めるべき？</h2><ul><li>生後2〜3か月：保育園の制度を調べ始める</li><li>生後6〜8か月：希望保育園の見学（秋申込に向け夏までに）</li><li>生後9〜10か月：申込書類の準備</li><li>生後11か月ごろ：11月の申込期間に合わせて提出</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 32,
  },
  {
    slug: "point-system",
    citySlug: "tomigusuku",
    title: "豊見城市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "豊見城市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>豊見城市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間と点数の関係</h3><ul><li>月160時間以上：20点</li><li>月140時間以上160時間未満：18点</li><li>月120時間以上140時間未満：16点</li><li>月100時間以上120時間未満：14点</li><li>月80時間以上100時間未満：12点</li><li>月64時間以上80時間未満：10点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 47,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "tomigusuku",
    title: "豊見城市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "豊見城市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。豊見城市では育休延長による大幅減点が特徴的です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+12点</li><li>生活保護受給：+7点</li><li>申込児童に障がいがある：+13点</li><li>きょうだいが同一施設に在籍・同時申込：+11点</li><li>市内認可保育施設に保育士として就労：+15点</li></ul><h3>主な減算項目</h3><ul><li>同居祖父母が保育可能：-3点</li><li>育児休業の延長（1歳以降の入所希望）：-150点</li></ul><div class="point-box"><p>育休延長による-150点は非常に大きな減点です。復職を前提とした申込が重要です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 49,
  },
  {
    slug: "selection-process",
    citySlug: "tomigusuku",
    title: "豊見城市の保育園選考フロー　書類提出から入園決定まで",
    description: "豊見城市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>11月上旬〜下旬に、豊見城市こども支援課へ提出します。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>豊見城市が申込書類に基づいて指数を計算します。就労時間の確認が重要です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月下旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 43,
  },
  {
    slug: "score-up-checklist",
    citySlug: "tomigusuku",
    title: "豊見城市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "豊見城市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯→+12点</li><li>生活保護受給→+7点</li><li>申込児童に障がいがある→+13点</li><li>きょうだいが同一施設在籍→+11点</li><li>市内認可保育施設で保育士として就労→+15点</li><li>市外認可外施設で保育士として就労→+5点</li></ul><div class="point-box"><p>市内認可保育施設の保育士就労+15点は大きな加点です。</p></div><h2>減点注意リスト</h2><ul><li>同居祖父母が保育可能→-3点</li><li>育休延長して入所希望→-150点（極めて大きな減点）</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 46,
  },
  {
    slug: "area-guide",
    citySlug: "tomigusuku",
    title: "豊見城市の保育園マップ　エリアごとの入りやすさを比較",
    description: "豊見城市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>豊見城市の保育園事情</h2><p>豊見城市は沖縄県南部の那覇市に隣接した市です。人口約6万人で成長が著しく、新興住宅地が多数あります。認可保育園は約20か所あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>豊崎・翁長地区：大型商業施設や新興住宅地があり若い世代が多い</li><li>豊見城中心部：交通利便性が高く人気が集中</li></ul><h3>比較的入りやすいエリア</h3><ul><li>郊外・南部エリア：居住人口が比較的少ないため空きがある園も</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 34,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "tomigusuku",
    title: "豊見城市の認可外保育施設ガイド　認可園との違いは？",
    description: "豊見城市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。沖縄県は認可外保育施設が比較的多い地域として知られています。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>選考</td><td>指数方式</td><td>施設独自</td></tr></table><div class="point-box"><p>沖縄県では認可外保育施設への補助制度があります。認可園に入れなかった場合でも費用負担が軽減される場合があります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 31,
  },
  {
    slug: "nursery-fees",
    citySlug: "tomigusuku",
    title: "豊見城市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "豊見城市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。豊見城市もこの制度に対応しています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～5,000円</td></tr><tr><td>300～500万円</td><td>7,000～18,000円</td></tr><tr><td>500～700万円</td><td>20,000～32,000円</td></tr><tr><td>700万円以上</td><td>32,000円〜</td></tr></table><div class="point-box"><p>豊見城市は沖縄県内でも比較的所得水準が高い地域です。3歳未満の保育料は世帯の課税状況によって決まります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
];

registerArticles(articles);
