import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "tsuchiura",
    title: "土浦市の保活スケジュール　令和8年度4月入園の流れ",
    description: "土浦市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>土浦市は茨城県南部に位置し、人口約13万6千人の都市です。霞ケ浦に面した水郷の都市として知られ、つくばエクスプレス沿線でつくばへのアクセスも良好です。申込先は土浦市こども家庭課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>土浦市の選考指数は父母各10点の合計20点満点（茨城県標準方式）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "tsuchiura",
    title: "土浦市の保活でよくある失敗と対策5選",
    description: "土浦市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>土浦市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>土浦市はつくば研究学園都市に隣接しており、研究職・技術職の共働き世帯も多い地域です。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>土浦市は父母各10点の合計20点制（茨城県標準方式）です。月64時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、育休復帰で+2点、きょうだい在園同施設で+3点、小規模卒園で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：勤務証明書の記載漏れ</h2><p>茨城県標準方式では月間就労時間が厳密に審査されます。勤務証明書の記載を正確に確認しましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "tsuchiura",
    title: "土浦市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "土浦市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。土浦市は茨城県南部に位置し、人口約13万6千人。霞ケ浦に面した水郷の都市で、つくばへのアクセスも良好です。</p><h2>土浦市の保育施設の種類</h2><ul><li>認可保育所：土浦市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "tsuchiura",
    title: "土浦市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "土浦市の保育施設入園選考で最も重要な基本指数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>土浦市の保育施設入園は指数方式（茨城県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：10点</li><li>月140〜160時間未満：9点</li><li>月120〜140時間未満：8点</li><li>月100〜120時間未満：7点</li><li>月64〜100時間未満：6点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "tsuchiura",
    title: "土浦市の調整指数ガイド　加点の全項目まとめ",
    description: "土浦市の保育入園選考で基本指数に加算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>土浦市では基本指数に加えて、世帯の状況に応じた調整指数が加算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+5点</td></tr><tr><td>育児休業から復帰予定</td><td>+2点</td></tr><tr><td>きょうだいが在園中（同じ園を希望）</td><td>+3点</td></tr><tr><td>きょうだいが在園中（別の園）</td><td>+1点</td></tr><tr><td>きょうだいと同時申込み</td><td>+2点</td></tr><tr><td>小規模保育等の卒園（連携施設への転所）</td><td>+3点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "tsuchiura",
    title: "土浦市のひとり親家庭の保活　+5点加点の活用法",
    description: "土浦市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>土浦市では、ひとり親世帯に対して+5点の調整指数加点があります。フルタイム就労10点＋ひとり親5点で15点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+5点）に加えて、育休復帰（+2点）、きょうだい在園（+3点）と合算することも可能です。</p>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "tsuchiura",
    title: "土浦市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "土浦市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>土浦市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月140〜160時間未満</td><td>9点</td></tr><tr><td>月120〜140時間未満</td><td>8点</td></tr><tr><td>月100〜120時間未満</td><td>7点</td></tr><tr><td>月64〜100時間未満</td><td>6点</td></tr></table><h2>研究職・技術職の場合</h2><p>土浦市はつくば研究学園都市に隣接しており、研究職・技術職の方も多く住んでいます。実際の月間就労時間で指数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "tsuchiura",
    title: "土浦市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "土浦市で育休から復帰するタイミングで保活をする方向けに、加点の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+2点）</h2><p>土浦市では、育児休業から復帰して入園する場合に+2点の調整指数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>フルタイム10点＋育休復帰+2点で12点が確保できます。さらにきょうだいが在園中（+3点）など他の加点と合算することで有利になります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "tsuchiura",
    title: "土浦市の認可保育施設一覧　地区別の施設数と特徴",
    description: "土浦市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>土浦市の保育施設の概要</h2><p>土浦市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。土浦駅周辺や市内各地に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>土浦駅周辺・市街地：施設数が多く利便性が高い</li><li>都和・新治地区：比較的定員に余裕のある施設が多い</li><li>荒川沖・神立地区：住宅地として発展中</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "regional-nursery",
    citySlug: "tsuchiura",
    title: "土浦市の小規模保育卒園後の転所　連携施設への+3点加点",
    description: "土浦市で小規模保育等を卒園する際の連携施設への転所加点（+3点）について解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>小規模保育卒園加点とは</h2><p>土浦市では、小規模保育事業等（0〜2歳児）を卒園する際に連携施設への入所を希望する場合、+3点の調整指数が加算されます。</p><h2>加点を受けるための条件</h2><ul><li>小規模保育事業・家庭的保育・事業所内保育などの卒園児であること</li><li>連携施設への入所を希望していること</li><li>在籍施設から証明書を取得すること</li></ul><div class="point-box"><p>フルタイム10点＋小規模卒園+3点で13点が確保できます。3歳以降の保活を有利に進めるために、0〜2歳では小規模保育への入園も検討しましょう。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
];

registerArticles(articles);
