import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "ube",
    title: "宇部市の保活スケジュール　令和8年度4月入園の流れ",
    description: "宇部市の認可保育所の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>宇部市は山口県の南西部に位置し、人口約16万人の都市です。山口宇部空港があり、化学・重工業が盛んな工業都市です。申込先は宇部市保育幼稚園課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>宇部市の選考指数は父母各20点の合計40点満点です。フルタイム共働きで40点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 35,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "ube",
    title: "宇部市の保活でよくある失敗と対策5選",
    description: "宇部市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>宇部市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>宇部市では希望園を複数記入できます。工業都市で共働き率が高いため人気園の競争率は高いです。</p><h2>失敗3：同居祖父母の影響を把握していない</h2><p>宇部市では65歳未満の祖父母が同居し保育できる状態の場合、-3点の減点があります。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、きょうだい在園で+3点、認可外利用で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：就労証明書の就労時間記載漏れ</h2><p>就労時間の記載が不正確だと指数計算に影響します。勤務先に正確に記入してもらいましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "ube",
    title: "宇部市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "宇部市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育所への入所を目指して活動することです。宇部市は山口県の南西部に位置し、人口約16万人。宇部興産をはじめ化学・素材産業が集積する工業都市で、共働き世帯が多い地域です。</p><h2>宇部市の保育施設の種類</h2><ul><li>認可保育所：宇部市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可外だが届出済みの施設。</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 37,
  },
  {
    slug: "point-system",
    citySlug: "ube",
    title: "宇部市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "宇部市の保育所入所選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>宇部市の保育所入所は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大20点、合計40点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。</p><h3>就労時間別の基本指数</h3><ul><li>月160時間以上：20点</li><li>月140〜160時間未満：18点</li><li>月120〜140時間未満：16点</li><li>月80〜120時間未満：12点</li><li>月64〜80時間未満：8点</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 45,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "ube",
    title: "宇部市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "宇部市の保育所入所選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。宇部市の主な調整指数は以下の通りです。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+5点</li><li>きょうだいが希望施設に在園中：+3点</li><li>きょうだいと同時申込み：+2点</li><li>生活保護受給：+3点</li><li>認可外保育施設に月ぎめで利用中：+3点</li><li>育児休業から復帰予定：+2点</li></ul><h3>減算項目</h3><ul><li>65歳未満の祖父母が同居し保育可能：-3点</li></ul><div class="point-box"><p>同居の祖父母が保育できる状態だと-3点の減点になります。祖父母の就労状況を事前に把握しておきましょう。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 42,
  },
  {
    slug: "selection-process",
    citySlug: "ube",
    title: "宇部市の保育所選考フロー　書類提出から入所決定まで",
    description: "宇部市の保育所入所選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>10〜11月に、宇部市保育幼稚園課へ提出します。就労証明書など必要書類を揃えましょう。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>宇部市が申込書類に基づいて指数を計算します。基本指数（父母各最大20点）と調整指数の合計が選考指数です。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望施設との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月中旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-11",
    popularity: 36,
  },
  {
    slug: "score-up-checklist",
    citySlug: "ube",
    title: "宇部市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "宇部市の入所選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親世帯で就労中→+5点</li><li>きょうだいが希望施設に在園中→+3点</li><li>きょうだいと同時申込み→+2点</li><li>生活保護受給中→+3点</li><li>認可外保育施設に月ぎめで利用中→+3点</li><li>育休から復帰予定→+2点</li></ul><div class="point-box"><p>宇部市では複数の加点条件が合算されます。特に認可外保育施設利用（+3点）は一度不承諾になった後の再申請で有効な手段です。</p></div><h2>注意：祖父母が同居している場合</h2><p>65歳未満の祖父母が同居し保育できる場合は-3点です。祖父母の就労状況を正確に申告しましょう。</p>`,
    publishedAt: "2026-05-11",
    popularity: 48,
  },
  {
    slug: "area-guide",
    citySlug: "ube",
    title: "宇部市の保育所マップ　エリアごとの入りやすさを比較",
    description: "宇部市内のエリアごとの保育所の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>宇部市の保育所事情</h2><p>宇部市は山口県の南西部に位置する人口約16万人の都市です。化学・素材・重工業の大企業が多く、共働き世帯が多い工業都市です。市内に認可保育所が25か所以上あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>宇部新川駅周辺・東岐波地区：市街地中心部で人気集中</li><li>小串・西岐波地区：住宅地開発が進む地域</li></ul><h3>比較的入りやすいエリア</h3><ul><li>楠・船木地区：市の北部エリア、空きがある施設も</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 32,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "ube",
    title: "宇部市の認可外保育施設ガイド　認可所との違いは？",
    description: "宇部市で認可保育所に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。宇部市内にも複数存在します。</p><h2>認可所との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の調整指数</td><td>-</td><td>+3点の加点</td></tr></table><div class="point-box"><p>宇部市では認可外保育施設に月ぎめで預けている場合、翌年度の選考で+3点の加点があります。一度不承諾になっても認可外に預けながら再申請すると入りやすくなります。</p></div>`,
    publishedAt: "2026-05-11",
    popularity: 33,
  },
  {
    slug: "ikukyuu-guide",
    citySlug: "ube",
    title: "宇部市で育休から保育所へ復帰する流れ",
    description: "宇部市で育児休業から認可保育所に入所して職場復帰するための手順を解説します。",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>育休中の保活スケジュール</h2><p>育休中の保護者が4月入所を目指す場合、育休終了時期と入所時期を合わせることが重要です。</p><h2>育休復帰の加点について</h2><p>宇部市では、育児休業から復帰予定の場合、調整指数で+2点の加点があります。復職予定の書類を準備して申込みましょう。</p><h2>注意点</h2><ul><li>内定後に育休を延長した場合、入所が取り消されることがあります</li><li>入所後に就労実態がない場合は退所となる場合があります</li><li>化学・工業系の職場は交替勤務が多いため、就労時間の月換算を正確に記入しましょう</li></ul>`,
    publishedAt: "2026-05-11",
    popularity: 37,
  },
];

registerArticles(articles);
