import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "urasoe",
    title: "浦添市の保活スケジュール　令和8年度4月入園の流れ",
    description: "浦添市の認可保育園の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>浦添市は沖縄県の中南部に位置する人口約12万人の都市で、那覇市の北西に隣接しています。申込先は浦添市保育課です。</p><h2>一次利用調整</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年11月上旬〜12月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月下旬</td></tr></table><h2>二次利用調整</h2><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>一次で不承諾だった方は自動的に二次の対象になります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 38,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "urasoe",
    title: "浦添市の保活でよくある失敗と対策5選",
    description: "浦添市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>浦添市の4月入園の申込は11月から始まります。見学の予約が埋まる前に動きましょう。</p><h2>失敗2：希望園を少なく書く</h2><p>浦添市では希望園を複数記入できます。1〜2園しか書かないと不承諾のリスクが高まります。</p><h2>失敗3：自分の点数を把握していない</h2><p>浦添市では基本指数＋調整指数で選考されます。フルタイム共働きで40点が基本ラインです。</p><h2>失敗4：加点の取りこぼし</h2><p>育休前在園・職場復帰で+20点、保育士就労で+18点の加点がつきます。使える加点は漏れなくチェックしましょう。</p><h2>失敗5：書類の不備</h2><p>就労証明書の記入漏れや指定様式以外の提出は受理されない場合があります。</p>`,
    publishedAt: "2026-05-08",
    popularity: 42,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "urasoe",
    title: "浦添市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "浦添市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育園への入園を目指して活動することです。浦添市は沖縄県の中南部に位置し、人口約12万人の住宅密集地です。</p><h2>浦添市の保育園の種類</h2><ul><li>認可保育園：浦添市が認可した園。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li><li>認可外保育施設：認可基準を満たさないが届出済みの施設。</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 35,
  },
  {
    slug: "point-system",
    citySlug: "urasoe",
    title: "浦添市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "浦添市の保育園入園選考で最も重要な基本指数システムについて、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>基本指数とは</h2><p>浦添市の保育園入園は指数方式です。基本指数は父母それぞれの「保育が必要な理由」を数値化したものです。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>フルタイム共働きの場合</h2><p>父・母ともに月160時間以上の就労で、各20点ずつ、基本指数の合計は40点になります。就労時間によって段階的に減点されます。</p><h3>就労時間と点数の関係</h3><ul><li>月160時間以上：20点</li><li>月140～160時間未満：18点</li><li>月64～80時間：10点</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 45,
  },
  {
    slug: "scoring-system-guide",
    citySlug: "urasoe",
    title: "浦添市の入園点数のしくみ　基本指数と調整指数をやさしく解説",
    description: "浦添市の保育園入園選考で使われる基本指数と調整指数の仕組みを、初めての方にもわかるように解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>調整指数とは？</h2><p>世帯の特別な事情に応じて加減される点数です。浦添市の調整指数は他の自治体と比較して独自の項目が多いのが特徴です。</p><h3>主な加算項目</h3><ul><li>ひとり親世帯：+46点</li><li>育休前在園・職場復帰：+20点</li><li>保育士就労（沖縄本島内認可保育所等）：+18点</li><li>きょうだい在園施設へ申込：+3点</li><li>きょうだい同時申込：+1点</li></ul><div class="point-box"><p>ひとり親世帯の加点が46点と非常に高いのが浦添市の特徴です。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 50,
  },
  {
    slug: "selection-process",
    citySlug: "urasoe",
    title: "浦添市の保育園選考フロー　書類提出から入園決定まで",
    description: "浦添市の保育園入園選考の全フローを、各ステップごとに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "選考のしくみ",
    categoryColor: "blue",
    content: `<h2>選考フロー</h2><div class="step"><div class="step-num">1</div><div class="step-content"><strong>申込書・必要書類の提出</strong><p>11〜12月中に、浦添市保育課へ提出します。沖縄県の他市町村から申込することも可能です。</p></div></div><div class="step"><div class="step-num">2</div><div class="step-content"><strong>指数の計算</strong><p>浦添市が申込書類に基づいて指数を計算します。</p></div></div><div class="step"><div class="step-num">3</div><div class="step-content"><strong>利用調整</strong><p>指数の高い順に、希望園との相性を調整します。</p></div></div><div class="step"><div class="step-num">4</div><div class="step-content"><strong>結果通知</strong><p>一次は1月下旬、二次は3月上旬に通知が届きます。</p></div></div>`,
    publishedAt: "2026-05-08",
    popularity: 41,
  },
  {
    slug: "score-up-checklist",
    citySlug: "urasoe",
    title: "浦添市で点数を1点でも上げる方法　加点のチェックリスト",
    description: "浦添市の入園選考で調整指数の加点を最大限に活用する方法を、チェックリスト形式で解説します。",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=400&fit=crop",
    category: "点数アップ",
    categoryColor: "amber",
    content: `<h2>加点チェックリスト</h2><ul><li>ひとり親で就労中→+46点</li><li>育休前に同園に在園していた→+20点</li><li>職場復帰予定で同園を希望→+20点</li><li>保育士資格で沖縄本島内認可保育所等で就労→+18点</li><li>きょうだいが希望施設に在園中→+3点</li><li>きょうだいと同時申込→+1点</li></ul><div class="point-box"><p>浦添市ではひとり親世帯の加点が特に高いため、ひとり親世帯の方が優先される傾向にあります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 48,
  },
  {
    slug: "area-guide",
    citySlug: "urasoe",
    title: "浦添市の保育園マップ　エリアごとの入りやすさを比較",
    description: "浦添市内のエリアごとの保育園の競争率や特徴をまとめました。",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop",
    category: "エリア情報",
    categoryColor: "purple",
    content: `<h2>浦添市の保育園事情</h2><p>浦添市は沖縄県の中南部に位置する人口約12万人の都市です。那覇市に隣接し、ベッドタウンとして発展しています。認可保育園は約35か所あります。</p><h2>エリアごとの競争率</h2><h3>競争率が高いエリア</h3><ul><li>牧港・経塚周辺：モノレール駅に近く、利便性が高い</li><li>宮城地域：住宅団地があり、需要が高い</li></ul><h3>比較的入りやすいエリア</h3><ul><li>当間・西原エリア：山間部で人口密度が低い</li><li>仲間地域：新規園の開設により空きが増加中</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 36,
  },
  {
    slug: "ninkagai-guide",
    citySlug: "urasoe",
    title: "浦添市の認可外保育施設ガイド　認可園との違いは？",
    description: "浦添市で認可園に入れなかった場合の選択肢として、認可外保育施設について解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "認可外保育",
    categoryColor: "teal",
    content: `<h2>認可外保育施設とは？</h2><p>認可外保育施設は、認可基準を満たしていないものの、自治体に届出をして運営している保育施設です。浦添市には複数の認可外施設があります。</p><h2>認可園との違い</h2><table><tr><th>項目</th><th>認可</th><th>認可外</th></tr><tr><td>保育料</td><td>所得に応じて決定</td><td>施設が設定</td></tr><tr><td>翌年の入園加点</td><td>-</td><td>なし</td></tr><tr><td>施設数</td><td>約35か所</td><td>複数</td></tr></table><div class="point-box"><p>浦添市では認可外施設を利用しても、次年度の加点対象にはなりません。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 33,
  },
  {
    slug: "nursery-fees",
    citySlug: "urasoe",
    title: "浦添市の保育料はいくら？　世帯年収別の目安を紹介",
    description: "浦添市の認可保育園の保育料を世帯年収別にわかりやすく紹介します。無償化の対象も解説。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "お金の話",
    categoryColor: "rose",
    content: `<h2>3歳以上は無償化</h2><p>2019年10月からの幼児教育・保育の無償化により、3歳児クラス以上の保育料は無料です。浦添市もこの制度に対応しています。</p><h2>世帯年収別の保育料の目安（0～2歳児）</h2><table><tr><th>世帯年収の目安</th><th>月額保育料の目安</th></tr><tr><td>～300万円</td><td>0～5,000円</td></tr><tr><td>300～500万円</td><td>8,000～20,000円</td></tr><tr><td>500～700万円</td><td>22,000～35,000円</td></tr><tr><td>700～1,000万円</td><td>35,000～50,000円</td></tr></table><div class="point-box"><p>浦添市では第2子の保育料は半額、第3子以降は無料になります。</p></div>`,
    publishedAt: "2026-05-08",
    popularity: 39,
  },
  {
    slug: "nursery-visit-guide",
    citySlug: "urasoe",
    title: "浦添市の保育園見学ガイド　チェックポイントと質問リスト",
    description: "浦添市の保育園見学で確認すべきポイントと、先輩ママが聞いてよかった質問をまとめました。",
    image: "https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>見学はいつ行くのがベスト？</h2><p>6月～9月が見学のベストシーズンです。浦添市は沖縄のため、夏場は日差しが強いので、午前中の見学がおすすめです。</p><h2>見学時のチェックポイント</h2><ul><li>園児たちの表情や雰囲気</li><li>保育士の子どもへの接し方</li><li>園庭や室内の広さ・清潔さ</li><li>給食の内容（アレルギー対応・沖縄食への対応）</li></ul><h2>聞いておきたい質問リスト</h2><ul><li>延長保育は何時まで？料金は？</li><li>慣らし保育の期間はどのくらい？</li><li>沖縄特有の行事（エイサー等）への対応</li><li>急な発熱時のお迎えルール</li></ul>`,
    publishedAt: "2026-05-08",
    popularity: 37,
  },
];

registerArticles(articles);
