import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の保活スケジュール　令和8年度4月入園の流れ",
    description: "大和郡山市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>大和郡山市は奈良県北部に位置し、人口約8万2千人の都市です。近鉄橿原線・田原本線が通り、金魚の養殖で有名です。大和郡山城跡がある歴史ある城下町で、奈良市・天理市に隣接しています。申込先は大和郡山市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>大和郡山市の選考指数は父母各10点の合計20点満点（加算方式20点制）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 37,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の保活でよくある失敗と対策5選",
    description: "大和郡山市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>大和郡山市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>大和郡山市は奈良県北部の歴史ある城下町で、働く親世帯も多いです。人気施設の競争率は高いです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>大和郡山市は父母各20点の合計40点制（加算方式）です。月48時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+12点、きょうだい在園で+3点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：祖父母同居の減点を見落とす</h2><p>大和郡山市では65歳未満の同居祖父母が保育できる状態の場合に-3点となります。同居祖父母の就労状況を確認しておきましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 41,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "yamatokooriyama",
    title: "大和郡山市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "大和郡山市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。大和郡山市は奈良県北部に位置し、人口約8万2千人の都市です。金魚の町として知られ、歴史ある大和郡山城跡を持つ城下町です。</p><h2>大和郡山市の保育施設の種類</h2><ul><li>認可保育所：大和郡山市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-15",
    popularity: 39,
  },
  {
    slug: "point-system",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の基本指数システム　40点満点の仕組みをわかりやすく",
    description: "大和郡山市の保育施設入園選考で最も重要な基本指数（父母各20点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>大和郡山市の保育施設入園は指数方式（加算方式20点制）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：10点</li><li>月140〜160時間未満：9点</li><li>月120〜140時間未満：8点</li><li>月100〜120時間未満：7点</li><li>月80〜100時間未満：6点</li><li>月48〜80時間未満：4点</li></ul>`,
    publishedAt: "2026-05-15",
    popularity: 43,
  },
  {
    slug: "adjustment-index",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の調整指数ガイド　加点・減点の全項目まとめ",
    description: "大和郡山市の保育入園選考で基本指数に加算・減算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>大和郡山市では基本指数に加えて、世帯の状況に応じた調整指数が加減算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親家庭等</td><td>+12点</td></tr><tr><td>既に兄弟姉妹が同一保育園に入所</td><td>+3点</td></tr><tr><td>3人以上の児童がいる</td><td>+3点</td></tr><tr><td>家庭状況により特別な支援が必要</td><td>+5点</td></tr><tr><td>生活保護受給世帯</td><td>+4点</td></tr><tr><td>市内認可保育園・こども園に復職・就職する保育士（常勤以外）</td><td>+10点</td></tr><tr><td>市内認可保育園・こども園に復職・就職する保育士（常勤）</td><td>+15点</td></tr></table><h2>減点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>保育料の滞納がある</td><td>-10点</td></tr><tr><td>同一年度内に内定を辞退した</td><td>-2点</td></tr><tr><td>申込児童は市内認可保育園へ入所中</td><td>-4点</td></tr></table>`,
    publishedAt: "2026-05-15",
    popularity: 45,
  },
  {
    slug: "single-parent",
    citySlug: "yamatokooriyama",
    title: "大和郡山市のひとり親家庭の保活　+12点加点の活用法",
    description: "大和郡山市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>大和郡山市では、ひとり親世帯に対して+12点の調整指数加点があります。フルタイム就労10点＋ひとり親12点で22点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+12点）を活用することで、入園の可能性を大きく高めることができます。</p>`,
    publishedAt: "2026-05-15",
    popularity: 35,
  },
  {
    slug: "working-mothers",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "大和郡山市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>大和郡山市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月140〜160時間未満</td><td>9点</td></tr><tr><td>月120〜140時間未満</td><td>8点</td></tr><tr><td>月100〜120時間未満</td><td>7点</td></tr><tr><td>月80〜100時間未満</td><td>6点</td></tr><tr><td>月48〜80時間未満</td><td>4点</td></tr></table><h2>奈良県内の動向</h2><p>大和郡山市は奈良市・天理市に隣接しており、多くの労働者が広域通勤しています。フルタイム就労世帯が多く、点数計算が重要になります。</p>`,
    publishedAt: "2026-05-15",
    popularity: 48,
  },
  {
    slug: "ikukyu-return",
    citySlug: "yamatokooriyama",
    title: "大和郡山市で育休復帰を目指すママへ　保活と育休のタイミング",
    description: "大和郡山市で育休から復帰するタイミングで保活をする方向けに、保活スケジュールと基準について解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰と保活のタイミング</h2><p>大和郡山市で育休から復帰するタイミングで保活をする場合、大和郡山市の保育実施選考基準に基づいて選考が行われます。</p><h2>保活スケジュール</h2><ul><li>育児休業期間中の基本指数の申告：育児休業中の状況で基本指数が決定されます</li><li>一次利用調整：10月中旬〜11月上旬の申込受付</li><li>復職予定の書類提出：事業主からの復職予定証明書を提出します</li></ul><div class="point-box"><p>大和郡山市の基準表にはこの項目はありません。育児休業からの復帰に関しては、申込時に直接大和郡山市子育て支援課に確認することをお勧めします。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 41,
  },
  {
    slug: "nursery-facilities",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の認可保育施設一覧　地区別の施設数と特徴",
    description: "大和郡山市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>大和郡山市の保育施設の概要</h2><p>大和郡山市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。郡山駅周辺や城下町中心部、西部地区に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>郡山駅周辺・城下町：施設数が多く利便性が高い</li><li>中部地区：定員に比較的余裕のある施設が多い</li><li>東部・南部地区：施設数が限定的だが、通勤路線で補完</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 33,
  },
  {
    slug: "grandparent-deduction",
    citySlug: "yamatokooriyama",
    title: "大和郡山市の祖父母同居の減点　-3点の条件と対処法",
    description: "大和郡山市で65歳未満の同居祖父母がいる場合の減点（-3点）について、条件と対処法を解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>祖父母同居の減点とは</h2><p>大和郡山市では、65歳未満の同居祖父母が保育できる状態にある場合、-3点の調整指数が適用されます。</p><h2>減点が適用される条件</h2><ul><li>65歳未満の祖父母が同居している</li><li>その祖父母が保育可能な状態（無職・就労時間が少ない等）</li></ul><h2>減点が適用されない条件</h2><ul><li>同居祖父母が65歳以上の場合</li><li>同居祖父母がフルタイムで就労している場合</li><li>同居祖父母が疾病・障害等で保育不可能な場合</li></ul><div class="point-box"><p>同居祖父母が就労している場合は就労証明書を提出することで減点を回避できる場合があります。市役所に確認しましょう。</p></div>`,
    publishedAt: "2026-05-15",
    popularity: 37,
  },
];

registerArticles(articles);
