import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "yatsushiro",
    title: "八代市の保活スケジュール　令和8年度4月入園の流れ",
    description: "八代市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>八代市は熊本県南部に位置し、人口約12万4千人の都市です。日本有数のい草産地として知られ、八代港を擁する物流拠点都市です。申込先は八代市子ども未来部子ども政策課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>八代市の選考点数は父母各100点の合計200点満点（熊本県標準方式）です。フルタイム共働きで200点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "yatsushiro",
    title: "八代市の保活でよくある失敗と対策5選",
    description: "八代市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>八代市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>八代市はい草産業・物流業が盛んで共働き世帯も多い地域です。人気施設の競争率は高めです。希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>八代市は父母各100点の合計200点制（熊本県標準方式）です。月48時間未満では基本点数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+10点、きょうだい在園で+5点、小規模卒園で+10点、認可外利用で+5点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：勤務証明書の記載不備</h2><p>就労時間は正確に記載する必要があります。勤務証明書の月間就労時間の記載漏れが多いのでご注意ください。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "yatsushiro",
    title: "八代市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "八代市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。八代市は熊本県南部に位置し、人口約12万4千人。日本有数のい草産地として知られる農工業都市です。</p><h2>八代市の保育施設の種類</h2><ul><li>認可保育所：八代市が認可した施設。保育料は世帯年収に応じて決定。選考は点数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "yatsushiro",
    title: "八代市の基本点数システム　200点満点の仕組みをわかりやすく",
    description: "八代市の保育施設入園選考で最も重要な基本点数（父母各100点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本点数とは</h2><p>八代市の保育施設入園は点数方式（熊本県標準方式）です。基本点数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大100点、合計200点が基本点数の満点です。</p><div class="point-box"><p>選考点数＝基本点数（父）＋基本点数（母）＋調整点数</p></div><h2>就労時間別の基本点数</h2><ul><li>月160時間以上：100点</li><li>月120〜160時間未満：90点</li><li>月96〜120時間未満：80点</li><li>月64〜96時間未満：70点</li><li>月48〜64時間未満：60点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "yatsushiro",
    title: "八代市の調整点数ガイド　加点の全項目まとめ",
    description: "八代市の保育入園選考で基本点数に加算される調整点数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整点数とは</h2><p>八代市では基本点数に加えて、世帯の状況に応じた調整点数が加算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+10点</td></tr><tr><td>きょうだいが在園中の園を希望</td><td>+5点</td></tr><tr><td>きょうだいと同時申込み</td><td>+3点</td></tr><tr><td>認可外保育施設に月ぎめで利用中</td><td>+5点</td></tr><tr><td>育児休業から復帰予定</td><td>+5点</td></tr><tr><td>生活保護受給世帯</td><td>+5点</td></tr><tr><td>小規模保育等の卒園に伴う転所</td><td>+10点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "yatsushiro",
    title: "八代市のひとり親家庭の保活　+10点加点の活用法",
    description: "八代市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>八代市では、ひとり親世帯に対して+10点の調整点数が加算されます。フルタイム就労100点＋ひとり親10点で110点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+10点）に加えて認可外利用中（+5点）、育休復帰（+5点）なども活用できます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "yatsushiro",
    title: "八代市の働くママの保活攻略法　フルタイムvs時短の点数差",
    description: "八代市でフルタイム・時短などさまざまな働き方をするママが、どのような点数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本点数</h2><p>八代市では就労時間が長いほど高い点数が付与されます。</p><table><tr><th>就労時間</th><th>基本点数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>100点</td></tr><tr><td>月120〜160時間未満</td><td>90点</td></tr><tr><td>月96〜120時間未満</td><td>80点</td></tr><tr><td>月64〜96時間未満</td><td>70点</td></tr><tr><td>月48〜64時間未満</td><td>60点</td></tr></table><h2>い草・農業・物流業の場合</h2><p>八代市はい草産業や物流業が盛んです。季節変動や交代制勤務の場合も、実際の月間就労時間で点数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "yatsushiro",
    title: "八代市で育休復帰を目指すママへ　+5点加点の活用法",
    description: "八代市で育休から復帰するタイミングで保活をする方向けに、育休復帰加点（+5点）の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+5点）</h2><p>八代市では、育児休業から復帰して入園する場合に+5点の調整点数が加算されます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園月に職場復帰すること</li><li>事業主からの復職予定証明書が必要</li></ul><div class="point-box"><p>フルタイム100点＋育休復帰+5点で105点が確保できます。さらに認可外利用（+5点）も組み合わせることで110点まで上げることができます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "yatsushiro",
    title: "八代市の認可保育施設一覧　地区別の施設数と特徴",
    description: "八代市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>八代市の保育施設の概要</h2><p>八代市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。八代駅周辺や市内各地に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>八代駅・市街地周辺：施設数が多く利便性が高い</li><li>東陽・泉地区：農村部で施設数は少ない</li><li>日奈久・鏡地区：比較的定員に余裕のある施設が多い</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "small-nursery",
    citySlug: "yatsushiro",
    title: "八代市の小規模保育卒園後の転所　+10点加点の活用法",
    description: "八代市で小規模保育等を卒園する際の転所加点（+10点）について解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>小規模保育卒園加点とは</h2><p>八代市では、小規模保育事業等（0〜2歳児）を卒園する際に転所を希望する場合、+10点の調整点数が加算されます。</p><h2>加点を受けるための条件</h2><ul><li>小規模保育事業・家庭的保育・事業所内保育などの卒園児であること</li><li>在籍施設から卒園証明書を取得すること</li></ul><div class="point-box"><p>小規模保育卒園加点（+10点）は非常に大きな加点です。0〜2歳での小規模保育入園が3歳以降の保活を有利にします。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
];

registerArticles(articles);
