import type { Article } from "./types";
import { registerArticles } from "./index";

const articles: Article[] = [
  {
    slug: "hokatsu-schedule",
    citySlug: "yonago",
    title: "米子市の保活スケジュール　令和8年度4月入園の流れ",
    description: "米子市の認可保育施設の申込時期・選考の流れ・結果通知の時期をわかりやすく解説。令和8年度4月入園のスケジュールを中心にまとめました。",
    image: "https://images.unsplash.com/photo-1484820540004-14229fe36ca4?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>令和8年度4月入園のスケジュール</h2><p>米子市は鳥取県西部に位置し、人口約14万5千人の都市です。山陰地方の主要都市として商業・医療・物流の中心的役割を担っています。申込先は米子市子育て支援課です。</p><h3>一次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和7年10月中旬〜11月上旬</td></tr><tr><td>結果通知</td><td>令和8年1月中旬</td></tr></table><h3>二次利用調整</h3><table><tr><th>項目</th><th>日程</th></tr><tr><td>申込受付期間</td><td>令和8年2月上旬〜2月中旬</td></tr><tr><td>結果通知</td><td>令和8年3月上旬</td></tr></table><div class="point-box"><p><strong>ポイント</strong></p><p>米子市の選考指数は父母各10点の合計20点満点（鳥取県標準方式）です。フルタイム共働きで20点が基本ラインです。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 36,
  },
  {
    slug: "hokatsu-mistakes",
    citySlug: "yonago",
    title: "米子市の保活でよくある失敗と対策5選",
    description: "米子市の保活で初めてのママがやりがちな失敗パターンと、その対策をまとめました。",
    image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>失敗1：情報収集のスタートが遅い</h2><p>米子市の4月入園の申込は10月から始まります。見学の予約は夏前から始めましょう。</p><h2>失敗2：希望施設を少なく書く</h2><p>米子市は山陰の商業・医療都市として共働き世帯が多い地域です。人気施設の競争率は高いため、希望施設はなるべく多く書きましょう。</p><h2>失敗3：自分の点数を把握していない</h2><p>米子市は父母各10点の合計20点制（鳥取県標準方式）です。月64時間未満では基本指数が付きません。</p><h2>失敗4：加点の取りこぼし</h2><p>ひとり親で+5点、育休復帰で+5点、小規模卒園連携で+10点など。使える加点を漏れなくチェックしましょう。</p><h2>失敗5：小規模卒園の連携施設を見逃す</h2><p>小規模保育卒園後に連携施設に転所する場合は+10点の大きな加点があります。連携施設への入所を積極的に検討しましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "hokatsu-basics",
    citySlug: "yonago",
    title: "米子市での保活、いつから始めるべき？新米ママ向けガイド",
    description: "米子市で初めて保活をする方向けに、いつから何を始めるべきかをステップごとに解説します。",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop",
    category: "保活の基本",
    categoryColor: "green",
    content: `<h2>保活ってなに？</h2><p>保活とは、認可保育施設への入園を目指して活動することです。米子市は鳥取県西部の中心都市で、人口約14万5千人。山陰地方の商業・医療・物流の拠点都市です。</p><h2>米子市の保育施設の種類</h2><ul><li>認可保育所：米子市が認可した施設。保育料は世帯年収に応じて決定。選考は指数方式。</li><li>小規模保育事業：定員6～19人の少人数保育。0～2歳児対象。</li><li>認定こども園：保育と教育の両方を行う施設。</li></ul><h2>いつから始めるべき？</h2><p>4月入園を目指す場合、前年の7〜8月には施設見学を始め、10月の申込受付に備えましょう。</p>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
  {
    slug: "point-system",
    citySlug: "yonago",
    title: "米子市の基本指数システム　20点満点の仕組みをわかりやすく",
    description: "米子市の保育施設入園選考で最も重要な基本指数（父母各10点）について、初心者向けに詳しく解説します。",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>基本指数とは</h2><p>米子市の保育施設入園は指数方式（鳥取県標準方式）です。基本指数は父母それぞれの「保育が必要な理由」を数値化したもので、父と母それぞれ最大10点、合計20点が基本指数の満点です。</p><div class="point-box"><p>選考指数＝基本指数（父）＋基本指数（母）＋調整指数</p></div><h2>就労時間別の基本指数</h2><ul><li>月160時間以上：10点</li><li>月140〜160時間未満：9点</li><li>月120〜140時間未満：8点</li><li>月100〜120時間未満：7点</li><li>月64〜100時間未満：6点</li></ul>`,
    publishedAt: "2026-05-12",
    popularity: 42,
  },
  {
    slug: "adjustment-index",
    citySlug: "yonago",
    title: "米子市の調整指数ガイド　加点の全項目まとめ",
    description: "米子市の保育入園選考で基本指数に加算される調整指数の全項目を解説します。",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>調整指数とは</h2><p>米子市では基本指数に加えて、世帯の状況に応じた調整指数が加算されます。</p><h2>加点項目</h2><table><tr><th>項目</th><th>点数</th></tr><tr><td>ひとり親世帯</td><td>+5点</td></tr><tr><td>育児休業から復帰予定</td><td>+5点</td></tr><tr><td>きょうだいが在園中の園を希望</td><td>+5点</td></tr><tr><td>きょうだい同時入所</td><td>+3点</td></tr><tr><td>生活保護受給世帯</td><td>+5点</td></tr><tr><td>小規模卒園（連携施設）</td><td>+10点</td></tr><tr><td>小規模卒園（連携施設以外）</td><td>+5点</td></tr><tr><td>障害のある子どもの入所</td><td>+3点</td></tr></table>`,
    publishedAt: "2026-05-12",
    popularity: 44,
  },
  {
    slug: "single-parent",
    citySlug: "yonago",
    title: "米子市のひとり親家庭の保活　+5点加点の活用法",
    description: "米子市でひとり親として保活をする方向けに、ひとり親加点の仕組みと活用方法を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>ひとり親加点の概要</h2><p>米子市では、ひとり親世帯に対して+5点の調整指数加点があります。フルタイム就労10点＋ひとり親5点で15点が目安となります。</p><h2>ひとり親世帯の認定条件</h2><ul><li>離婚・死別等によるひとり親（母子・父子家庭）</li><li>未婚のひとり親</li></ul><p>ひとり親加点（+5点）に加えて育休復帰加点（+5点）、生活保護受給（+5点）なども活用できます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 34,
  },
  {
    slug: "working-mothers",
    citySlug: "yonago",
    title: "米子市の働くママの保活攻略法　フルタイムvs時短の指数差",
    description: "米子市でフルタイム・時短などさまざまな働き方をするママが、どのような指数になるかを解説します。",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>働き方別の基本指数</h2><p>米子市では就労時間が長いほど高い指数が付与されます。</p><table><tr><th>就労時間</th><th>基本指数</th></tr><tr><td>月160時間以上（フルタイム）</td><td>10点</td></tr><tr><td>月140〜160時間未満</td><td>9点</td></tr><tr><td>月120〜140時間未満</td><td>8点</td></tr><tr><td>月100〜120時間未満</td><td>7点</td></tr><tr><td>月64〜100時間未満</td><td>6点</td></tr></table><h2>医療・商業従事者の場合</h2><p>米子市は山陰地方の医療・商業都市です。病院や商業施設で働く方が多く、シフト制の場合も実際の月間就労時間で指数が計算されます。</p>`,
    publishedAt: "2026-05-12",
    popularity: 46,
  },
  {
    slug: "ikukyu-return",
    citySlug: "yonago",
    title: "米子市で育休復帰を目指すママへ　+5点加点の活用法",
    description: "米子市で育休から復帰するタイミングで保活をする方向けに、育休復帰加点（+5点）の仕組みと注意点を解説します。",
    image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&h=400&fit=crop",
    category: "家庭の状況別",
    categoryColor: "purple",
    content: `<h2>育休復帰加点（+5点）</h2><p>米子市では、育児休業から復帰して入園する場合に+5点の調整指数が加算されます。この加点は他の調整指数と合算できます。</p><h2>加点を得るための条件</h2><ul><li>育児休業取得中であること</li><li>入園が承諾された場合に速やかに復職すること</li><li>復職予定証明書など、事業主からの書類が必要</li></ul><div class="point-box"><p>育休復帰加点（+5点）はひとり親加点（+5点）とも合算できます。フルタイム10点＋育休+5点で15点が確保できます。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 40,
  },
  {
    slug: "nursery-facilities",
    citySlug: "yonago",
    title: "米子市の認可保育施設一覧　地区別の施設数と特徴",
    description: "米子市の認可保育所・認定こども園・小規模保育事業の施設数と、地区別の傾向をまとめました。",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&h=400&fit=crop",
    category: "施設選び",
    categoryColor: "amber",
    content: `<h2>米子市の保育施設の概要</h2><p>米子市には認可保育所・認定こども園・小規模保育事業など多数の保育施設があります。米子駅周辺や市内各地に施設が分布しています。</p><h2>地区別の傾向</h2><ul><li>米子駅周辺・市街地：施設数が多く利便性が高い</li><li>淀江・東山地区：比較的定員に余裕のある施設が多い</li><li>彦名・河崎地区：住宅地として発展中</li></ul><div class="point-box"><p>希望施設はなるべく多く記入することで入園の可能性が高まります。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 32,
  },
  {
    slug: "small-nursery",
    citySlug: "yonago",
    title: "米子市の小規模保育卒園後の転所　連携施設への+10点加点",
    description: "米子市で小規模保育等を卒園する際の連携施設への転所加点（+10点）について解説します。",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
    category: "点数の仕組み",
    categoryColor: "blue",
    content: `<h2>小規模保育卒園加点とは</h2><p>米子市では、小規模保育事業等（0〜2歳児）を卒園する際に連携施設への入所を希望する場合、+10点の調整指数が加算されます。連携施設以外への入所希望でも+5点が適用されます。</p><h2>加点を受けるための条件</h2><ul><li>小規模保育事業等の卒園児であること</li><li>連携施設への入所を希望していること</li></ul><div class="point-box"><p>小規模保育卒園後の連携施設への転所加点（+10点）は非常に大きな加点です。0〜2歳での小規模保育入園が3歳以降の保活を有利にします。</p></div>`,
    publishedAt: "2026-05-12",
    popularity: 38,
  },
];

registerArticles(articles);
